<?php
/**
* WoltLab Community Framework
* language: de-informal
* encoding: UTF-8
* category: wcf.user.register
* generated at Tue, 13 Aug 2013 11:37:05 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.register.activation'] = 'Abschließen der Registrierung';
$this->items[$this->languageID]['wcf.user.register.activation.code'] = '9-stelliger Aktivierungscode';
$this->items[$this->languageID]['wcf.user.register.activation.error.code.notValid'] = 'Du hast einen ungültigen Aktivierungscode eingegeben. Klick <a href="index.php?page=Register&amp;action={if $action == \'enable\'}newActivationCode{else}newReactivationCode{/if}{@SID_ARG_2ND}">hier</a>, um einen neuen Aktivierungscode anzufordern.';
$this->dynamicItems[$this->languageID]['wcf.user.register.activation.error.code.notValid'] = 'Du hast einen ungültigen Aktivierungscode eingegeben. Klick <a href="index.php?page=Register&amp;action=<?php if ($this->v[\'action\'] == \'enable\') { ?>newActivationCode<?php } else { ?>newReactivationCode<?php } ?><?php echo SID_ARG_2ND; ?>">hier</a>, um einen neuen Aktivierungscode anzufordern.';
$this->items[$this->languageID]['wcf.user.register.activation.error.userID.notValid'] = 'Du hast eine ungültige Benutzernummer eingegeben.';
$this->items[$this->languageID]['wcf.user.register.activation.redirect'] = 'Dein Benutzerkonto wurde erfolgreich freigeschaltet. Du kannst dich jetzt mit deinen Benutzerdaten anmelden.';
$this->items[$this->languageID]['wcf.user.register.activation.userID'] = 'Benutzernummer';
$this->items[$this->languageID]['wcf.user.register.awaitActivation'] = 'Vielen Dank für die Registrierung, {$username}. Deine Benutzerdaten werden in Kürze von einem Administrator geprüft.<br />
Sobald dein Benutzerkonto freigeschaltet ist, wirst du per E-Mail darüber in Kenntnis gesetzt.';
$this->dynamicItems[$this->languageID]['wcf.user.register.awaitActivation'] = 'Vielen Dank für die Registrierung, <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>. Deine Benutzerdaten werden in Kürze von einem Administrator geprüft.<br />
Sobald dein Benutzerkonto freigeschaltet ist, wirst du per E-Mail darüber in Kenntnis gesetzt.';
$this->items[$this->languageID]['wcf.user.register.confirmEmail.description'] = 'Bitte wiederhole zur Sicherheit die Eingabe deiner E-Mail-Adresse!';
$this->items[$this->languageID]['wcf.user.register.confirmPassword.description'] = 'Bitte wiederhole zur Sicherheit die Eingabe deines Kennworts!';
$this->items[$this->languageID]['wcf.user.register.disclaimer'] = '<p>Die Registrierung und Benutzung der Website &raquo;{lang}{PAGE_TITLE}{/lang}&laquo; sind völlig kostenlos. Klicke auf &raquo;Akzeptieren&laquo;, wenn du die hier genannten Regeln und Erklärungen anerkennst. Danach kannst du dich registrieren.</p>

<p>Die Administratoren und Moderatoren der Website &raquo;{lang}{PAGE_TITLE}{/lang}&laquo; versuchen, unerwünschte Beiträge von dieser Website fernzuhalten, es ist jedoch unmöglich, alle Inhalte manuell zu überprüfen. Alle Beiträge drücken ausschließlich die Ansichten der Autoren selbst aus. Die Eigentümer der Website &raquo;{lang}{PAGE_TITLE}{/lang}&laquo; oder die WoltLab GmbH (Entwickler der verwendeten Software) können nicht für den Inhalt einzelner Beiträge verantwortlich gemacht werden.</p>

<p>Mit dem Vollenden der Registrierung erklärst du dich damit einverstanden, diese Website nicht für Obszönitäten, Vulgäres, Beleidigungen, Propaganda, (extreme) politische Ansichten oder (verbale) Verstöße gegen das Gesetz zu missbrauchen.</p>

<p>Beiträge und Benutzerkonten können durch Moderatoren und Administratoren dieser Website, u.a. aus Gründen des Verstoßes gegen die guten Sitten, ohne weitere Begründung editiert oder gelöscht werden.</p>

<p>Viel Spaß beim Nutzen der Website &raquo;{lang}{PAGE_TITLE}{/lang}&laquo;!</p>';
$this->dynamicItems[$this->languageID]['wcf.user.register.disclaimer'] = '<p>Die Registrierung und Benutzung der Website &raquo;<?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang55756e2c7ffd222d089063b13d1aa31be6e45ee0 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang55756e2c7ffd222d089063b13d1aa31be6e45ee0, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>&laquo; sind völlig kostenlos. Klicke auf &raquo;Akzeptieren&laquo;, wenn du die hier genannten Regeln und Erklärungen anerkennst. Danach kannst du dich registrieren.</p>

<p>Die Administratoren und Moderatoren der Website &raquo;<?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang57f35799fcc4fea1cca2ead337e71c96b6ba16f7 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang57f35799fcc4fea1cca2ead337e71c96b6ba16f7, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>&laquo; versuchen, unerwünschte Beiträge von dieser Website fernzuhalten, es ist jedoch unmöglich, alle Inhalte manuell zu überprüfen. Alle Beiträge drücken ausschließlich die Ansichten der Autoren selbst aus. Die Eigentümer der Website &raquo;<?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang23dc4ed50d6cd5eb19714f7db6238fc9fc40137c = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang23dc4ed50d6cd5eb19714f7db6238fc9fc40137c, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>&laquo; oder die WoltLab GmbH (Entwickler der verwendeten Software) können nicht für den Inhalt einzelner Beiträge verantwortlich gemacht werden.</p>

<p>Mit dem Vollenden der Registrierung erklärst du dich damit einverstanden, diese Website nicht für Obszönitäten, Vulgäres, Beleidigungen, Propaganda, (extreme) politische Ansichten oder (verbale) Verstöße gegen das Gesetz zu missbrauchen.</p>

<p>Beiträge und Benutzerkonten können durch Moderatoren und Administratoren dieser Website, u.a. aus Gründen des Verstoßes gegen die guten Sitten, ohne weitere Begründung editiert oder gelöscht werden.</p>

<p>Viel Spaß beim Nutzen der Website &raquo;<?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langc8b5d59bd4bd90c6ab0a8bf14ad1ff2a9d40ac6a = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langc8b5d59bd4bd90c6ab0a8bf14ad1ff2a9d40ac6a, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>&laquo;!</p>';
$this->items[$this->languageID]['wcf.user.register.disclaimer.button.accept'] = 'Akzeptieren';
$this->items[$this->languageID]['wcf.user.register.disclaimer.button.decline'] = 'Ablehnen';
$this->items[$this->languageID]['wcf.user.register.disclaimer.title'] = 'Nutzungsbestimmungen';
$this->items[$this->languageID]['wcf.user.register.email.description'] = 'Bitte gib deine E-Mail-Adresse ein!';
$this->items[$this->languageID]['wcf.user.register.error.disabled'] = 'Die Registrierung ist momentan deaktiviert.';
$this->items[$this->languageID]['wcf.user.register.error.userAlreadyEnabled'] = 'Dieser Benutzer ist bereits freigeschaltet.';
$this->items[$this->languageID]['wcf.user.register.invitation'] = 'Registriere Dich jetzt!';
$this->items[$this->languageID]['wcf.user.register.needActivation'] = 'Vielen Dank für die Registrierung, {$username}.<br />
Wir haben dir eine E-Mail an {$email} geschickt. Die E-Mail enthält einen Link, den du einmalig aufrufen musst, um die Gültigkeit deiner E-Mail-Adresse zu bestätigen und damit deine Registrierung abzuschließen.';
$this->dynamicItems[$this->languageID]['wcf.user.register.needActivation'] = 'Vielen Dank für die Registrierung, <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>.<br />
Wir haben dir eine E-Mail an <?php echo StringUtil::encodeHTML($this->v[\'email\']); ?> geschickt. Die E-Mail enthält einen Link, den du einmalig aufrufen musst, um die Gültigkeit deiner E-Mail-Adresse zu bestätigen und damit deine Registrierung abzuschließen.';
$this->items[$this->languageID]['wcf.user.register.needActivation.mail'] = 'Hallo {$username}!

Vielen Dank für deine Registrierung auf der Website: {PAGE_TITLE}.
Bevor wir deine Registrierung aktivieren können, musst du einmalig die Gültigkeit deiner E-Mail-Adresse bestätigen.

Bitte bestätige die Gültigkeit deiner E-Mail-Adresse, indem du folgenden Link aufrufst:
{PAGE_URL}/index.php?page=Register&action=a&u={$userID}&a={$activationCode}

**** Funktioniert der Link oben nicht? ****
Wenn der Link nicht funktioniert, solltest du folgende Adresse in deinem Browser aufrufen:
{PAGE_URL}/index.php?page=Register&action=a

Bitte achte darauf, dass sich keine Leerzeichen in der Adresse befinden.
Wenn du den Link aufgerufen hast, musst du auf der erscheinenden Seite deine Benutzernummer sowie den Aktivierungscode eingeben.

Deine Benutzernummer lautet: 	{$userID}
Dein Aktivierungscode lautet: 	{$activationCode}

Wenn du Probleme mit der Aktivierung hast, wende dich bitte an den Administrator: {MAIL_ADMIN_ADDRESS}

Solltest du dich nicht auf der Website: {PAGE_TITLE} angemeldet haben, kannst du diese E-Mail ignorieren.

Vielen Dank,
dein {PAGE_TITLE} Team';
$this->dynamicItems[$this->languageID]['wcf.user.register.needActivation.mail'] = 'Hallo <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>!

Vielen Dank für deine Registrierung auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>.
Bevor wir deine Registrierung aktivieren können, musst du einmalig die Gültigkeit deiner E-Mail-Adresse bestätigen.

Bitte bestätige die Gültigkeit deiner E-Mail-Adresse, indem du folgenden Link aufrufst:
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?page=Register&action=a&u=<?php echo StringUtil::encodeHTML($this->v[\'userID\']); ?>&a=<?php echo StringUtil::encodeHTML($this->v[\'activationCode\']); ?>

**** Funktioniert der Link oben nicht? ****
Wenn der Link nicht funktioniert, solltest du folgende Adresse in deinem Browser aufrufen:
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?page=Register&action=a

Bitte achte darauf, dass sich keine Leerzeichen in der Adresse befinden.
Wenn du den Link aufgerufen hast, musst du auf der erscheinenden Seite deine Benutzernummer sowie den Aktivierungscode eingeben.

Deine Benutzernummer lautet: 	<?php echo StringUtil::encodeHTML($this->v[\'userID\']); ?>
Dein Aktivierungscode lautet: 	<?php echo StringUtil::encodeHTML($this->v[\'activationCode\']); ?>

Wenn du Probleme mit der Aktivierung hast, wende dich bitte an den Administrator: <?php echo StringUtil::encodeHTML(MAIL_ADMIN_ADDRESS); ?>

Solltest du dich nicht auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> angemeldet haben, kannst du diese E-Mail ignorieren.

Vielen Dank,
dein <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> Team';
$this->items[$this->languageID]['wcf.user.register.needActivation.mail.subject'] = 'Aktivierung der Registrierung auf der Website: {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.register.needActivation.mail.subject'] = 'Aktivierung der Registrierung auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.register.needsActivation'] = 'Dein Benutzerkonto ist noch nicht aktiviert. Du musst den <a href="index.php?page=Register&amp;action=enable{@SID_ARG_2ND}">Aktivierungsvorgang abschließen</a>, um den vollen Funktionsumfang dieser Seite nutzen zu können.';
$this->dynamicItems[$this->languageID]['wcf.user.register.needsActivation'] = 'Dein Benutzerkonto ist noch nicht aktiviert. Du musst den <a href="index.php?page=Register&amp;action=enable<?php echo SID_ARG_2ND; ?>">Aktivierungsvorgang abschließen</a>, um den vollen Funktionsumfang dieser Seite nutzen zu können.';
$this->items[$this->languageID]['wcf.user.register.newActivationCode'] = 'Neuen Aktivierungscode anfordern';
$this->items[$this->languageID]['wcf.user.register.newActivationCode.email.description'] = 'Optional kannst du hier eine neue E-Mail-Adresse eintragen, an die der neue Aktivierungscode gesendet werden soll. Lass dieses Feld frei, wenn der Aktivierungscode an die bestehende Adresse geschickt werden soll.';
$this->items[$this->languageID]['wcf.user.register.newActivationCode.success'] = 'Eine E-Mail mit dem neuen Aktivierungscode wurde an {$email} versendet.';
$this->dynamicItems[$this->languageID]['wcf.user.register.newActivationCode.success'] = 'Eine E-Mail mit dem neuen Aktivierungscode wurde an <?php echo StringUtil::encodeHTML($this->v[\'email\']); ?> versendet.';
$this->items[$this->languageID]['wcf.user.register.notification.mail'] = 'Hallo Administrator,

auf der Website: {PAGE_TITLE} erfolgte eine neue Benutzeranmeldung durch: {$username}';
$this->dynamicItems[$this->languageID]['wcf.user.register.notification.mail'] = 'Hallo Administrator,

auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> erfolgte eine neue Benutzeranmeldung durch: <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>';
$this->items[$this->languageID]['wcf.user.register.notification.mail.subject'] = 'Neue Benutzeranmeldung auf der Website: {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.register.notification.mail.subject'] = 'Neue Benutzeranmeldung auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.register.password.description'] = '{if REGISTER_ENABLE_PASSWORD_SECURITY_CHECK && REGISTER_PASSWORD_MIN_LENGTH}Das Kennwort muss mindestens {REGISTER_PASSWORD_MIN_LENGTH} Zeichen lang sein.{else}Ein sicheres Kennwort sollte mindestens 8 Zeichen lang sein.{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.register.password.description'] = '<?php if (REGISTER_ENABLE_PASSWORD_SECURITY_CHECK && REGISTER_PASSWORD_MIN_LENGTH) { ?>Das Kennwort muss mindestens <?php echo StringUtil::encodeHTML(REGISTER_PASSWORD_MIN_LENGTH); ?> Zeichen lang sein.<?php } else { ?>Ein sicheres Kennwort sollte mindestens 8 Zeichen lang sein.<?php } ?>';
$this->items[$this->languageID]['wcf.user.register.success'] = 'Vielen Dank für die Registrierung, {$username}. Deine Registrierung ist hiermit vollständig abgeschlossen.';
$this->dynamicItems[$this->languageID]['wcf.user.register.success'] = 'Vielen Dank für die Registrierung, <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>. Deine Registrierung ist hiermit vollständig abgeschlossen.';
$this->items[$this->languageID]['wcf.user.register.title'] = 'Registrieren';
$this->items[$this->languageID]['wcf.user.register.username.description'] = 'Der Benutzername muss mindestens {REGISTER_USERNAME_MIN_LENGTH} und darf maximal {REGISTER_USERNAME_MAX_LENGTH} Zeichen lang sein.';
$this->dynamicItems[$this->languageID]['wcf.user.register.username.description'] = 'Der Benutzername muss mindestens <?php echo StringUtil::encodeHTML(REGISTER_USERNAME_MIN_LENGTH); ?> und darf maximal <?php echo StringUtil::encodeHTML(REGISTER_USERNAME_MAX_LENGTH); ?> Zeichen lang sein.';
$this->items[$this->languageID]['wcf.user.register.welcome'] = 'Lieber Besucher, herzlich willkommen bei: {lang}{PAGE_TITLE}{/lang}.
Falls dies dein erster Besuch auf dieser Seite ist, lies bitte die <a href="index.php?page=Help{@SID_ARG_2ND}">Hilfe</a> durch. Dort wird dir die Bedienung dieser Seite näher erläutert.
Darüber hinaus solltest du dich registrieren, um alle Funktionen dieser Seite nutzen zu können.
Benutze das <a href="index.php?page=Register{@SID_ARG_2ND}">Registrierungsformular</a>, um dich zu registrieren oder <a href="index.php?page=Help&amp;item=user.login{@SID_ARG_2ND}">informiere dich ausführlich</a> über den Registrierungsvorgang.
Falls du dich bereits zu einem früheren Zeitpunkt registriert hast, kannst du dich <a href="index.php?form=UserLogin{@SID_ARG_2ND}">hier anmelden</a>.';
$this->dynamicItems[$this->languageID]['wcf.user.register.welcome'] = 'Lieber Besucher, herzlich willkommen bei: <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang982a5580430bc90d68eb9efdc0f1bf9e38d09fa9 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang982a5580430bc90d68eb9efdc0f1bf9e38d09fa9, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>.
Falls dies dein erster Besuch auf dieser Seite ist, lies bitte die <a href="index.php?page=Help<?php echo SID_ARG_2ND; ?>">Hilfe</a> durch. Dort wird dir die Bedienung dieser Seite näher erläutert.
Darüber hinaus solltest du dich registrieren, um alle Funktionen dieser Seite nutzen zu können.
Benutze das <a href="index.php?page=Register<?php echo SID_ARG_2ND; ?>">Registrierungsformular</a>, um dich zu registrieren oder <a href="index.php?page=Help&amp;item=user.login<?php echo SID_ARG_2ND; ?>">informiere dich ausführlich</a> über den Registrierungsvorgang.
Falls du dich bereits zu einem früheren Zeitpunkt registriert hast, kannst du dich <a href="index.php?form=UserLogin<?php echo SID_ARG_2ND; ?>">hier anmelden</a>.';
?>