<?php
/**
* WoltLab Community Framework
* language: de-informal
* encoding: UTF-8
* category: wcf.header.menu
* generated at Tue, 13 Aug 2013 11:37:06 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.header.menu.help'] = 'Hilfe';
$this->items[$this->languageID]['wcf.header.menu.memberslist'] = 'Mitglieder';
$this->items[$this->languageID]['wcf.header.menu.contact'] = 'Kontakt';
?>