<?php
/**
* WoltLab Community Framework
* language: de-informal
* encoding: UTF-8
* category: wbb.global
* generated at Tue, 13 Aug 2013 11:37:05 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.global.changeStyle'] = 'Stil ändern';
$this->items[$this->languageID]['wbb.global.copyright'] = '<a href="http://www.woltlab.com/de/">Forensoftware: <strong>Burning Board&reg;{if SHOW_VERSION_NUMBER} {@PACKAGE_VERSION}{/if}</strong>, entwickelt von <strong>WoltLab&reg; GmbH</strong></a>';
$this->dynamicItems[$this->languageID]['wbb.global.copyright'] = '<a href="http://www.woltlab.com/de/">Forensoftware: <strong>Burning Board&reg;<?php if (SHOW_VERSION_NUMBER) { ?> <?php echo PACKAGE_VERSION; ?><?php } ?></strong>, entwickelt von <strong>WoltLab&reg; GmbH</strong></a>';
$this->items[$this->languageID]['wbb.global.evaluation'] = 'Bei dieser Software handelt es sich um eine Testversion. Die Laufzeit ist auf <strong>{@EVALUATION_END|fulldate}</strong>{if EVALUATION_END > TIME_NOW} ({@TIME_NOW|datediff:EVALUATION_END}){/if} begrenzt.
		Für eine legale Nutzung über diesen Zeitpunkt hinaus musst du eine <a href="http://www.woltlab.com">kostenpflichtige Lizenz der Software erwerben</a>, oder diese abschalten und alle Bestandteile dauerhaft löschen.';
$this->dynamicItems[$this->languageID]['wbb.global.evaluation'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierFulldate\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierFulldate.class.php\');
$this->pluginObjects[\'TemplatePluginModifierFulldate\'] = new TemplatePluginModifierFulldate;
}
if (!isset($this->pluginObjects[\'TemplatePluginModifierDatediff\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierDatediff.class.php\');
$this->pluginObjects[\'TemplatePluginModifierDatediff\'] = new TemplatePluginModifierDatediff;
}
?>Bei dieser Software handelt es sich um eine Testversion. Die Laufzeit ist auf <strong><?php echo $this->pluginObjects[\'TemplatePluginModifierFulldate\']->execute(array(EVALUATION_END), $this); ?></strong><?php if (EVALUATION_END > TIME_NOW) { ?> (<?php echo $this->pluginObjects[\'TemplatePluginModifierDatediff\']->execute(array(TIME_NOW,EVALUATION_END), $this); ?>)<?php } ?> begrenzt.
		Für eine legale Nutzung über diesen Zeitpunkt hinaus musst du eine <a href="http://www.woltlab.com">kostenpflichtige Lizenz der Software erwerben</a>, oder diese abschalten und alle Bestandteile dauerhaft löschen.';
$this->items[$this->languageID]['wbb.global.offline'] = 'Das Forum befindet sich zurzeit {if OFFLINE_MESSAGE != \'\'}aus folgenden Gründen im Wartungsmodus:{else}im Wartungsmodus.{/if}';
$this->dynamicItems[$this->languageID]['wbb.global.offline'] = 'Das Forum befindet sich zurzeit <?php if (OFFLINE_MESSAGE != \'\') { ?>aus folgenden Gründen im Wartungsmodus:<?php } else { ?>im Wartungsmodus.<?php } ?>';
?>