<?php
/**
* WoltLab Community Framework
* language: de-informal
* encoding: UTF-8
* category: wcf.user.whitelist
* generated at Tue, 13 Aug 2013 11:37:05 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.whitelist.accept'] = 'Das Freundschaftsangebot dieses Benutzers annehmen';
$this->items[$this->languageID]['wcf.user.whitelist.accept.success'] = 'Das Freundschaftsangebot von &raquo;{$user}&laquo; wurde angenommen.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.accept.success'] = 'Das Freundschaftsangebot von &raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&laquo; wurde angenommen.';
$this->items[$this->languageID]['wcf.user.whitelist.accept.sure'] = 'Möchtest du die Freundschaft mit &raquo;{$member->username}&laquo; wirklich bestätigen?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.accept.sure'] = 'Möchtest du die Freundschaft mit &raquo;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&laquo; wirklich bestätigen?';
$this->items[$this->languageID]['wcf.user.whitelist.add.success'] = '{if $addedUsers|count == 1}Der Benutzer &raquo;{$addedUsers|array_shift}&laquo; wurde{else}Die Benutzer {implode from=$addedUsers item=user}&raquo;{$user}&laquo;{/implode} wurden{/if} erfolgreich deiner Freunde-Liste hinzugefügt.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.add.success'] = '<?php if (count($this->v[\'addedUsers\']) == 1) { ?>Der Benutzer &raquo;<?php echo StringUtil::encodeHTML(array_shift($this->v[\'addedUsers\'])); ?>&laquo; wurde<?php } else { ?>Die Benutzer <?php
$_length82a0a266519773c6f5565af4aeea5b7114f2b563 = count($this->v[\'addedUsers\']);
$_i82a0a266519773c6f5565af4aeea5b7114f2b563 = 0;
foreach ($this->v[\'addedUsers\'] as $this->v[\'user\']) { ?>&raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&laquo;<?php
if (++$_i82a0a266519773c6f5565af4aeea5b7114f2b563 < $_length82a0a266519773c6f5565af4aeea5b7114f2b563) { echo \', \'; }
} ?> wurden<?php } ?> erfolgreich deiner Freunde-Liste hinzugefügt.';
$this->items[$this->languageID]['wcf.user.whitelist.cancel'] = 'Das Freundschaftsangebot zurücknehmen?';
$this->items[$this->languageID]['wcf.user.whitelist.cancel.success'] = 'Das Freundschaftsangebot an &raquo;{$user}&laquo; wurde zurückgenommen.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.cancel.success'] = 'Das Freundschaftsangebot an &raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&laquo; wurde zurückgenommen.';
$this->items[$this->languageID]['wcf.user.whitelist.cancel.sure'] = 'Möchtest du das Freundschaftsangebot an den Benutzer &raquo;{$member->username}&laquo; wirklich von zurücknehmen?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.cancel.sure'] = 'Möchtest du das Freundschaftsangebot an den Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&laquo; wirklich von zurücknehmen?';
$this->items[$this->languageID]['wcf.user.whitelist.decline'] = 'Das Freundschaftsangebot dieses Benutzers ablehnen';
$this->items[$this->languageID]['wcf.user.whitelist.decline.success'] = 'Das Freundschaftsangebot von &raquo;{$user}&laquo; wurde abgelehnt.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.decline.success'] = 'Das Freundschaftsangebot von &raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&laquo; wurde abgelehnt.';
$this->items[$this->languageID]['wcf.user.whitelist.decline.sure'] = 'Möchtest du die Freundschaft mit &raquo;{$member->username}&laquo; wirklich ablehnen?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.decline.sure'] = 'Möchtest du die Freundschaft mit &raquo;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&laquo; wirklich ablehnen?';
$this->items[$this->languageID]['wcf.user.whitelist.empty'] = 'Freunde-Liste leeren';
$this->items[$this->languageID]['wcf.user.whitelist.empty.sure'] = 'Möchtest du wirklich deine komplette Freunde-Liste leeren?';
$this->items[$this->languageID]['wcf.user.whitelist.error.username.canNotAddYourself'] = 'Du kannst dich nicht deiner eigenen Freunde-Liste hinzufügen.';
$this->items[$this->languageID]['wcf.user.whitelist.error.username.userDoesNotAllowFriendshipOfferings'] = 'Der Benutzer &raquo;{$error.username}&laquo; akzeptiert keine Freundschaftsangebote.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.error.username.userDoesNotAllowFriendshipOfferings'] = 'Der Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&laquo; akzeptiert keine Freundschaftsangebote.';
$this->items[$this->languageID]['wcf.user.whitelist.invitedMembers'] = 'Ausgehende Freundschaftsangebote';
$this->items[$this->languageID]['wcf.user.whitelist.invitingMembers'] = 'Eingehende Freundschaftsangebote';
$this->items[$this->languageID]['wcf.user.whitelist.members'] = '{#$members|count} Benutzer auf deiner Freunde-Liste';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.members'] = '<?php echo StringUtil::formatNumeric(count($this->v[\'members\'])); ?> Benutzer auf deiner Freunde-Liste';
$this->items[$this->languageID]['wcf.user.whitelist.notification'] = '{if $this->user->getInvitations()|count == 1}Von folgendem Benutzer liegt ein Freundschaftsangebot vor:{else}Von folgenden Benutzern liegen Freundschaftsangebote vor:{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.notification'] = '<?php if (count($this->v[\'this\']->user->getInvitations()) == 1) { ?>Von folgendem Benutzer liegt ein Freundschaftsangebot vor:<?php } else { ?>Von folgenden Benutzern liegen Freundschaftsangebote vor:<?php } ?>';
$this->items[$this->languageID]['wcf.user.whitelist.notification.cancel'] = 'Benachrichtung ausblenden';
$this->items[$this->languageID]['wcf.user.whitelist.offer.success'] = '{if $invitedUsers|count == 1}Dem Benutzer &raquo;{$invitedUsers|array_shift}&laquo; wurde ein Freundschaftsangebot{else}Den Benutzern {implode from=$invitedUsers item=user}&raquo;{$user}&laquo;{/implode} wurden Freundschaftsangebote{/if} unterbreitet.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.offer.success'] = '<?php if (count($this->v[\'invitedUsers\']) == 1) { ?>Dem Benutzer &raquo;<?php echo StringUtil::encodeHTML(array_shift($this->v[\'invitedUsers\'])); ?>&laquo; wurde ein Freundschaftsangebot<?php } else { ?>Den Benutzern <?php
$_length1b7b6687e140ddefac61d110ac9887b0cc785c35 = count($this->v[\'invitedUsers\']);
$_i1b7b6687e140ddefac61d110ac9887b0cc785c35 = 0;
foreach ($this->v[\'invitedUsers\'] as $this->v[\'user\']) { ?>&raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&laquo;<?php
if (++$_i1b7b6687e140ddefac61d110ac9887b0cc785c35 < $_length1b7b6687e140ddefac61d110ac9887b0cc785c35) { echo \', \'; }
} ?> wurden Freundschaftsangebote<?php } ?> unterbreitet.';
$this->items[$this->languageID]['wcf.user.whitelist.remove'] = 'Diesen Benutzer von deiner Freunde-Liste entfernen';
$this->items[$this->languageID]['wcf.user.whitelist.remove.success'] = 'Der Benutzer &raquo;{$user}&laquo; wurde von deiner Freunde-Liste entfernt.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.remove.success'] = 'Der Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&laquo; wurde von deiner Freunde-Liste entfernt.';
$this->items[$this->languageID]['wcf.user.whitelist.remove.sure'] = 'Möchtest du den Benutzer &raquo;{$member->username}&laquo; wirklich von deiner Freunde-Liste entfernen?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.remove.sure'] = 'Möchtest du den Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&laquo; wirklich von deiner Freunde-Liste entfernen?';
$this->items[$this->languageID]['wcf.user.whitelist.title'] = 'Freunde-Liste';
$this->items[$this->languageID]['wcf.user.whitelist.username'] = 'Benutzername(n)';
$this->items[$this->languageID]['wcf.user.whitelist.username.description'] = 'Bitte gib den Namen des Benutzers ein, den du deiner Freunde-Liste hinzufügen möchtest. Mehrere Benutzer werden mit je einem Komma voneinander getrennt.';
$this->items[$this->languageID]['wcf.user.whitelist.declineAll'] = 'Alle ablehnen';
$this->items[$this->languageID]['wcf.user.whitelist.acceptAll'] = 'Alle annehmen';
$this->items[$this->languageID]['wcf.user.whitelist.declineAll.sure'] = 'Willst du wirklich alle Freundschaftsangebote ablehnen?';
$this->items[$this->languageID]['wcf.user.whitelist.acceptAll.sure'] = 'Willst du wirklich alle Freundschaftsangebote annehmen?';
?>