<?php
/**
* WoltLab Community Framework
* language: de-informal
* encoding: UTF-8
* category: wbb.board
* generated at Tue, 13 Aug 2013 11:37:06 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.board.button.newThread'] = 'Thema erstellen';
$this->items[$this->languageID]['wbb.board.clicks'] = 'Zugriffe';
$this->items[$this->languageID]['wbb.board.deletedThread'] = 'Das Thema &raquo;{$thread->topic}&laquo; von &raquo;{$thread->username}&laquo; ({@$thread->time|time}) wurde{if $thread->deleteReason} aus folgendem Grund{/if} vom {if $thread->userID == $thread->deletedByID}Autor selbst{else}Benutzer &raquo;{$thread->deletedBy}&laquo;{/if} gelöscht{if $thread->deleteReason}: {$thread->deleteReason}{/if} ({@$thread->deleteTime|time}).';
$this->dynamicItems[$this->languageID]['wbb.board.deletedThread'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierTime\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierTime.class.php\');
$this->pluginObjects[\'TemplatePluginModifierTime\'] = new TemplatePluginModifierTime;
}
?>Das Thema &raquo;<?php echo StringUtil::encodeHTML($this->v[\'thread\']->topic); ?>&laquo; von &raquo;<?php echo StringUtil::encodeHTML($this->v[\'thread\']->username); ?>&laquo; (<?php echo $this->pluginObjects[\'TemplatePluginModifierTime\']->execute(array($this->v[\'thread\']->time), $this); ?>) wurde<?php if ($this->v[\'thread\']->deleteReason) { ?> aus folgendem Grund<?php } ?> vom <?php if ($this->v[\'thread\']->userID == $this->v[\'thread\']->deletedByID) { ?>Autor selbst<?php } else { ?>Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v[\'thread\']->deletedBy); ?>&laquo;<?php } ?> gelöscht<?php if ($this->v[\'thread\']->deleteReason) { ?>: <?php echo StringUtil::encodeHTML($this->v[\'thread\']->deleteReason); ?><?php } ?> (<?php echo $this->pluginObjects[\'TemplatePluginModifierTime\']->execute(array($this->v[\'thread\']->deleteTime), $this); ?>).';
$this->items[$this->languageID]['wbb.board.feed'] = 'Themen dieses Forums abonnieren';
$this->items[$this->languageID]['wbb.board.feed.description'] = 'Beiträge aus dem Forum: {lang}{PAGE_TITLE}{/lang}';
$this->dynamicItems[$this->languageID]['wbb.board.feed.description'] = 'Beiträge aus dem Forum: <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langb9542ea747a802a3e56eec32cea278b92e03a894 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langb9542ea747a802a3e56eec32cea278b92e03a894, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>';
$this->items[$this->languageID]['wbb.board.feed.title'] = '{lang}{PAGE_TITLE}{/lang} Feed';
$this->dynamicItems[$this->languageID]['wbb.board.feed.title'] = '<?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang3136491471150986f7302a4bfea4c2fb05c67f3c = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang3136491471150986f7302a4bfea4c2fb05c67f3c, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> Feed';
$this->items[$this->languageID]['wbb.board.filterByDate'] = 'Im Zeitraum';
$this->items[$this->languageID]['wbb.board.filterByDate.1'] = 'der letzten 24 Stunden';
$this->items[$this->languageID]['wbb.board.filterByDate.100'] = 'der letzten 100 Tage';
$this->items[$this->languageID]['wbb.board.filterByDate.1000'] = 'von Anfang an';
$this->items[$this->languageID]['wbb.board.filterByDate.14'] = 'der letzten 14 Tage';
$this->items[$this->languageID]['wbb.board.filterByDate.3'] = 'der letzten 3 Tage';
$this->items[$this->languageID]['wbb.board.filterByDate.30'] = 'der letzten 30 Tage';
$this->items[$this->languageID]['wbb.board.filterByDate.365'] = 'der letzten 365 Tage';
$this->items[$this->languageID]['wbb.board.filterByDate.60'] = 'der letzten 60 Tage';
$this->items[$this->languageID]['wbb.board.filterByDate.7'] = 'der letzten 7 Tage';
$this->items[$this->languageID]['wbb.board.filterByLanguage'] = 'Sprache';
$this->items[$this->languageID]['wbb.board.filterByPrefix'] = 'Präfix';
$this->items[$this->languageID]['wbb.board.filterByPrefix.empty'] = 'ohne Präfix';
$this->items[$this->languageID]['wbb.board.filterByStatus'] = 'Status';
$this->items[$this->languageID]['wbb.board.filterByStatus.closed'] = 'geschlossen';
$this->items[$this->languageID]['wbb.board.filterByStatus.deleted'] = 'gelöscht';
$this->items[$this->languageID]['wbb.board.filterByStatus.done'] = 'erledigt';
$this->items[$this->languageID]['wbb.board.filterByStatus.hidden'] = 'deaktiviert';
$this->items[$this->languageID]['wbb.board.filterByStatus.open'] = 'offen';
$this->items[$this->languageID]['wbb.board.filterByStatus.read'] = 'gelesen';
$this->items[$this->languageID]['wbb.board.filterByStatus.undone'] = 'unerledigt';
$this->items[$this->languageID]['wbb.board.filterByStatus.unread'] = 'ungelesen';
$this->items[$this->languageID]['wbb.board.ignoredBoards'] = 'Foren an / aus';
$this->items[$this->languageID]['wbb.board.ignoredBoards.edit.success'] = 'Deine Änderungen wurden erfolgreich gespeichert.';
$this->items[$this->languageID]['wbb.board.markAsRead'] = 'Forum als gelesen markieren';
$this->items[$this->languageID]['wbb.board.markAsReadByDoubleClick'] = 'Forum durch Doppelklick als gelesen markieren';
$this->items[$this->languageID]['wbb.board.moderators'] = 'Moderatoren:';
$this->items[$this->languageID]['wbb.board.noThreads'] = 'Es ist kein Thema {if $board->getThreads() > 0}zu den gewählten Kriterien {/if}in diesem Forum vorhanden.';
$this->dynamicItems[$this->languageID]['wbb.board.noThreads'] = 'Es ist kein Thema <?php if ($this->v[\'board\']->getThreads() > 0) { ?>zu den gewählten Kriterien <?php } ?>in diesem Forum vorhanden.';
$this->items[$this->languageID]['wbb.board.posts.button.merge'] = 'Zusammenfügen';
$this->items[$this->languageID]['wbb.board.posts.delete.reason'] = 'Willst du diesen Beitrag wirklich löschen, optional mit folgender Begründung?';
$this->items[$this->languageID]['wbb.board.posts.delete.sure'] = 'Willst du diesen Beitrag wirklich löschen?';
$this->items[$this->languageID]['wbb.board.posts.deleteCompletely.sure'] = 'Willst du diesen Beitrag wirklich endgültig löschen?';
$this->items[$this->languageID]['wbb.board.posts.deleteMarked.reason'] = 'Willst du die markierten Beiträge wirklich löschen, optional mit folgender Begründung?';
$this->items[$this->languageID]['wbb.board.posts.deleteMarked.sure'] = 'Willst du die markierten Beiträge wirklich löschen?';
$this->items[$this->languageID]['wbb.board.posts.merge.sure'] = 'Möchtest du diesen Beitrag wirklich mit den markierten Beiträgen zusammenfügen?';
$this->items[$this->languageID]['wbb.board.posts.removeReport.sure'] = 'Willst du diese Meldung wirklich löschen?';
$this->items[$this->languageID]['wbb.board.posts.removeReports.sure'] = 'Willst du diese Meldungen wirklich löschen?';
$this->items[$this->languageID]['wbb.board.quickJump.title'] = 'Bitte wählen:';
$this->items[$this->languageID]['wbb.board.search.query'] = 'Forum durchsuchen';
$this->items[$this->languageID]['wbb.board.sortBy'] = 'Sortierung nach';
$this->items[$this->languageID]['wbb.board.sortBy.attachments'] = 'Dateianhänge';
$this->items[$this->languageID]['wbb.board.sortBy.lastPostTime'] = 'Letztem Beitrag';
$this->items[$this->languageID]['wbb.board.sortBy.polls'] = 'Umfragen';
$this->items[$this->languageID]['wbb.board.sortBy.prefix'] = 'Präfix';
$this->items[$this->languageID]['wbb.board.sortBy.rating'] = 'Bewertung';
$this->items[$this->languageID]['wbb.board.sortBy.replies'] = 'Antworten';
$this->items[$this->languageID]['wbb.board.sortBy.startTime'] = 'Erstem Beitrag';
$this->items[$this->languageID]['wbb.board.sortBy.starter'] = 'Autor';
$this->items[$this->languageID]['wbb.board.sortBy.topic'] = 'Titel';
$this->items[$this->languageID]['wbb.board.sortBy.views'] = 'Zugriffe';
$this->items[$this->languageID]['wbb.board.sorting'] = 'Sortierung &amp; Filterung';
$this->items[$this->languageID]['wbb.board.stats'] = 'Statistiken';
$this->items[$this->languageID]['wbb.board.stats.detail'] = '{#$board->getThreads()} {if $board->getThreads() == 1}Thema{else}Themen{/if} - {#$board->getPosts()} {if $board->getPosts() == 1}Beitrag{else}Beiträge{/if} ({#$board->getPostsPerDay()} {if $board->getPostsPerDay() == 1}Beitrag{else}Beiträge{/if} pro Tag)';
$this->dynamicItems[$this->languageID]['wbb.board.stats.detail'] = '<?php echo StringUtil::formatNumeric($this->v[\'board\']->getThreads()); ?> <?php if ($this->v[\'board\']->getThreads() == 1) { ?>Thema<?php } else { ?>Themen<?php } ?> - <?php echo StringUtil::formatNumeric($this->v[\'board\']->getPosts()); ?> <?php if ($this->v[\'board\']->getPosts() == 1) { ?>Beitrag<?php } else { ?>Beiträge<?php } ?> (<?php echo StringUtil::formatNumeric($this->v[\'board\']->getPostsPerDay()); ?> <?php if ($this->v[\'board\']->getPostsPerDay() == 1) { ?>Beitrag<?php } else { ?>Beiträge<?php } ?> pro Tag)';
$this->items[$this->languageID]['wbb.board.stats.posts'] = '{if $boardStats[$boardID][\'posts\'] == 1}Beitrag{else}Beiträge{/if}';
$this->dynamicItems[$this->languageID]['wbb.board.stats.posts'] = '<?php if ($this->v[\'boardStats\'][$this->v[\'boardID\']][\'posts\'] == 1) { ?>Beitrag<?php } else { ?>Beiträge<?php } ?>';
$this->items[$this->languageID]['wbb.board.stats.threads'] = '{if $boardStats[$boardID][\'threads\'] == 1}Thema{else}Themen{/if}';
$this->dynamicItems[$this->languageID]['wbb.board.stats.threads'] = '<?php if ($this->v[\'boardStats\'][$this->v[\'boardID\']][\'threads\'] == 1) { ?>Thema<?php } else { ?>Themen<?php } ?>';
$this->items[$this->languageID]['wbb.board.subscribe'] = 'Forum abonnieren';
$this->items[$this->languageID]['wbb.board.threads.attachments'] = 'Dieses Thema enthält {if $thread->attachments == 1}einen Dateianhang{else}{#$thread->attachments} Dateianhänge{/if}.';
$this->dynamicItems[$this->languageID]['wbb.board.threads.attachments'] = 'Dieses Thema enthält <?php if ($this->v[\'thread\']->attachments == 1) { ?>einen Dateianhang<?php } else { ?><?php echo StringUtil::formatNumeric($this->v[\'thread\']->attachments); ?> Dateianhänge<?php } ?>.';
$this->items[$this->languageID]['wbb.board.threads.button.close'] = 'Schließen';
$this->items[$this->languageID]['wbb.board.threads.button.copy'] = 'Hierher kopieren';
$this->items[$this->languageID]['wbb.board.threads.button.copyAndInsert'] = 'Neues Thema erstellen (Beiträge kopieren)';
$this->items[$this->languageID]['wbb.board.threads.button.copyAndMerge'] = 'Kopieren und mit diesem Thema zusammenfügen';
$this->items[$this->languageID]['wbb.board.threads.button.deleteLink'] = 'Link löschen';
$this->items[$this->languageID]['wbb.board.threads.button.disable'] = 'Deaktivieren';
$this->items[$this->languageID]['wbb.board.threads.button.done'] = 'Als erledigt markieren';
$this->items[$this->languageID]['wbb.board.threads.button.editPost'] = 'Beitrag bearbeiten';
$this->items[$this->languageID]['wbb.board.threads.button.editPrefix'] = 'Präfix bearbeiten';
$this->items[$this->languageID]['wbb.board.threads.button.editTitle'] = 'Titel bearbeiten';
$this->items[$this->languageID]['wbb.board.threads.button.enable'] = 'Aktivieren';
$this->items[$this->languageID]['wbb.board.threads.button.merge'] = 'Mit diesem Thema zusammenfügen';
$this->items[$this->languageID]['wbb.board.threads.button.move'] = 'Hierher verschieben';
$this->items[$this->languageID]['wbb.board.threads.button.moveAndInsert'] = 'Neues Thema erstellen (Beiträge verschieben)';
$this->items[$this->languageID]['wbb.board.threads.button.moveWithLink'] = 'Hierher verschieben (mit Link)';
$this->items[$this->languageID]['wbb.board.threads.button.open'] = 'Öffnen';
$this->items[$this->languageID]['wbb.board.threads.button.recover'] = 'Wiederherstellen';
$this->items[$this->languageID]['wbb.board.threads.button.removeReport'] = 'Meldung löschen';
$this->items[$this->languageID]['wbb.board.threads.button.showMarked'] = 'Anzeigen';
$this->items[$this->languageID]['wbb.board.threads.button.stick'] = 'Oben anheften';
$this->items[$this->languageID]['wbb.board.threads.button.undone'] = 'Als unerledigt markieren';
$this->items[$this->languageID]['wbb.board.threads.button.unstick'] = 'Lösen';
$this->items[$this->languageID]['wbb.board.threads.close'] = '&raquo;{@$title}&laquo; schließen';
$this->dynamicItems[$this->languageID]['wbb.board.threads.close'] = '&raquo;<?php echo $this->v[\'title\']; ?>&laquo; schließen';
$this->items[$this->languageID]['wbb.board.threads.delete.reason'] = 'Willst du dieses Thema wirklich löschen, optional mit folgender Begründung?';
$this->items[$this->languageID]['wbb.board.threads.delete.sure'] = 'Willst du dieses Thema wirklich löschen?';
$this->items[$this->languageID]['wbb.board.threads.deleteCompletely.sure'] = 'Willst du dieses Thema wirklich endgültig löschen?';
$this->items[$this->languageID]['wbb.board.threads.deleteLink.sure'] = 'Willst du den Link zu diesem Thema wirklich löschen?';
$this->items[$this->languageID]['wbb.board.threads.deleteMarked.reason'] = 'Willst du die markierten Themen wirklich löschen, optional mit folgender Begründung?';
$this->items[$this->languageID]['wbb.board.threads.deleteMarked.sure'] = 'Willst du die markierten Themen wirklich löschen?';
$this->items[$this->languageID]['wbb.board.threads.deleteNote'] = 'Gelöscht {if $thread->userID == $thread->deletedByID}vom Autor selbst{else}von &raquo;{$thread->deletedBy}&laquo;{/if} ({@$thread->deleteTime|time}){if $thread->deleteReason}: {$thread->deleteReason}{/if}
		{if THREAD_EMPTY_RECYCLE_BIN_CYCLE > 0}<br />Zeit bis zur endgültigen Löschung: {@$thread->deleteTime+THREAD_EMPTY_RECYCLE_BIN_CYCLE*86400|datediff}{/if}';
$this->dynamicItems[$this->languageID]['wbb.board.threads.deleteNote'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierTime\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierTime.class.php\');
$this->pluginObjects[\'TemplatePluginModifierTime\'] = new TemplatePluginModifierTime;
}
if (!isset($this->pluginObjects[\'TemplatePluginModifierDatediff\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierDatediff.class.php\');
$this->pluginObjects[\'TemplatePluginModifierDatediff\'] = new TemplatePluginModifierDatediff;
}
?>Gelöscht <?php if ($this->v[\'thread\']->userID == $this->v[\'thread\']->deletedByID) { ?>vom Autor selbst<?php } else { ?>von &raquo;<?php echo StringUtil::encodeHTML($this->v[\'thread\']->deletedBy); ?>&laquo;<?php } ?> (<?php echo $this->pluginObjects[\'TemplatePluginModifierTime\']->execute(array($this->v[\'thread\']->deleteTime), $this); ?>)<?php if ($this->v[\'thread\']->deleteReason) { ?>: <?php echo StringUtil::encodeHTML($this->v[\'thread\']->deleteReason); ?><?php } ?>
		<?php if (THREAD_EMPTY_RECYCLE_BIN_CYCLE > 0) { ?><br />Zeit bis zur endgültigen Löschung: <?php echo $this->pluginObjects[\'TemplatePluginModifierDatediff\']->execute(array($this->v[\'thread\']->deleteTime+THREAD_EMPTY_RECYCLE_BIN_CYCLE*86400), $this); ?><?php } ?>';
$this->items[$this->languageID]['wbb.board.threads.done'] = 'Thema ist als erledigt markiert';
$this->items[$this->languageID]['wbb.board.threads.lastPost'] = 'Letzte Antwort';
$this->items[$this->languageID]['wbb.board.threads.markedPosts'] = 'this.count == 1 ? "Ein Beitrag markiert" : this.count+" Beiträge markiert"';
$this->items[$this->languageID]['wbb.board.threads.markedThreads'] = 'this.count == 1 ? "Ein Thema markiert" : this.count+" Themen markiert"';
$this->items[$this->languageID]['wbb.board.threads.noReply'] = 'keine Antwort';
$this->items[$this->languageID]['wbb.board.threads.normal'] = 'Themen';
$this->items[$this->languageID]['wbb.board.threads.open'] = '&raquo;{@$title}&laquo; öffnen';
$this->dynamicItems[$this->languageID]['wbb.board.threads.open'] = '&raquo;<?php echo $this->v[\'title\']; ?>&laquo; öffnen';
$this->items[$this->languageID]['wbb.board.threads.ownPosts'] = 'Dieses Thema enthält Beiträge von dir.';
$this->items[$this->languageID]['wbb.board.threads.polls'] = 'Dieses Thema enthält {if $thread->polls == 1}eine Umfrage{else}{#$thread->polls} Umfragen{/if}.';
$this->dynamicItems[$this->languageID]['wbb.board.threads.polls'] = 'Dieses Thema enthält <?php if ($this->v[\'thread\']->polls == 1) { ?>eine Umfrage<?php } else { ?><?php echo StringUtil::formatNumeric($this->v[\'thread\']->polls); ?> Umfragen<?php } ?>.';
$this->items[$this->languageID]['wbb.board.threads.postBy'] = 'Von';
$this->items[$this->languageID]['wbb.board.threads.rating'] = 'Bewertung';
$this->items[$this->languageID]['wbb.board.threads.replies'] = 'Antworten';
$this->items[$this->languageID]['wbb.board.threads.subscribed'] = 'Du hast dieses Thema abonniert.';
$this->items[$this->languageID]['wbb.board.threads.top'] = 'Ankündigungen und wichtige Themen';
$this->items[$this->languageID]['wbb.board.threads.topic'] = 'Thema';
$this->items[$this->languageID]['wbb.board.threads.undone'] = 'Thema ist als unerledigt markiert';
$this->items[$this->languageID]['wbb.board.threads.views'] = 'Zugriffe';
$this->items[$this->languageID]['wbb.board.unsubscribe'] = 'Forum abbestellen';
$this->items[$this->languageID]['wbb.board.usersOnline'] = 'Zurzeit {if $usersOnlineTotal == 1}ist{else}sind{/if} neben dir {#$usersOnlineTotal} Benutzer in diesem Forum unterwegs:';
$this->dynamicItems[$this->languageID]['wbb.board.usersOnline'] = 'Zurzeit <?php if ($this->v[\'usersOnlineTotal\'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> neben dir <?php echo StringUtil::formatNumeric($this->v[\'usersOnlineTotal\']); ?> Benutzer in diesem Forum unterwegs:';
$this->items[$this->languageID]['wbb.board.vote.description'] = '{$votes} Bewertung(en) - Durchschnitt: {$vote}';
$this->dynamicItems[$this->languageID]['wbb.board.vote.description'] = '<?php echo StringUtil::encodeHTML($this->v[\'votes\']); ?> Bewertung(en) - Durchschnitt: <?php echo StringUtil::encodeHTML($this->v[\'vote\']); ?>';
?>