<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.poll
* generated at Tue, 13 Aug 2013 11:30:43 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.poll'] = 'Umfrage';
$this->items[$this->languageID]['wcf.poll.button.change'] = 'Stimme ändern';
$this->items[$this->languageID]['wcf.poll.button.detail'] = 'Details';
$this->items[$this->languageID]['wcf.poll.button.result'] = 'Ergebnis';
$this->items[$this->languageID]['wcf.poll.button.vote'] = 'Abstimmen';
$this->items[$this->languageID]['wcf.poll.choiceCount'] = 'Anzahl erlaubter Antworten';
$this->items[$this->languageID]['wcf.poll.endTime'] = 'Umfrage endet am (optional)';
$this->items[$this->languageID]['wcf.poll.endTime.error.invalid'] = 'Bitte geben Sie ein gültiges Datum ein!';
$this->items[$this->languageID]['wcf.poll.error.choiceCount.notValid'] = 'Die Anzahl der erlaubten Antworten ist unzulässig.';
$this->items[$this->languageID]['wcf.poll.error.choiceCount.tooMuch'] = 'Die Anzahl der erlaubten Antworten ist größer als die Anzahl der zur Verfügung stehenden Antworten.';
$this->items[$this->languageID]['wcf.poll.error.notEnoughOptions'] = 'Sie müssen mindestens zwei Antworten eintragen.';
$this->items[$this->languageID]['wcf.poll.error.tooMuchOptions'] = 'Sie haben zu viele Antworten eingetragen. Maximal sind {POLL_MAX_OPTIONS} Antworten erlaubt.';
$this->dynamicItems[$this->languageID]['wcf.poll.error.tooMuchOptions'] = 'Sie haben zu viele Antworten eingetragen. Maximal sind <?php echo StringUtil::encodeHTML(POLL_MAX_OPTIONS); ?> Antworten erlaubt.';
$this->items[$this->languageID]['wcf.poll.isPublic'] = 'Öffentliche Umfrage (Teilnehmer und deren Stimmen für alle sichtbar)';
$this->items[$this->languageID]['wcf.poll.notVoted'] = 'Sie haben noch nicht abgestimmt.';
$this->items[$this->languageID]['wcf.poll.option.votes'] = '
		{if $pollOptionData.pollOption->votes == 0}
			Noch keine Stimme.
		{else}
			Es {if $pollOptionData.users|count+$pollOptionData.guests > 1}haben{else}hat{/if}
				{if $pollOptionData.users|count > 0}{#$pollOptionData.users|count} Benutzer {if $pollOptionData.guests > 0} und {/if}{/if}
				{if $pollOptionData.guests > 0}{#$pollOptionData.guests} {if $pollOptionData.guests != 1}Gäste{else}Gast{/if} {/if}
			für diese Option gestimmt.
		{/if}';
$this->dynamicItems[$this->languageID]['wcf.poll.option.votes'] = '
		<?php if ($this->v[\'pollOptionData\'][\'pollOption\']->votes == 0) { ?>
			Noch keine Stimme.
		<?php } else { ?>
			Es <?php if (count($this->v[\'pollOptionData\'][\'users\'],+$this->v[\'pollOptionData\'][\'guests\']) > 1) { ?>haben<?php } else { ?>hat<?php } ?>
				<?php if (count($this->v[\'pollOptionData\'][\'users\']) > 0) { ?><?php echo StringUtil::formatNumeric(count($this->v[\'pollOptionData\'][\'users\'])); ?> Benutzer <?php if ($this->v[\'pollOptionData\'][\'guests\'] > 0) { ?> und <?php } ?><?php } ?>
				<?php if ($this->v[\'pollOptionData\'][\'guests\'] > 0) { ?><?php echo StringUtil::formatNumeric($this->v[\'pollOptionData\'][\'guests\']); ?> <?php if ($this->v[\'pollOptionData\'][\'guests\'] != 1) { ?>Gäste<?php } else { ?>Gast<?php } ?> <?php } ?>
			für diese Option gestimmt.
		<?php } ?>';
$this->items[$this->languageID]['wcf.poll.options'] = 'Antworten';
$this->items[$this->languageID]['wcf.poll.options.description'] = 'Eine Antwort pro Zeile - maximal {POLL_MAX_OPTIONS} Antworten';
$this->dynamicItems[$this->languageID]['wcf.poll.options.description'] = 'Eine Antwort pro Zeile - maximal <?php echo StringUtil::encodeHTML(POLL_MAX_OPTIONS); ?> Antworten';
$this->items[$this->languageID]['wcf.poll.question'] = 'Frage';
$this->items[$this->languageID]['wcf.poll.settings'] = 'Optionen';
$this->items[$this->languageID]['wcf.poll.sortByResult'] = 'Ergebnis nach Stimmen sortieren';
$this->items[$this->languageID]['wcf.poll.vote.changeVote'] = 'Sie haben bereits an dieser Umfrage teilgenommen, können Ihre Stimme aber noch einmal ändern.';
$this->items[$this->languageID]['wcf.poll.vote.choiceCount'] = 'Sie können maximal {#$poll->choiceCount} Optionen auswählen';
$this->dynamicItems[$this->languageID]['wcf.poll.vote.choiceCount'] = 'Sie können maximal <?php echo StringUtil::formatNumeric($this->v[\'poll\']->choiceCount); ?> Optionen auswählen';
$this->items[$this->languageID]['wcf.poll.vote.endTime'] = 'Die Umfrage endet: {@$poll->endTime|time}';
$this->dynamicItems[$this->languageID]['wcf.poll.vote.endTime'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierTime\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierTime.class.php\');
$this->pluginObjects[\'TemplatePluginModifierTime\'] = new TemplatePluginModifierTime;
}
?>Die Umfrage endet: <?php echo $this->pluginObjects[\'TemplatePluginModifierTime\']->execute(array($this->v[\'poll\']->endTime), $this); ?>';
$this->items[$this->languageID]['wcf.poll.vote.error.notValid'] = 'Sie haben keine gültige Antwort ausgewählt. Bitte wählen Sie mindestens eine Antwort aus!';
$this->items[$this->languageID]['wcf.poll.vote.error.tooMuch'] = 'Sie haben zu viele Antworten ausgewählt. Sie dürfen nur maximal {#$poll->choiceCount} Optionen auswählen.';
$this->dynamicItems[$this->languageID]['wcf.poll.vote.error.tooMuch'] = 'Sie haben zu viele Antworten ausgewählt. Sie dürfen nur maximal <?php echo StringUtil::formatNumeric($this->v[\'poll\']->choiceCount); ?> Optionen auswählen.';
$this->items[$this->languageID]['wcf.poll.voted'] = 'Sie haben bereits abgestimmt.';
$this->items[$this->languageID]['wcf.poll.voters'] = 'Umfrageteilnehmer';
$this->items[$this->languageID]['wcf.poll.votes'] = '{if $poll->votes == 0}Noch keine Stimme{else}Insgesamt {#$poll->votes} Stimme{if $poll->votes > 1}n{/if}{/if}';
$this->dynamicItems[$this->languageID]['wcf.poll.votes'] = '<?php if ($this->v[\'poll\']->votes == 0) { ?>Noch keine Stimme<?php } else { ?>Insgesamt <?php echo StringUtil::formatNumeric($this->v[\'poll\']->votes); ?> Stimme<?php if ($this->v[\'poll\']->votes > 1) { ?>n<?php } ?><?php } ?>';
$this->items[$this->languageID]['wcf.poll.votesNotChangeable'] = 'Einmal abgegebene Bewertungen dürfen nicht mehr verändert werden.';
?>