<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.avatar
* generated at Tue, 13 Aug 2013 10:18:13 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.avatar'] = 'Avatar';
$this->items[$this->languageID]['wcf.user.avatar.availableAvatars'] = 'Sie können aus {#$items} vorgegebenen Avatar{if $items != 1}en{/if} wählen';
$this->dynamicItems[$this->languageID]['wcf.user.avatar.availableAvatars'] = 'Sie können aus <?php echo StringUtil::formatNumeric($this->v[\'items\']); ?> vorgegebenen Avatar<?php if ($this->v[\'items\'] != 1) { ?>en<?php } ?> wählen';
$this->items[$this->languageID]['wcf.user.avatar.avatarURL'] = 'Avatar herunterladen';
$this->items[$this->languageID]['wcf.user.avatar.avatarUpload'] = 'Avatar hochladen';
$this->items[$this->languageID]['wcf.user.avatar.avatarUpload.description'] = 'Eigene Avatare dürfen die Dateiendungen gif, jpg, jpeg und png und maximal eine Größe von {#$this->user->getPermission(\'user.profile.avatar.maxWidth\')}*{#$this->user->getPermission(\'user.profile.avatar.maxHeight\')} Pixel und {@$this->user->getPermission(\'user.profile.avatar.maxSize\')|filesize} besitzen. Größere Avatare werden automatisch auf die Maximalgröße verkleinert.';
$this->dynamicItems[$this->languageID]['wcf.user.avatar.avatarUpload.description'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierFilesize\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierFilesize.class.php\');
$this->pluginObjects[\'TemplatePluginModifierFilesize\'] = new TemplatePluginModifierFilesize;
}
?>Eigene Avatare dürfen die Dateiendungen gif, jpg, jpeg und png und maximal eine Größe von <?php echo StringUtil::formatNumeric($this->v[\'this\']->user->getPermission(\'user.profile.avatar.maxWidth\')); ?>*<?php echo StringUtil::formatNumeric($this->v[\'this\']->user->getPermission(\'user.profile.avatar.maxHeight\')); ?> Pixel und <?php echo $this->pluginObjects[\'TemplatePluginModifierFilesize\']->execute(array($this->v[\'this\']->user->getPermission(\'user.profile.avatar.maxSize\')), $this); ?> besitzen. Größere Avatare werden automatisch auf die Maximalgröße verkleinert.';
$this->items[$this->languageID]['wcf.user.avatar.category.default'] = 'Standard-Avatare';
$this->items[$this->languageID]['wcf.user.avatar.currentAvatar'] = 'Aktueller Avatar';
$this->items[$this->languageID]['wcf.user.avatar.defaultAvatars'] = 'Vorgegebene Avatare';
$this->items[$this->languageID]['wcf.user.avatar.disable'] = 'Avatar löschen';
$this->items[$this->languageID]['wcf.user.avatar.disable.sure'] = 'Möchten Sie Ihren aktuellen Avatar wirklich löschen?';
$this->items[$this->languageID]['wcf.user.avatar.error.availableAvatars.invalid'] = 'Sie haben ein ungültigen Avatar ausgewählt.';
$this->items[$this->languageID]['wcf.user.avatar.error.avatarURL.downloadFailed'] = 'Das Herunterladen der Datei ist fehlgeschlagen. Die angegebene Adresse (URL) ist vermutlich nicht korrekt.';
$this->items[$this->languageID]['wcf.user.avatar.error.avatarUpload.uploadFailed'] = 'Das Hochladen der Datei ist fehlgeschlagen.';
$this->items[$this->languageID]['wcf.user.avatar.error.badAvatar'] = 'Sie haben ein beschädigtes Bild ausgewählt.';
$this->items[$this->languageID]['wcf.user.avatar.error.copyFailed'] = 'Der Avatar konnte nicht zum endgültigen Speicherort kopiert werden. Es liegt vermutlich ein Systemfehler vor.';
$this->items[$this->languageID]['wcf.user.avatar.error.disabled'] = 'Der Administrator hat{if $avatarID != 0} Ihren derzeitigen Avatar gesperrt und{/if} Ihnen die weitere Nutzungberechtigung der Avatar-Funktion {if !$this->user->disableAvatarReason}entzogen.{else} aus folgenden Gründen entzogen: {$this->user->disableAvatarReason}{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.avatar.error.disabled'] = 'Der Administrator hat<?php if ($this->v[\'avatarID\'] != 0) { ?> Ihren derzeitigen Avatar gesperrt und<?php } ?> Ihnen die weitere Nutzungberechtigung der Avatar-Funktion <?php if ( ! $this->v[\'this\']->user->disableAvatarReason) { ?>entzogen.<?php } else { ?> aus folgenden Gründen entzogen: <?php echo StringUtil::encodeHTML($this->v[\'this\']->user->disableAvatarReason); ?><?php } ?>';
$this->items[$this->languageID]['wcf.user.avatar.error.notAllowedExtension'] = 'Das ausgewählte Bild besitzt eine ungültige Dateiendung. Die erlaubten Dateiendungen sind gif, jpg, jpeg und png.';
$this->items[$this->languageID]['wcf.user.avatar.error.tooLarge'] = 'Das ausgewählte Bild überschreitet die erlaubte Maximalgröße. Die maximale Größe liegt bei {#$this->user->getPermission(\'user.profile.avatar.maxWidth\')}*{#$this->user->getPermission(\'user.profile.avatar.maxHeight\')} Pixeln und {@$this->user->getPermission(\'user.profile.avatar.maxSize\')|filesize}.';
$this->dynamicItems[$this->languageID]['wcf.user.avatar.error.tooLarge'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierFilesize\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierFilesize.class.php\');
$this->pluginObjects[\'TemplatePluginModifierFilesize\'] = new TemplatePluginModifierFilesize;
}
?>Das ausgewählte Bild überschreitet die erlaubte Maximalgröße. Die maximale Größe liegt bei <?php echo StringUtil::formatNumeric($this->v[\'this\']->user->getPermission(\'user.profile.avatar.maxWidth\')); ?>*<?php echo StringUtil::formatNumeric($this->v[\'this\']->user->getPermission(\'user.profile.avatar.maxHeight\')); ?> Pixeln und <?php echo $this->pluginObjects[\'TemplatePluginModifierFilesize\']->execute(array($this->v[\'this\']->user->getPermission(\'user.profile.avatar.maxSize\')), $this); ?>.';
$this->items[$this->languageID]['wcf.user.avatar.gravatar'] = 'Gravatar';
$this->items[$this->languageID]['wcf.user.avatar.gravatar.description'] = 'Bei einem Gravatar handelt es sich um einen global verfügbaren Avatar (Global Recognized Avatar), welcher mit Ihrer E-Mail-Adresse verknüpft ist. Auf der folgenden Website können Sie einen Gravatar anlegen: <a href="http://www.gravatar.com" class="externalURL">www.gravatar.com</a>';
$this->items[$this->languageID]['wcf.user.avatar.ownAvatar'] = 'Eigener Avatar';
$this->items[$this->languageID]['wcf.user.avatar.success'] = 'Ihr Auswahl wurde erfolgreich gespeichert.';
?>