<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.contact
* generated at Tue, 13 Aug 2013 10:21:11 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.contact.daten'] = 'Benutzerdaten';
$this->items[$this->languageID]['wcf.contact.username'] = 'Name';
$this->items[$this->languageID]['wcf.contact.title'] = 'Kontaktformular';
$this->items[$this->languageID]['wcf.contact.description'] = '';
$this->items[$this->languageID]['wcf.contact.mail.subject'] = 'Nachricht von "{$username}": {$subject}';
$this->dynamicItems[$this->languageID]['wcf.contact.mail.subject'] = 'Nachricht von "<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>": <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>';
$this->items[$this->languageID]['wcf.contact.mail.message'] = 'Hallo {$recipient},

auf der Website: {PAGE_TITLE} ({PAGE_URL}) wurde Ihnen folgende Nachricht gesandt:

Name: {$name}
E-Mail: {$email}

Betreff: {$subject}
Nachricht:
{$message}';
$this->dynamicItems[$this->languageID]['wcf.contact.mail.message'] = 'Hallo <?php echo StringUtil::encodeHTML($this->v[\'recipient\']); ?>,

auf der Website: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> (<?php echo StringUtil::encodeHTML(PAGE_URL); ?>) wurde Ihnen folgende Nachricht gesandt:

Name: <?php echo StringUtil::encodeHTML($this->v[\'name\']); ?>
E-Mail: <?php echo StringUtil::encodeHTML($this->v[\'email\']); ?>

Betreff: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>
Nachricht:
<?php echo StringUtil::encodeHTML($this->v[\'message\']); ?>';
$this->items[$this->languageID]['wcf.contact.mailvers'] = 'Ihre Nachricht an unser &raquo;Team - {$username}&laquo; wurde erfolgreich versandt.';
$this->dynamicItems[$this->languageID]['wcf.contact.mailvers'] = 'Ihre Nachricht an unser &raquo;Team - <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&laquo; wurde erfolgreich versandt.';
?>