<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.acp
* generated at Tue, 13 Aug 2013 10:14:53 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.acp'] = 'Administrationsoberfläche';
$this->items[$this->languageID]['wcf.acp.help'] = 'Hilfe';
$this->items[$this->languageID]['wcf.acp.help.complete'] = 'Vollständige Hilfe';
$this->items[$this->languageID]['wcf.acp.help.disable'] = 'Hilfe deaktivieren';
$this->items[$this->languageID]['wcf.acp.help.interactive'] = 'Interaktive Hilfe';
$this->items[$this->languageID]['wcf.acp.packageQuickAccess'] = 'Paket wechseln';
$this->items[$this->languageID]['wcf.acp.search.extended'] = 'Erweiterte Suche ...';
$this->items[$this->languageID]['wcf.acp.sitemap'] = 'Sitemap';
?>