<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.page
* generated at Tue, 13 Aug 2013 10:52:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.page.pageNo'] = 'Seite {#$pageNo}';
$this->dynamicItems[$this->languageID]['wcf.page.pageNo'] = 'Seite <?php echo StringUtil::formatNumeric($this->v[\'pageNo\']); ?>';
?>