<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.user.infraction
* generated at Tue, 13 Aug 2013 11:31:08 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.infraction.button.warn'] = 'Verwarnen';
$this->items[$this->languageID]['wcf.user.infraction.error.alreadyReported'] = 'Der Benutzer wurde für diesen Eintrag bereits verwarnt.';
$this->items[$this->languageID]['wcf.user.infraction.error.canNotBeWarned'] = 'Der Benutzer &raquo;{$user->username}&laquo; kann nicht verwarnt werden.';
$this->dynamicItems[$this->languageID]['wcf.user.infraction.error.canNotBeWarned'] = 'Der Benutzer &raquo;<?php echo StringUtil::encodeHTML($this->v[\'user\']->username); ?>&laquo; kann nicht verwarnt werden.';
$this->items[$this->languageID]['wcf.user.infraction.userSuspension.suspensions'] = 'Sanktionen';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.add'] = 'Benutzer verwarnen';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.add.success'] = 'Der Benutzer wurde erfolgreich verwarnt.';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.jugde'] = 'Verwarnung durch';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.message.subject'] = 'Sie wurden verwarnt';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.message.text'] = '{@$title}{if $reason}: {@$reason}{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.infraction.userWarning.message.text'] = '<?php echo $this->v[\'title\']; ?><?php if ($this->v[\'reason\']) { ?>: <?php echo $this->v[\'reason\']; ?><?php } ?>';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.object'] = 'Ursprung';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.reason'] = 'Begründung';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.reason.description'] = 'Geben Sie hier den Grund für die Verwarnung an. Die Begründung wird dem verwarnten Benutzer angezeigt.';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.time'] = 'Datum';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.userWarningID'] = 'ID';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.warning'] = 'Verwarnung';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.warning.individual'] = 'Eigene';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.warning.predefined'] = 'Vordefinierte Verwarnungen';
$this->items[$this->languageID]['wcf.user.infraction.userWarning.warnings'] = 'Verwarnungen';
$this->items[$this->languageID]['wcf.user.infraction.warning.expires'] = 'Ablauf';
$this->items[$this->languageID]['wcf.user.infraction.warning.expires.description'] = 'Geben Sie hier an, nach welchem Zeitraum diese Verwarnung ablaufen soll. Nach dem Ablaufen werden die Verwarnungspunkte vom Konto des verwarnten Benutzers abgezogen. Keine Angaben führen hier dazu, dass die Verwarnung niemals abläuft und entsprechend unbegrenzt gültig bleibt.';
$this->items[$this->languageID]['wcf.user.infraction.warning.expires.never'] = 'Nie';
$this->items[$this->languageID]['wcf.user.infraction.warning.general'] = 'Allgemein';
$this->items[$this->languageID]['wcf.user.infraction.warning.points'] = 'Punkte';
$this->items[$this->languageID]['wcf.user.infraction.warning.points.description'] = 'Geben Sie hier an, wieviele Verwarnungspunkte dem Konto eines Benutzers gutgeschrieben werden sollen, wenn diese Verwarnung gegen ihn ausgesprochen wird.';
$this->items[$this->languageID]['wcf.user.infraction.warning.title'] = 'Name';
$this->items[$this->languageID]['wcf.user.infraction.warning.title.description'] = 'Geben Sie eine Bezeichnung für die Verwarnung an!';
$this->items[$this->languageID]['wcf.user.infraction.warning.warningID'] = 'ID';
$this->items[$this->languageID]['wcf.user.infraction.warning.warnings'] = 'Anwendungen';
?>