<?php
/**
* WoltLab Community Framework
* language: de
* encoding: UTF-8
* category: wcf.acp.menu
* generated at Tue, 13 Aug 2013 10:14:53 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.acp.menu.link.autoupdate'] = 'Automatisches Update';
$this->items[$this->languageID]['wcf.acp.menu.link.content'] = 'Inhalte';
$this->items[$this->languageID]['wcf.acp.menu.link.display'] = 'Darstellung';
$this->items[$this->languageID]['wcf.acp.menu.link.group'] = 'Benutzergruppen';
$this->items[$this->languageID]['wcf.acp.menu.link.group.add'] = 'Benutzergruppe hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.group.mail'] = 'E-Mail an Gruppenmitglieder';
$this->items[$this->languageID]['wcf.acp.menu.link.group.view'] = 'Benutzergruppen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.log'] = 'Protokoll';
$this->items[$this->languageID]['wcf.acp.menu.link.log.cache'] = 'Cache';
$this->items[$this->languageID]['wcf.acp.menu.link.log.session'] = 'Sitzungen';
$this->items[$this->languageID]['wcf.acp.menu.link.maintenance'] = 'Wartung';
$this->items[$this->languageID]['wcf.acp.menu.link.option'] = 'Optionen';
$this->items[$this->languageID]['wcf.acp.menu.link.option.importAndExport'] = 'Sichern &amp; Wiederherstellen';
$this->items[$this->languageID]['wcf.acp.menu.link.package'] = 'Paketverwaltung';
$this->items[$this->languageID]['wcf.acp.menu.link.package.database'] = 'Pakete suchen';
$this->items[$this->languageID]['wcf.acp.menu.link.package.install'] = 'Paket installieren';
$this->items[$this->languageID]['wcf.acp.menu.link.package.server.add'] = 'Server hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.package.server.view'] = 'Server auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.package.view'] = 'Pakete auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.system'] = 'System';
$this->items[$this->languageID]['wcf.acp.menu.link.user'] = 'Benutzer';
$this->items[$this->languageID]['wcf.acp.menu.link.user.add'] = 'Benutzer hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.list'] = 'Benutzer auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.mail'] = 'E-Mail an alle Benutzer';
$this->items[$this->languageID]['wcf.acp.menu.link.user.management'] = 'Benutzer';
$this->items[$this->languageID]['wcf.acp.menu.link.user.massProcessing'] = 'Massenverarbeitung von Benutzern';
$this->items[$this->languageID]['wcf.acp.menu.link.user.search'] = 'Benutzer suchen';
$this->items[$this->languageID]['wcf.acp.menu.link.cronjobs.add'] = 'Zeitgesteuerte Aufgabe hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.cronjobs.showLog'] = 'Zeitgesteuerte Aufgaben';
$this->items[$this->languageID]['wcf.acp.menu.link.cronjobs.view'] = 'Zeitgesteuerte Aufgaben auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.option'] = 'Benutzerprofilfelder';
$this->items[$this->languageID]['wcf.acp.menu.link.user.option.add'] = 'Benutzerprofilfeld hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.option.category.add'] = 'Benutzerprofilfeld-Kategorie hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.option.category.view'] = 'Benutzerprofilfeld-Kategorien auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.option.setDefaults'] = 'Benutzerprofil-Einstellungen verwalten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.option.view'] = 'Benutzerprofilfelder auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.language'] = 'Sprachen';
$this->items[$this->languageID]['wcf.acp.menu.link.language.add'] = 'Sprache hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.language.multilingualism'] = 'Mehrsprachigkeit verwalten';
$this->items[$this->languageID]['wcf.acp.menu.link.language.search'] = 'Sprachen durchsuchen';
$this->items[$this->languageID]['wcf.acp.menu.link.language.sync'] = 'Sprachen abgleichen';
$this->items[$this->languageID]['wcf.acp.menu.link.language.variable.add'] = 'Sprachvariable hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.language.view'] = 'Sprachen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.maintenance.db.export'] = 'Datenbank sichern';
$this->items[$this->languageID]['wcf.acp.menu.link.maintenance.db.import'] = 'Datenbank einspielen';
$this->items[$this->languageID]['wcf.acp.menu.link.maintenance.db.manage'] = 'Datenbank verwalten';
$this->items[$this->languageID]['wcf.acp.menu.link.template'] = 'Templates';
$this->items[$this->languageID]['wcf.acp.menu.link.template.add'] = 'Template hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.template.search'] = 'Templates suchen';
$this->items[$this->languageID]['wcf.acp.menu.link.template.view'] = 'Templates auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.templatepack.add'] = 'Templategruppe hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.templatepack.view'] = 'Templategruppen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.log.stats'] = 'Statistiken';
$this->items[$this->languageID]['wcf.acp.menu.link.pageMenuItem'] = 'Hauptmenü';
$this->items[$this->languageID]['wcf.acp.menu.link.pageMenuItem.add'] = 'Menüpunkt hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.pageMenuItem.edit'] = 'Menüpunkt bearbeiten';
$this->items[$this->languageID]['wcf.acp.menu.link.pageMenuItem.view'] = 'Menüpunkte auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.style'] = 'Stile';
$this->items[$this->languageID]['wcf.acp.menu.link.style.add'] = 'Stil hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.style.import'] = 'Stil importieren';
$this->items[$this->languageID]['wcf.acp.menu.link.style.toPackage'] = 'Anwendungs-Zuordnung';
$this->items[$this->languageID]['wcf.acp.menu.link.style.view'] = 'Stile auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.style.writeFiles'] = 'Stile aktualisieren';
$this->items[$this->languageID]['wcf.acp.menu.link.helpItem'] = 'Hilfethemen';
$this->items[$this->languageID]['wcf.acp.menu.link.helpItem.add'] = 'Hilfethema hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.helpItem.edit'] = 'Hilfethema bearbeiten';
$this->items[$this->languageID]['wcf.acp.menu.link.helpItem.view'] = 'Hilfethemen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.log.failedLogin'] = 'Fehlgeschlagene Anmeldungen';
$this->items[$this->languageID]['wcf.acp.menu.link.smiley'] = 'Smileys';
$this->items[$this->languageID]['wcf.acp.menu.link.smiley.add'] = 'Smiley hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.smiley.category.add'] = 'Smiley-Kategorie hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.smiley.category.view'] = 'Smiley-Kategorien auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.smiley.view'] = 'Smileys auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.bbcode'] = 'BBCodes';
$this->items[$this->languageID]['wcf.acp.menu.link.bbcode.add'] = 'BBCode hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.bbcode.view'] = 'BBCodes auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.attachment'] = 'Dateianhänge';
$this->items[$this->languageID]['wcf.acp.menu.link.attachment.massProcessing'] = 'Massenverarbeitung von Dateianhängen';
$this->items[$this->languageID]['wcf.acp.menu.link.attachment.view'] = 'Dateianhänge verwalten';
$this->items[$this->languageID]['wcf.acp.menu.link.avatar'] = 'Avatare';
$this->items[$this->languageID]['wcf.acp.menu.link.avatar.add'] = 'Avatar hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.avatar.category.add'] = 'Avatar-Kategorie hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.avatar.category.view'] = 'Avatar-Kategorien auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.avatar.view'] = 'Avatare auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.rank'] = 'Benutzerränge';
$this->items[$this->languageID]['wcf.acp.menu.link.user.rank.add'] = 'Benutzerrang hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.rank.view'] = 'Benutzerränge auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.group.pm'] = 'Private Nachricht an Gruppenmitglieder';
$this->items[$this->languageID]['wcf.acp.menu.link.user.pm'] = 'Private Nachricht an alle Benutzer';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction'] = 'Verwarnungen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction.suspension.add'] = 'Vordefinierte Sanktion hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction.suspension.view'] = 'Vordefinierte Sanktionen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction.userSuspension.view'] = 'Aktive Sanktionen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction.userWarning.view'] = 'Aktive Verwarnungen auflisten';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction.warning.add'] = 'Vordefinierte Verwarnung hinzufügen';
$this->items[$this->languageID]['wcf.acp.menu.link.user.infraction.warning.view'] = 'Vordefinierte Verwarnungen auflisten';
?>