<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.pm
* generated at Tue, 13 Aug 2013 11:36:41 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.pm.addFolder'] = 'Add Folder';
$this->items[$this->languageID]['wcf.pm.addFolder.color'] = 'Color:';
$this->items[$this->languageID]['wcf.pm.addFolder.color.blue'] = 'Blue';
$this->items[$this->languageID]['wcf.pm.addFolder.color.green'] = 'Green';
$this->items[$this->languageID]['wcf.pm.addFolder.color.red'] = 'Red';
$this->items[$this->languageID]['wcf.pm.addFolder.color.white'] = 'White';
$this->items[$this->languageID]['wcf.pm.addFolder.color.yellow'] = 'Yellow';
$this->items[$this->languageID]['wcf.pm.addFolder.success'] = 'A new folder was created successfully.';
$this->items[$this->languageID]['wcf.pm.author'] = 'Author';
$this->items[$this->languageID]['wcf.pm.author.system'] = 'System';
$this->items[$this->languageID]['wcf.pm.button.cancel'] = 'Cancel';
$this->items[$this->languageID]['wcf.pm.button.download'] = 'Download';
$this->items[$this->languageID]['wcf.pm.button.downloadDialogue'] = 'Download dialogue';
$this->items[$this->languageID]['wcf.pm.button.edit'] = 'Edit';
$this->items[$this->languageID]['wcf.pm.button.emptyRecycleBin'] = 'Empty recycle bin';
$this->items[$this->languageID]['wcf.pm.button.forward'] = 'Forward';
$this->items[$this->languageID]['wcf.pm.button.markAll'] = 'Select all';
$this->items[$this->languageID]['wcf.pm.button.markAsRead'] = 'Mark as read';
$this->items[$this->languageID]['wcf.pm.button.markAsUnread'] = 'Mark as unread';
$this->items[$this->languageID]['wcf.pm.button.moveTo'] = 'Move to {literal}{$folder}{/literal}';
$this->dynamicItems[$this->languageID]['wcf.pm.button.moveTo'] = 'Move to {$folder}';
$this->items[$this->languageID]['wcf.pm.button.newMessage'] = 'New message';
$this->items[$this->languageID]['wcf.pm.button.recover'] = 'Restore';
$this->items[$this->languageID]['wcf.pm.button.reply'] = 'Reply';
$this->items[$this->languageID]['wcf.pm.button.replyToAll'] = 'Reply to all';
$this->items[$this->languageID]['wcf.pm.button.saveAsDraft'] = 'Save as draft';
$this->items[$this->languageID]['wcf.pm.cancel.sure'] = 'Do you really want to cancel this message?';
$this->items[$this->languageID]['wcf.pm.cancelMarked.sure'] = 'Do you really want to cancel the selected messages?';
$this->items[$this->languageID]['wcf.pm.date'] = 'Date';
$this->items[$this->languageID]['wcf.pm.delete.sure'] = 'Do you really want to delete this message?';
$this->items[$this->languageID]['wcf.pm.deleteFolder'] = 'Delete Folder';
$this->items[$this->languageID]['wcf.pm.deleteFolder.success'] = 'The folder was successfully delted.';
$this->items[$this->languageID]['wcf.pm.deleteFolder.sure'] = 'Do you really want to delete this folder?';
$this->items[$this->languageID]['wcf.pm.deleteMarked.sure'] = 'Do you really want to delete the selected messages?';
$this->items[$this->languageID]['wcf.pm.dialogue'] = 'Conversation';
$this->items[$this->languageID]['wcf.pm.download.message'] = 'Message from: {$author}
Date: {$date}
To: {$recipient}
Subject: {$subject}

{$text}';
$this->dynamicItems[$this->languageID]['wcf.pm.download.message'] = 'Message from: <?php echo StringUtil::encodeHTML($this->v[\'author\']); ?>
Date: <?php echo StringUtil::encodeHTML($this->v[\'date\']); ?>
To: <?php echo StringUtil::encodeHTML($this->v[\'recipient\']); ?>
Subject: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>

<?php echo StringUtil::encodeHTML($this->v[\'text\']); ?>';
$this->items[$this->languageID]['wcf.pm.drafts'] = 'Drafts';
$this->items[$this->languageID]['wcf.pm.editFolders'] = 'Manage folders';
$this->items[$this->languageID]['wcf.pm.editRules'] = 'Manage rules';
$this->items[$this->languageID]['wcf.pm.emptyRecycleBin.sure'] = 'Do you really want to empty the recycle bin?';
$this->items[$this->languageID]['wcf.pm.error.addFolder.tooManyFolders'] = 'You cannot add more folders. You can only have $this->user->getPermission(\'user.pm.maxFolders\') own folders.';
$this->items[$this->languageID]['wcf.pm.error.mailboxIsFull'] = 'Your mail box is full. You have to delete messages first, before you can write new messages.';
$this->items[$this->languageID]['wcf.pm.error.recipient.canNotUsePm'] = '&quot;{$error.username}&quot; cannot receive messages.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.canNotUsePm'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; cannot receive messages.';
$this->items[$this->languageID]['wcf.pm.error.recipient.doesNotAcceptPm'] = '&quot;{$error.username}&quot; does not want to receive messages.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.doesNotAcceptPm'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; does not want to receive messages.';
$this->items[$this->languageID]['wcf.pm.error.recipient.ignoresYou'] = '&quot;{$error.username}&quot; ignores you.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.ignoresYou'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; ignores you.';
$this->items[$this->languageID]['wcf.pm.error.recipient.notFound'] = '&quot;{$error.username}&quot; does not exist.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.notFound'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; does not exist.';
$this->items[$this->languageID]['wcf.pm.error.recipient.onlyAcceptsPmFromBuddies'] = '&quot;{$error.username}&quot; wants to receive messages only from his friends.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.onlyAcceptsPmFromBuddies'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; wants to receive messages only from his friends.';
$this->items[$this->languageID]['wcf.pm.error.recipient.recipientsMailboxIsFull'] = 'The message inbox from &quot;{$error.username}&quot; is full.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.recipientsMailboxIsFull'] = 'The message inbox from &quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; is full.';
$this->items[$this->languageID]['wcf.pm.error.recipient.tooManyRecipients'] = 'You have chosen too many recipients. You can select at most {#$this->getUser()->getPermission(\'user.pm.maxRecipients\')} recipients per message.';
$this->dynamicItems[$this->languageID]['wcf.pm.error.recipient.tooManyRecipients'] = 'You have chosen too many recipients. You can select at most <?php echo StringUtil::formatNumeric($this->v[\'this\']->getUser()->getPermission(\'user.pm.maxRecipients\')); ?> recipients per message.';
$this->items[$this->languageID]['wcf.pm.existingFolders'] = 'Existing folders';
$this->items[$this->languageID]['wcf.pm.feed'] = 'Private Message Feed';
$this->items[$this->languageID]['wcf.pm.feed.description'] = 'Private Messages from the site: {lang}{PAGE_TITLE}{/lang}';
$this->dynamicItems[$this->languageID]['wcf.pm.feed.description'] = 'Private Messages from the site: <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang961ff208160413cba7fc340b01d0a9a892b2ee36 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang961ff208160413cba7fc340b01d0a9a892b2ee36, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>';
$this->items[$this->languageID]['wcf.pm.feed.title'] = '{lang}{PAGE_TITLE}{/lang} - Private Messages';
$this->dynamicItems[$this->languageID]['wcf.pm.feed.title'] = '<?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langdbb54817c55c0d72b73feaea85c9161dd709f8cc = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langdbb54817c55c0d72b73feaea85c9161dd709f8cc, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> - Private Messages';
$this->items[$this->languageID]['wcf.pm.filterBySender'] = 'Sender';
$this->items[$this->languageID]['wcf.pm.forward.subject'] = 'FW: {$subject}';
$this->dynamicItems[$this->languageID]['wcf.pm.forward.subject'] = 'FW: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>';
$this->items[$this->languageID]['wcf.pm.forward.text'] = '
[quote=\'{$author}\']
[i]Send: {$date}
To: {$recipients}
Subject: {$subject}[/i]

{$text}[/quote]';
$this->dynamicItems[$this->languageID]['wcf.pm.forward.text'] = '
[quote=\'<?php echo StringUtil::encodeHTML($this->v[\'author\']); ?>\']
[i]Send: <?php echo StringUtil::encodeHTML($this->v[\'date\']); ?>
To: <?php echo StringUtil::encodeHTML($this->v[\'recipients\']); ?>
Subject: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>[/i]

<?php echo StringUtil::encodeHTML($this->v[\'text\']); ?>[/quote]';
$this->items[$this->languageID]['wcf.pm.from'] = 'From';
$this->items[$this->languageID]['wcf.pm.inbox'] = 'Inbox';
$this->items[$this->languageID]['wcf.pm.information'] = 'Message information';
$this->items[$this->languageID]['wcf.pm.invisibleRecipients'] = 'Invisible recipients';
$this->items[$this->languageID]['wcf.pm.markAsReadByDoubleClick'] = 'Mark message as read by double click';
$this->items[$this->languageID]['wcf.pm.markedMessages'] = 'this.count == 1 ? "One message selected" : this.count+" messages selected"';
$this->items[$this->languageID]['wcf.pm.messageFrom'] = 'from';
$this->items[$this->languageID]['wcf.pm.moveMessageTo'] = 'Move message to:';
$this->items[$this->languageID]['wcf.pm.newMessage'] = 'Create new message';
$this->items[$this->languageID]['wcf.pm.noMessages'] = 'This folder does not contain any messages.';
$this->items[$this->languageID]['wcf.pm.notification.cancel'] = 'Cancel notification';
$this->items[$this->languageID]['wcf.pm.notification.mail'] = 'Hello {$recipient},

You have received a new private message from {$author}:
---------------------------------
Subject: {$subject}
{$text}
---------------------------------

Please use this link to jump directly to your message inbox where you can answer this private message.
{PAGE_URL}/index.php?page=PMList

DO NOT ANSWER THIS E_MAIL. It is an automatic notification.

Have a nice day,
Your {PAGE_TITLE} team';
$this->dynamicItems[$this->languageID]['wcf.pm.notification.mail'] = 'Hello <?php echo StringUtil::encodeHTML($this->v[\'recipient\']); ?>,

You have received a new private message from <?php echo StringUtil::encodeHTML($this->v[\'author\']); ?>:
---------------------------------
Subject: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>
<?php echo StringUtil::encodeHTML($this->v[\'text\']); ?>
---------------------------------

Please use this link to jump directly to your message inbox where you can answer this private message.
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?page=PMList

DO NOT ANSWER THIS E_MAIL. It is an automatic notification.

Have a nice day,
Your <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> team';
$this->items[$this->languageID]['wcf.pm.notification.report'] = 'You have {#$this->user->pmOutstandingNotifications} unread private message{if $this->user->pmOutstandingNotifications > 1}s{/if}:';
$this->dynamicItems[$this->languageID]['wcf.pm.notification.report'] = 'You have <?php echo StringUtil::formatNumeric($this->v[\'this\']->user->pmOutstandingNotifications); ?> unread private message<?php if ($this->v[\'this\']->user->pmOutstandingNotifications > 1) { ?>s<?php } ?>:';
$this->items[$this->languageID]['wcf.pm.notification.subject'] = 'New private message from {$author} at {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.pm.notification.subject'] = 'New private message from <?php echo StringUtil::encodeHTML($this->v[\'author\']); ?> at <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.pm.originalMessage'] = 'Original message';
$this->items[$this->languageID]['wcf.pm.outbox'] = 'Outbox';
$this->items[$this->languageID]['wcf.pm.profile.sendPM'] = 'Send private message';
$this->items[$this->languageID]['wcf.pm.recipient'] = 'Recipient';
$this->items[$this->languageID]['wcf.pm.recipientList'] = 'Recipients:';
$this->items[$this->languageID]['wcf.pm.renameFolders.success'] = 'The folders were renamed successfully.';
$this->items[$this->languageID]['wcf.pm.reply.subject'] = 'RE: {$subject}';
$this->dynamicItems[$this->languageID]['wcf.pm.reply.subject'] = 'RE: <?php echo StringUtil::encodeHTML($this->v[\'subject\']); ?>';
$this->items[$this->languageID]['wcf.pm.search.folders'] = 'Search the following folders';
$this->items[$this->languageID]['wcf.pm.search.folders.all'] = 'Search in all folders';
$this->items[$this->languageID]['wcf.pm.search.query'] = 'Search messages';
$this->items[$this->languageID]['wcf.pm.search.result.sender'] = 'Private message from: <a href="index.php?page=User&amp;userID={@$item.message->userID}{@SID_ARG_2ND}">{$item.message->username}</a>';
$this->dynamicItems[$this->languageID]['wcf.pm.search.result.sender'] = 'Private message from: <a href="index.php?page=User&amp;userID=<?php echo $this->v[\'item\'][\'message\']->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v[\'item\'][\'message\']->username); ?></a>';
$this->items[$this->languageID]['wcf.pm.sortBy'] = 'Sort by';
$this->items[$this->languageID]['wcf.pm.sortBy.isViewed'] = 'Read';
$this->items[$this->languageID]['wcf.pm.sortBy.isViewedByAll'] = 'Read';
$this->items[$this->languageID]['wcf.pm.sortBy.recipients'] = 'Recipients';
$this->items[$this->languageID]['wcf.pm.sortBy.subject'] = 'Subject';
$this->items[$this->languageID]['wcf.pm.sortBy.time'] = 'Date';
$this->items[$this->languageID]['wcf.pm.sortBy.username'] = 'Author';
$this->items[$this->languageID]['wcf.pm.sorting'] = 'Sorting';
$this->items[$this->languageID]['wcf.pm.subject'] = 'Subject';
$this->items[$this->languageID]['wcf.pm.subject.description'] = 'Enter the subject of this message.';
$this->items[$this->languageID]['wcf.pm.text'] = 'Message';
$this->items[$this->languageID]['wcf.pm.text.description'] = 'Enter the text of the private message that you want to send.';
$this->items[$this->languageID]['wcf.pm.title'] = 'Private messages';
$this->items[$this->languageID]['wcf.pm.trash'] = 'Recycle bin';
$this->items[$this->languageID]['wcf.pm.usage'] = '{@$usage*100|floor}% disk space in use';
$this->dynamicItems[$this->languageID]['wcf.pm.usage'] = '<?php echo floor($this->v[\'usage\']*100); ?>% disk space in use';
$this->items[$this->languageID]['wcf.pm.userMenu.mailboxIsFull'] = '(Mail box full)';
$this->items[$this->languageID]['wcf.pm.visibleRecipients'] = 'Visible recipients';
?>