<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.global
* generated at Tue, 13 Aug 2013 11:36:40 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.global.button.back'] = '&laquo; Back';
$this->items[$this->languageID]['wcf.global.button.close'] = 'Close';
$this->items[$this->languageID]['wcf.global.button.collapse'] = 'Collapse';
$this->items[$this->languageID]['wcf.global.button.collapsible'] = 'Expand or collapse';
$this->items[$this->languageID]['wcf.global.button.delete'] = 'Delete';
$this->items[$this->languageID]['wcf.global.button.delete.confirm'] = 'Do you really want to delete this item?';
$this->items[$this->languageID]['wcf.global.button.deleteCompletely'] = 'Delete completely';
$this->items[$this->languageID]['wcf.global.button.edit'] = 'Edit';
$this->items[$this->languageID]['wcf.global.button.editor.jump'] = 'Use full editor';
$this->items[$this->languageID]['wcf.global.button.expand'] = 'Expand';
$this->items[$this->languageID]['wcf.global.button.mark'] = 'Select';
$this->items[$this->languageID]['wcf.global.button.next'] = 'Next &raquo;';
$this->items[$this->languageID]['wcf.global.button.preview'] = 'Preview';
$this->items[$this->languageID]['wcf.global.button.reset'] = 'Reset';
$this->items[$this->languageID]['wcf.global.button.submit'] = 'Submit';
$this->items[$this->languageID]['wcf.global.button.unmark'] = 'Unselect';
$this->items[$this->languageID]['wcf.global.date.day'] = 'Day';
$this->items[$this->languageID]['wcf.global.date.days'] = 'Days';
$this->items[$this->languageID]['wcf.global.date.hour'] = 'Hour';
$this->items[$this->languageID]['wcf.global.date.hours'] = 'Hours';
$this->items[$this->languageID]['wcf.global.date.minute'] = 'Minute';
$this->items[$this->languageID]['wcf.global.date.minutes'] = 'Minutes';
$this->items[$this->languageID]['wcf.global.date.month'] = 'Month';
$this->items[$this->languageID]['wcf.global.date.months'] = 'Months';
$this->items[$this->languageID]['wcf.global.date.second'] = 'Second';
$this->items[$this->languageID]['wcf.global.date.seconds'] = 'Seconds';
$this->items[$this->languageID]['wcf.global.date.week'] = 'Week';
$this->items[$this->languageID]['wcf.global.date.weeks'] = 'Weeks';
$this->items[$this->languageID]['wcf.global.date.year'] = 'Year';
$this->items[$this->languageID]['wcf.global.date.year.notRequired'] = 'Specifying the year is optional.';
$this->items[$this->languageID]['wcf.global.date.years'] = 'Years';
$this->items[$this->languageID]['wcf.global.dateFormat'] = 'M jS Y';
$this->items[$this->languageID]['wcf.global.dateFormatToday'] = '<b>\T\o\d\a\y</b>, g:ia';
$this->items[$this->languageID]['wcf.global.dateFormatYesterday'] = '\Y\e\s\t\e\r\d\a\y, g:ia';
$this->items[$this->languageID]['wcf.global.dateInputOrder'] = 'month-day-year';
$this->items[$this->languageID]['wcf.global.dateMethod'] = 'date';
$this->items[$this->languageID]['wcf.global.decimalPoint'] = '.';
$this->items[$this->languageID]['wcf.global.defaultValue'] = 'Default';
$this->items[$this->languageID]['wcf.global.error.backward'] = 'Back to last page';
$this->items[$this->languageID]['wcf.global.error.empty'] = 'Please enter the required information for this field.';
$this->items[$this->languageID]['wcf.global.error.file.notFound'] = 'The file could not be found.';
$this->items[$this->languageID]['wcf.global.error.illegalLink'] = 'The link you are trying to reach is no longer available or is invalid.';
$this->items[$this->languageID]['wcf.global.error.permissionDenied'] = 'You are not allowed to enter this page. You do not have the required permissions to enter this page.';
$this->items[$this->languageID]['wcf.global.error.permissionDenied.title'] = 'You are not allowed to enter this page.';
$this->items[$this->languageID]['wcf.global.error.title'] = 'Error message';
$this->items[$this->languageID]['wcf.global.form.error'] = 'The data you have entered are invalid. Please check the information you have given in the marked fields.';
$this->items[$this->languageID]['wcf.global.language.ar'] = 'Arabic';
$this->items[$this->languageID]['wcf.global.language.bs'] = 'Bosnian';
$this->items[$this->languageID]['wcf.global.language.cs'] = 'Czech';
$this->items[$this->languageID]['wcf.global.language.da'] = 'Danish';
$this->items[$this->languageID]['wcf.global.language.de'] = 'German';
$this->items[$this->languageID]['wcf.global.language.de-informal'] = 'German (Informal)';
$this->items[$this->languageID]['wcf.global.language.el'] = 'Greek';
$this->items[$this->languageID]['wcf.global.language.en'] = 'English';
$this->items[$this->languageID]['wcf.global.language.es'] = 'Spanish';
$this->items[$this->languageID]['wcf.global.language.fa'] = 'Persian (Farsi)';
$this->items[$this->languageID]['wcf.global.language.fi'] = 'Finnish';
$this->items[$this->languageID]['wcf.global.language.fr'] = 'French';
$this->items[$this->languageID]['wcf.global.language.he'] = 'Hebrew';
$this->items[$this->languageID]['wcf.global.language.hr'] = 'Croatian';
$this->items[$this->languageID]['wcf.global.language.hu'] = 'Hungarian';
$this->items[$this->languageID]['wcf.global.language.it'] = 'Italian';
$this->items[$this->languageID]['wcf.global.language.ja'] = 'Japanese';
$this->items[$this->languageID]['wcf.global.language.ko'] = 'Korean';
$this->items[$this->languageID]['wcf.global.language.nl'] = 'Dutch';
$this->items[$this->languageID]['wcf.global.language.no'] = 'Norwegian';
$this->items[$this->languageID]['wcf.global.language.pl'] = 'Polish';
$this->items[$this->languageID]['wcf.global.language.pt'] = 'Portuguese';
$this->items[$this->languageID]['wcf.global.language.pt-BR'] = 'Portuguese (Brazil)';
$this->items[$this->languageID]['wcf.global.language.ro'] = 'Romanian';
$this->items[$this->languageID]['wcf.global.language.ru'] = 'Russian';
$this->items[$this->languageID]['wcf.global.language.sk'] = 'Slovak';
$this->items[$this->languageID]['wcf.global.language.sr'] = 'Serbian';
$this->items[$this->languageID]['wcf.global.language.sv'] = 'Swedish';
$this->items[$this->languageID]['wcf.global.language.th'] = 'Thai';
$this->items[$this->languageID]['wcf.global.language.tr'] = 'Turkish';
$this->items[$this->languageID]['wcf.global.language.zh-CN'] = 'Chinese (Simplified)';
$this->items[$this->languageID]['wcf.global.language.zh-TW'] = 'Chinese (Traditional)';
$this->items[$this->languageID]['wcf.global.locale.unix'] = 'en_US';
$this->items[$this->languageID]['wcf.global.locale.win'] = 'english';
$this->items[$this->languageID]['wcf.global.multiSelect'] = 'Multiple items can be selected by holding the &quot;Ctrl/Shift&quot; key (Windows) or &quot;Command&quot; (Mac OS) key and clicking the items required.';
$this->items[$this->languageID]['wcf.global.page.input'] = 'Go to next page';
$this->items[$this->languageID]['wcf.global.page.next'] = 'Next page';
$this->items[$this->languageID]['wcf.global.page.previous'] = 'Previous page';
$this->items[$this->languageID]['wcf.global.pageDirection'] = 'ltr';
$this->items[$this->languageID]['wcf.global.pageTitle'] = 'WoltLab&reg; Community Framework&trade;';
$this->items[$this->languageID]['wcf.global.redirect.title'] = 'Redirection';
$this->items[$this->languageID]['wcf.global.redirect.url'] = 'Please click here if the automatic redirection does not work!';
$this->items[$this->languageID]['wcf.global.scrollUp'] = 'Go to the top of the page';
$this->items[$this->languageID]['wcf.global.search.matchesExactly'] = 'Exact match';
$this->items[$this->languageID]['wcf.global.shortTimeFormat'] = 'M jS Y, g:ia';
$this->items[$this->languageID]['wcf.global.skipToContent'] = 'Skip navigation';
$this->items[$this->languageID]['wcf.global.sortOrder.ascending'] = 'ascending';
$this->items[$this->languageID]['wcf.global.sortOrder.descending'] = 'descending';
$this->items[$this->languageID]['wcf.global.thousandsSeparator'] = ',';
$this->items[$this->languageID]['wcf.global.timeFormat'] = 'l, F jS Y, g:ia';
?>