<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.user.profile
* generated at Tue, 13 Aug 2013 17:19:30 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.profile.addToBuddyList'] = 'Add user to friend list';
$this->items[$this->languageID]['wcf.user.profile.addToIgnoreList'] = 'Ignore user';
$this->items[$this->languageID]['wcf.user.profile.avatar.disable'] = 'Disable Avatar';
$this->items[$this->languageID]['wcf.user.profile.avatar.enable'] = 'Enable Avatar';
$this->items[$this->languageID]['wcf.user.profile.banned'] = '&quot;{$username}&quot; has been banned';
$this->dynamicItems[$this->languageID]['wcf.user.profile.banned'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; has been banned';
$this->items[$this->languageID]['wcf.user.profile.birthday'] = '&quot;{$username}&quot; {if $age}is {$age} years old today{else}celebrates his birthday today{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.profile.birthday'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; <?php if ($this->v[\'age\']) { ?>is <?php echo StringUtil::encodeHTML($this->v[\'age\']); ?> years old today<?php } else { ?>celebrates his birthday today<?php } ?>';
$this->items[$this->languageID]['wcf.user.profile.button.edit'] = 'Edit profile';
$this->items[$this->languageID]['wcf.user.profile.connection'] = 'Your connection to &quot;{$user->username}&quot;';
$this->dynamicItems[$this->languageID]['wcf.user.profile.connection'] = 'Your connection to &quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']->username); ?>&quot;';
$this->items[$this->languageID]['wcf.user.profile.connection.guest'] = 'You have to register first, to connect to this user.';
$this->items[$this->languageID]['wcf.user.profile.connection.none'] = 'You have no connection to this user yet.';
$this->items[$this->languageID]['wcf.user.profile.contact'] = 'Contact';
$this->items[$this->languageID]['wcf.user.profile.currentLocation'] = 'Browsing';
$this->items[$this->languageID]['wcf.user.profile.downloadVCard'] = 'Download vCard';
$this->items[$this->languageID]['wcf.user.profile.edit'] = 'Edit my profile';
$this->items[$this->languageID]['wcf.user.profile.email.title'] = 'Send e-mail to &quot;{$username}&quot;';
$this->dynamicItems[$this->languageID]['wcf.user.profile.email.title'] = 'Send e-mail to &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot;';
$this->items[$this->languageID]['wcf.user.profile.error.ignoredUser'] = '&quot;{$username}&quot; is ignoring you. You cannot access his user profile.';
$this->dynamicItems[$this->languageID]['wcf.user.profile.error.ignoredUser'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; is ignoring you. You cannot access his user profile.';
$this->items[$this->languageID]['wcf.user.profile.error.protectedProfile'] = 'The details of this user profile are accessible only by friends of &quot;{$username}&quot;.';
$this->dynamicItems[$this->languageID]['wcf.user.profile.error.protectedProfile'] = 'The details of this user profile are accessible only by friends of &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot;.';
$this->items[$this->languageID]['wcf.user.profile.friend'] = '&quot;{$username}&quot; is your friend';
$this->dynamicItems[$this->languageID]['wcf.user.profile.friend'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; is your friend';
$this->items[$this->languageID]['wcf.user.profile.friends'] = 'Friends';
$this->items[$this->languageID]['wcf.user.profile.friends.allFriends'] = 'Show all friends';
$this->items[$this->languageID]['wcf.user.profile.gender.female'] = '&quot;{$username}&quot; is female';
$this->dynamicItems[$this->languageID]['wcf.user.profile.gender.female'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; is female';
$this->items[$this->languageID]['wcf.user.profile.gender.male'] = '&quot;{$username}&quot; is male';
$this->dynamicItems[$this->languageID]['wcf.user.profile.gender.male'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; is male';
$this->items[$this->languageID]['wcf.user.profile.general'] = 'General information';
$this->items[$this->languageID]['wcf.user.profile.hits'] = 'Profile hits';
$this->items[$this->languageID]['wcf.user.profile.hitsPerDay'] = '({#$user->profileHits/$user->getProfileAge()} Hits per day)';
$this->dynamicItems[$this->languageID]['wcf.user.profile.hitsPerDay'] = '(<?php echo StringUtil::formatNumeric($this->v[\'user\']->profileHits/$this->v[\'user\']->getProfileAge()); ?> Hits per day)';
$this->items[$this->languageID]['wcf.user.profile.homepage.title'] = 'Visit the personal website of &quot;{$username}&quot;';
$this->dynamicItems[$this->languageID]['wcf.user.profile.homepage.title'] = 'Visit the personal website of &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot;';
$this->items[$this->languageID]['wcf.user.profile.languages'] = 'Languages';
$this->items[$this->languageID]['wcf.user.profile.members'] = 'Members';
$this->items[$this->languageID]['wcf.user.profile.menu.link.friends'] = 'Friends';
$this->items[$this->languageID]['wcf.user.profile.menu.link.profile'] = 'Profile';
$this->items[$this->languageID]['wcf.user.profile.network'] = 'Your network';
$this->items[$this->languageID]['wcf.user.profile.network.friends'] = 'Direct Friends';
$this->items[$this->languageID]['wcf.user.profile.network.friends3rdGrade'] = 'Third degree friends';
$this->items[$this->languageID]['wcf.user.profile.network.friendsOfFriends'] = 'Friends of friends';
$this->items[$this->languageID]['wcf.user.profile.network.none'] = 'Extend your personal network by adding other members as friends.';
$this->items[$this->languageID]['wcf.user.profile.noDeclaration'] = 'No entry';
$this->items[$this->languageID]['wcf.user.profile.oldUsername'] = '(formerly &quot;{$user->getOldUsername()}&quot;)';
$this->dynamicItems[$this->languageID]['wcf.user.profile.oldUsername'] = '(formerly &quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']->getOldUsername()); ?>&quot;)';
$this->items[$this->languageID]['wcf.user.profile.removeFromBuddyList'] = 'Remove friend';
$this->items[$this->languageID]['wcf.user.profile.removeFromIgnoreList'] = 'Cancel ignoring';
$this->items[$this->languageID]['wcf.user.profile.search.query'] = 'Search user posts';
$this->items[$this->languageID]['wcf.user.profile.title'] = 'Profile of &quot;{$user->username}&quot;';
$this->dynamicItems[$this->languageID]['wcf.user.profile.title'] = 'Profile of &quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']->username); ?>&quot;';
$this->items[$this->languageID]['wcf.user.profile.visitors'] = 'Visitors';
$this->items[$this->languageID]['wcf.user.profile.aim.title'] = 'Contact &quot;{$username}&quot; over AOL Instant Messenger (AIM)';
$this->dynamicItems[$this->languageID]['wcf.user.profile.aim.title'] = 'Contact &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; over AOL Instant Messenger (AIM)';
$this->items[$this->languageID]['wcf.user.profile.icq.title'] = 'Contact &quot;{$username}&quot; by ICQ';
$this->dynamicItems[$this->languageID]['wcf.user.profile.icq.title'] = 'Contact &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; by ICQ';
$this->items[$this->languageID]['wcf.user.profile.msn.title'] = 'Contact &quot;{$username}&quot; by Windows Live Messenger';
$this->dynamicItems[$this->languageID]['wcf.user.profile.msn.title'] = 'Contact &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; by Windows Live Messenger';
$this->items[$this->languageID]['wcf.user.profile.skype.title'] = 'Contact &quot;{$username}&quot; by Skype';
$this->dynamicItems[$this->languageID]['wcf.user.profile.skype.title'] = 'Contact &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; by Skype';
$this->items[$this->languageID]['wcf.user.profile.yim.title'] = 'Contact &quot;{$username}&quot; by Yahoo! Instant Messenger (YIM)';
$this->dynamicItems[$this->languageID]['wcf.user.profile.yim.title'] = 'Contact &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; by Yahoo! Instant Messenger (YIM)';
$this->items[$this->languageID]['wcf.user.profile.jabber.title'] = 'Contact &quot;{$username}&quot; by Jabber';
$this->dynamicItems[$this->languageID]['wcf.user.profile.jabber.title'] = 'Contact &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot; by Jabber';
$this->items[$this->languageID]['wcf.user.profile.signature.disable'] = 'Disable signature';
$this->items[$this->languageID]['wcf.user.profile.signature.enable'] = 'Enable signature';
$this->items[$this->languageID]['wcf.user.profile.menu.link.infraction'] = 'Infractions';
$this->items[$this->languageID]['wcf.user.profile.allPosts'] = 'Show all posts';
$this->items[$this->languageID]['wcf.user.profile.allThreads'] = 'Show all threads';
$this->items[$this->languageID]['wcf.user.profile.lastPosts'] = 'Posts';
$this->items[$this->languageID]['wcf.user.profile.search'] = 'Search all posts by &quot;{$username}&quot;';
$this->dynamicItems[$this->languageID]['wcf.user.profile.search'] = 'Search all posts by &quot;<?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>&quot;';
?>