<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wbb.search
* generated at Tue, 13 Aug 2013 11:36:41 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.search.boards'] = 'Search in the following forum(s)';
$this->items[$this->languageID]['wbb.search.boards.all'] = 'Search in all forums';
$this->items[$this->languageID]['wbb.search.error.noMatches'] = 'There are no results for your search.';
$this->items[$this->languageID]['wbb.search.findAttachments'] = 'Show only posts with attachments';
$this->items[$this->languageID]['wbb.search.findPolls'] = 'Show only posts with polls';
$this->items[$this->languageID]['wbb.search.findUserThreads'] = 'Show only threads that have been started by this user';
$this->items[$this->languageID]['wbb.search.newPostsSinceLastVisit'] = 'New posts since {@$this->user->boardLastVisitTime|shorttime}';
$this->dynamicItems[$this->languageID]['wbb.search.newPostsSinceLastVisit'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierShorttime\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierShorttime.class.php\');
$this->pluginObjects[\'TemplatePluginModifierShorttime\'] = new TemplatePluginModifierShorttime;
}
?>New posts since <?php echo $this->pluginObjects[\'TemplatePluginModifierShorttime\']->execute(array($this->v[\'this\']->user->boardLastVisitTime), $this); ?>';
$this->items[$this->languageID]['wbb.search.result.author'] = 'Author: {if $item.message->userID}<a href="index.php?page=User&amp;userID={@$item.message->userID}{@SID_ARG_2ND}">{$item.message->username}</a>{else}{$item.message->username}{/if}';
$this->dynamicItems[$this->languageID]['wbb.search.result.author'] = 'Author: <?php if ($this->v[\'item\'][\'message\']->userID) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v[\'item\'][\'message\']->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v[\'item\'][\'message\']->username); ?></a><?php } else { ?><?php echo StringUtil::encodeHTML($this->v[\'item\'][\'message\']->username); ?><?php } ?>';
$this->items[$this->languageID]['wbb.search.results.display'] = 'Display type';
$this->items[$this->languageID]['wbb.search.results.display.post'] = 'Message preview';
$this->items[$this->languageID]['wbb.search.results.display.thread'] = 'Thread list';
$this->items[$this->languageID]['wbb.search.threadsOfTheLast24Hours'] = 'Threads of the last 24 hours';
$this->items[$this->languageID]['wbb.search.unreadPosts'] = 'Unread posts';
$this->items[$this->languageID]['wbb.search.unrepliedThreads'] = 'Unreplied threads';
?>