<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.user.login
* generated at Sat, 17 Aug 2013 09:22:34 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.login'] = 'Login';
$this->items[$this->languageID]['wcf.user.login.error.password.false'] = 'The password you entered is invalid. If you have lost your password you can use the <a href="index.php?form=LostPassword{@SID_ARG_2ND}">&quot;Lost Password&quot; function</a>.';
$this->dynamicItems[$this->languageID]['wcf.user.login.error.password.false'] = 'The password you entered is invalid. If you have lost your password you can use the <a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">&quot;Lost Password&quot; function</a>.';
$this->items[$this->languageID]['wcf.user.login.redirect'] = 'You have been successfully logged in.';
$this->items[$this->languageID]['wcf.user.login.useCookies'] = 'Remember my login on this computer until I logout manually.';
?>