<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.page
* generated at Tue, 13 Aug 2013 17:19:25 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.page.pageNo'] = 'Page {#$pageNo}';
$this->dynamicItems[$this->languageID]['wcf.page.pageNo'] = 'Page <?php echo StringUtil::formatNumeric($this->v[\'pageNo\']); ?>';
?>