<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.acp.user
* generated at Thu, 22 Aug 2013 20:21:18 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.acp.user.add'] = 'Add new user';
$this->items[$this->languageID]['wcf.acp.user.add.data'] = 'User details';
$this->items[$this->languageID]['wcf.acp.user.add.success'] = 'The new user has been successfully saved.';
$this->items[$this->languageID]['wcf.acp.user.assignToGroup'] = 'Group assignment';
$this->items[$this->languageID]['wcf.acp.user.assignToGroup.markedUsers'] = 'Assign the following users to the selected group(s)';
$this->items[$this->languageID]['wcf.acp.user.assignToGroup.success'] = 'The users have been successfully assigned to your chosen groups.';
$this->items[$this->languageID]['wcf.acp.user.button.assignGroup'] = 'Group assignment';
$this->items[$this->languageID]['wcf.acp.user.button.exportMail'] = 'Export e-mail addresses';
$this->items[$this->languageID]['wcf.acp.user.button.sendMail'] = 'Send an e-mail';
$this->items[$this->languageID]['wcf.acp.user.delete'] = 'Delete user(s)';
$this->items[$this->languageID]['wcf.acp.user.delete.error'] = 'No user could be deleted.';
$this->items[$this->languageID]['wcf.acp.user.delete.success'] = '{if $deletedUsers == 1}The user has {else}{#$deletedUsers} users have{/if} been successfully deleted.';
$this->dynamicItems[$this->languageID]['wcf.acp.user.delete.success'] = '<?php if ($this->v[\'deletedUsers\'] == 1) { ?>The user has <?php } else { ?><?php echo StringUtil::formatNumeric($this->v[\'deletedUsers\']); ?> users have<?php } ?> been successfully deleted.';
$this->items[$this->languageID]['wcf.acp.user.delete.sure'] = 'Are you sure that you would like to delete this user?';
$this->items[$this->languageID]['wcf.acp.user.deleteMarked.sure'] = 'Are you sure that you would like to delete the selected User(s)?';
$this->items[$this->languageID]['wcf.acp.user.edit'] = 'Edit user';
$this->items[$this->languageID]['wcf.acp.user.edit.success'] = 'The changes for this user have been successfully saved.';
$this->items[$this->languageID]['wcf.acp.user.edit.warning.selfEdit'] = 'You are currently editing your own user account. Changing the permissions of this user group might lead to locking yourself out of the Administration Control Panel. Please be careful!';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress'] = 'Export e-mail addresses';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.fileType'] = 'Export file format';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.fileType.csv'] = 'CSV (<em>Character Separated Values</em>)';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.fileType.xml'] = 'XML (<em>Extensible Markup Language</em>)';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.format'] = 'Export options';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.markedUsers'] = 'Export the e-mail addresses from the following users';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.separator'] = 'Separate the addresses with a ';
$this->items[$this->languageID]['wcf.acp.user.exportEmailAddress.textSeparator'] = 'Enclose the addresses with ';
$this->items[$this->languageID]['wcf.acp.user.groups'] = 'Group memberships';
$this->items[$this->languageID]['wcf.acp.user.groups.invertSearch'] = 'Find users that are not members of the chosen user groups.';
$this->items[$this->languageID]['wcf.acp.user.list'] = 'Users';
$this->items[$this->languageID]['wcf.acp.user.list.all'] = 'All users';
$this->items[$this->languageID]['wcf.acp.user.list.count'] = 'A total of {#$items} user{if $items > 1}s{/if}';
$this->dynamicItems[$this->languageID]['wcf.acp.user.list.count'] = 'A total of <?php echo StringUtil::formatNumeric($this->v[\'items\']); ?> user<?php if ($this->v[\'items\'] > 1) { ?>s<?php } ?>';
$this->items[$this->languageID]['wcf.acp.user.markedUsers'] = 'this.count == 1 ? "1 user selected" : this.count+" users selected"';
$this->items[$this->languageID]['wcf.acp.user.massProcessing'] = 'Bulk processing of users';
$this->items[$this->languageID]['wcf.acp.user.massProcessing.action'] = 'Action';
$this->items[$this->languageID]['wcf.acp.user.massProcessing.conditions'] = 'Conditions';
$this->items[$this->languageID]['wcf.acp.user.massProcessing.success'] = 'The chosen action has been executed successfully on {#$affectedUsers} users.';
$this->dynamicItems[$this->languageID]['wcf.acp.user.massProcessing.success'] = 'The chosen action has been executed successfully on <?php echo StringUtil::formatNumeric($this->v[\'affectedUsers\']); ?> users.';
$this->items[$this->languageID]['wcf.acp.user.massProcessing.warning'] = 'The bulk processor will perform the following tasks <strong>without additional security notification</strong>, on all users matching the set conditions. Bulk processing can be very performance intensive, so it should only be executed when the forum is offline. To have a correct display of your content you should update the counters. The processing can not be reversed, so please be attentive when using this function.';
$this->items[$this->languageID]['wcf.acp.user.search'] = 'Search for users';
$this->items[$this->languageID]['wcf.acp.user.search.conditions'] = 'Search criteria';
$this->items[$this->languageID]['wcf.acp.user.search.conditions.general'] = 'General search criteria';
$this->items[$this->languageID]['wcf.acp.user.search.conditions.profile'] = 'Profile search criteria';
$this->items[$this->languageID]['wcf.acp.user.search.display'] = 'Display';
$this->items[$this->languageID]['wcf.acp.user.search.display.columns'] = 'Columns';
$this->items[$this->languageID]['wcf.acp.user.search.display.columns.other'] = 'Other';
$this->items[$this->languageID]['wcf.acp.user.search.display.columns.profile'] = 'Profile';
$this->items[$this->languageID]['wcf.acp.user.search.display.general'] = 'General';
$this->items[$this->languageID]['wcf.acp.user.search.display.itemsPerPage'] = 'Users per page';
$this->items[$this->languageID]['wcf.acp.user.search.display.sort'] = 'Sorting';
$this->items[$this->languageID]['wcf.acp.user.search.error.noMatches'] = 'No users have been found.';
$this->items[$this->languageID]['wcf.acp.user.search.matches'] = 'Your search produced {if $items == 1}one result{else}{#$items} results{/if}';
$this->dynamicItems[$this->languageID]['wcf.acp.user.search.matches'] = 'Your search produced <?php if ($this->v[\'items\'] == 1) { ?>one result<?php } else { ?><?php echo StringUtil::formatNumeric($this->v[\'items\']); ?> results<?php } ?>';
$this->items[$this->languageID]['wcf.acp.user.search.withinResults'] = 'Search within results';
$this->items[$this->languageID]['wcf.acp.user.sendMail'] = 'Send an e-mail';
$this->items[$this->languageID]['wcf.acp.user.sendMail.all'] = 'E-Mail all Users';
$this->items[$this->languageID]['wcf.acp.user.sendMail.enableHTML'] = 'Send e-mail as HTML';
$this->items[$this->languageID]['wcf.acp.user.sendMail.from'] = 'Sender';
$this->items[$this->languageID]['wcf.acp.user.sendMail.from.description'] = '<p>Here you can enter the sender\'s e-mail address in the following format:</p>
<p style="text-align: center; line-height: 2em;"><code>{if MAIL_USE_FORMATTED_ADDRESS}Senders name &lt;email@sender.tld&gt;{else}email@sender.tld{/if}</code></p>
<p>If you have completely filled in the section under System -> Options -> E-mail, then this field will automatically be filled in. If you are sending e-mails using SMTP, then the sender\'s e-mail-Address must also be accepted by the server.</p>';
$this->dynamicItems[$this->languageID]['wcf.acp.user.sendMail.from.description'] = '<p>Here you can enter the sender\'s e-mail address in the following format:</p>
<p style="text-align: center; line-height: 2em;"><code><?php if (MAIL_USE_FORMATTED_ADDRESS) { ?>Senders name &lt;email@sender.tld&gt;<?php } else { ?>email@sender.tld<?php } ?></code></p>
<p>If you have completely filled in the section under System -> Options -> E-mail, then this field will automatically be filled in. If you are sending e-mails using SMTP, then the sender\'s e-mail-Address must also be accepted by the server.</p>';
$this->items[$this->languageID]['wcf.acp.user.sendMail.group'] = 'E-mail all group members';
$this->items[$this->languageID]['wcf.acp.user.sendMail.groups'] = 'Send an e-mail to the members of the following user groups:';
$this->items[$this->languageID]['wcf.acp.user.sendMail.mail'] = 'E-mail';
$this->items[$this->languageID]['wcf.acp.user.sendMail.markedUsers'] = 'Send an e-mail to the following users';
$this->items[$this->languageID]['wcf.acp.user.sendMail.subject'] = 'Subject';
$this->items[$this->languageID]['wcf.acp.user.sendMail.subject.description'] = 'Enter here the e-mail subject.';
$this->items[$this->languageID]['wcf.acp.user.sendMail.text'] = 'Message';
$this->items[$this->languageID]['wcf.acp.user.sendMail.text.description'] = 'Enter here the message you want to send to users.';
$this->items[$this->languageID]['wcf.acp.user.userNote'] = 'Welcome {$this->user->username}.';
$this->dynamicItems[$this->languageID]['wcf.acp.user.userNote'] = 'Welcome <?php echo StringUtil::encodeHTML($this->v[\'this\']->user->username); ?>.';
$this->items[$this->languageID]['wcf.acp.user.activation.mail'] = 'Hello {$username},

Your account at {PAGE_TITLE} has been enabled by an administrator.
You now have full access to the functions of this site.

Yours truly,
The {PAGE_TITLE} Team';
$this->dynamicItems[$this->languageID]['wcf.acp.user.activation.mail'] = 'Hello <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>,

Your account at <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> has been enabled by an administrator.
You now have full access to the functions of this site.

Yours truly,
The <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> Team';
$this->items[$this->languageID]['wcf.acp.user.activation.mail.subject'] = 'Your account has been enabled at: {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.acp.user.activation.mail.subject'] = 'Your account has been enabled at: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.acp.user.ban'] = 'Ban user';
$this->items[$this->languageID]['wcf.acp.user.ban.markedUsers'] = 'The following users have been banned';
$this->items[$this->languageID]['wcf.acp.user.ban.reason'] = 'Reason';
$this->items[$this->languageID]['wcf.acp.user.ban.reason.description'] = 'Enter an optional reason fo the ban. This reason will be displayed to the banned user.';
$this->items[$this->languageID]['wcf.acp.user.ban.success'] = 'The users have been banned successfully.';
$this->items[$this->languageID]['wcf.acp.user.button.ban'] = 'Ban';
$this->items[$this->languageID]['wcf.acp.user.button.disable'] = 'Disable';
$this->items[$this->languageID]['wcf.acp.user.button.enable'] = 'Enable';
$this->items[$this->languageID]['wcf.acp.user.button.sendActivationMail'] = 'Send activation e-mail';
$this->items[$this->languageID]['wcf.acp.user.button.sendNewPassword'] = 'Send new password';
$this->items[$this->languageID]['wcf.acp.user.button.unban'] = 'Remove ban';
$this->items[$this->languageID]['wcf.acp.user.disable.success'] = 'The users have been successfully disabled.';
$this->items[$this->languageID]['wcf.acp.user.enable.success'] = 'The users have been enabled successfully.';
$this->items[$this->languageID]['wcf.acp.user.list.banned'] = 'Banned users';
$this->items[$this->languageID]['wcf.acp.user.list.new'] = 'New users';
$this->items[$this->languageID]['wcf.acp.user.list.notActivated'] = 'Not activated users';
$this->items[$this->languageID]['wcf.acp.user.newPassword.mail'] = 'Hello {$username},

Your password at: {PAGE_TITLE} has been changed by an administrator.

Your new password is: {$password}

Yours truly,
The {PAGE_TITLE} Team';
$this->dynamicItems[$this->languageID]['wcf.acp.user.newPassword.mail'] = 'Hello <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>,

Your password at: <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> has been changed by an administrator.

Your new password is: <?php echo StringUtil::encodeHTML($this->v[\'password\']); ?>

Yours truly,
The <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> Team';
$this->items[$this->languageID]['wcf.acp.user.newPassword.mail.subject'] = 'New password for your account at {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.acp.user.newPassword.mail.subject'] = 'New password for your account at <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.acp.user.sendActivationMail'] = 'Send activation e-mail to users';
$this->items[$this->languageID]['wcf.acp.user.sendNewPassword'] = 'Send new password to users';
$this->items[$this->languageID]['wcf.acp.user.unban.success'] = 'The ban of the users has been removed successfully.';
$this->items[$this->languageID]['wcf.acp.user.disableSignature'] = 'Disable signature';
$this->items[$this->languageID]['wcf.acp.user.disableSignatureReason'] = 'Reason';
$this->items[$this->languageID]['wcf.acp.user.button.sendPM'] = 'Send private message';
$this->items[$this->languageID]['wcf.acp.user.sendPM'] = 'Send private message to user';
$this->items[$this->languageID]['wcf.acp.user.sendPM.all'] = 'Send private message to all users';
$this->items[$this->languageID]['wcf.acp.user.sendPM.group'] = 'Send private message to group members';
$this->items[$this->languageID]['wcf.acp.user.sendPM.groups'] = 'Send private message to members of the following user groups';
$this->items[$this->languageID]['wcf.acp.user.sendPM.markedUsers'] = 'Send private message to the following users';
$this->items[$this->languageID]['wcf.acp.user.sendPM.message'] = 'Message';
$this->items[$this->languageID]['wcf.acp.user.sendPM.success'] = 'The message has been send successfully.';
?>