<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wbb.header
* generated at Tue, 13 Aug 2013 11:36:41 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wbb.header.login.useCookies'] = 'Remember me?';
$this->items[$this->languageID]['wbb.header.menu.board'] = 'Forum';
$this->items[$this->languageID]['wbb.header.search.extended'] = 'Advanced Search';
$this->items[$this->languageID]['wbb.header.search.query'] = 'Enter search word';
$this->items[$this->languageID]['wbb.header.userMenu.acp'] = 'Administration';
$this->items[$this->languageID]['wbb.header.userMenu.changeLanguage'] = 'Change Language';
$this->items[$this->languageID]['wbb.header.userMenu.login'] = 'Login';
$this->items[$this->languageID]['wbb.header.userMenu.logout'] = 'Logout';
$this->items[$this->languageID]['wbb.header.userMenu.moderation'] = 'Moderation';
$this->items[$this->languageID]['wbb.header.userMenu.pm'] = 'Private Messages';
$this->items[$this->languageID]['wbb.header.userMenu.profile'] = 'Edit Profile';
$this->items[$this->languageID]['wbb.header.userMenu.register'] = 'Register';
$this->items[$this->languageID]['wbb.header.userMenu.subscriptions'] = 'Favorites';
$this->items[$this->languageID]['wbb.header.userMenu.userGroupLeader'] = 'Group Leader';
$this->items[$this->languageID]['wbb.header.userNote.guest'] = 'You are not logged in.';
$this->items[$this->languageID]['wbb.header.userNote.user'] = 'Welcome <a href="index.php?page=User&amp;userID={@$this->user->userID}{@SID_ARG_2ND}">{$this->user->username}</a>.';
$this->dynamicItems[$this->languageID]['wbb.header.userNote.user'] = 'Welcome <a href="index.php?page=User&amp;userID=<?php echo $this->v[\'this\']->user->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v[\'this\']->user->username); ?></a>.';
$this->items[$this->languageID]['wbb.header.welcomeBack'] = 'Welcome back, {$this->user->username}! <a href="index.php?form=Search&amp;action=newPostsSince&amp;since={@$this->user->boardLastActivityTime}{@SID_ARG_2ND}">Show new posts since your last visit ({@$this->user->boardLastActivityTime|time}).</a>';
$this->dynamicItems[$this->languageID]['wbb.header.welcomeBack'] = '<?php
if (!isset($this->pluginObjects[\'TemplatePluginModifierTime\'])) {
require_once(WCF_DIR.\'lib/system/template/plugin/TemplatePluginModifierTime.class.php\');
$this->pluginObjects[\'TemplatePluginModifierTime\'] = new TemplatePluginModifierTime;
}
?>Welcome back, <?php echo StringUtil::encodeHTML($this->v[\'this\']->user->username); ?>! <a href="index.php?form=Search&amp;action=newPostsSince&amp;since=<?php echo $this->v[\'this\']->user->boardLastActivityTime; ?><?php echo SID_ARG_2ND; ?>">Show new posts since your last visit (<?php echo $this->pluginObjects[\'TemplatePluginModifierTime\']->execute(array($this->v[\'this\']->user->boardLastActivityTime), $this); ?>).</a>';
?>