<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.header.menu
* generated at Tue, 13 Aug 2013 11:36:42 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.header.menu.help'] = 'Help';
$this->items[$this->languageID]['wcf.header.menu.memberslist'] = 'Members';
$this->items[$this->languageID]['wcf.header.menu.contact'] = 'Contact';
?>