<?php
/**
* WoltLab Community Framework
* language: en
* encoding: UTF-8
* category: wcf.user.whitelist
* generated at Tue, 13 Aug 2013 11:36:41 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.whitelist.accept'] = 'Accept the friendship offer by this user';
$this->items[$this->languageID]['wcf.user.whitelist.accept.success'] = 'The friendship offer by &quot;{$user}&quot; has been successfully accepted.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.accept.success'] = 'The friendship offer by &quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&quot; has been successfully accepted.';
$this->items[$this->languageID]['wcf.user.whitelist.accept.sure'] = 'Do you really want to accept the friendship offer by &quot;{$member->username}&quot;?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.accept.sure'] = 'Do you really want to accept the friendship offer by &quot;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&quot;?';
$this->items[$this->languageID]['wcf.user.whitelist.add.success'] = '{if $addedUsers|count == 1}&quot;{$addedUsers|array_shift}&quot; has{else}{implode from=$addedUsers item=user}&quot;{$user}&quot;{/implode} have{/if} been successfully added to your friend list.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.add.success'] = '<?php if (count($this->v[\'addedUsers\']) == 1) { ?>&quot;<?php echo StringUtil::encodeHTML(array_shift($this->v[\'addedUsers\'])); ?>&quot; has<?php } else { ?><?php
$_lengtha257b417abbafed18659f8d1908e596d19f7b252 = count($this->v[\'addedUsers\']);
$_ia257b417abbafed18659f8d1908e596d19f7b252 = 0;
foreach ($this->v[\'addedUsers\'] as $this->v[\'user\']) { ?>&quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&quot;<?php
if (++$_ia257b417abbafed18659f8d1908e596d19f7b252 < $_lengtha257b417abbafed18659f8d1908e596d19f7b252) { echo \', \'; }
} ?> have<?php } ?> been successfully added to your friend list.';
$this->items[$this->languageID]['wcf.user.whitelist.cancel'] = 'Cancel the friendship offer by this user?';
$this->items[$this->languageID]['wcf.user.whitelist.cancel.success'] = 'Your friendship offer for &quot;{$user}&quot; has been successfully cancelled.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.cancel.success'] = 'Your friendship offer for &quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&quot; has been successfully cancelled.';
$this->items[$this->languageID]['wcf.user.whitelist.cancel.sure'] = 'Do you really want to cancel your friendship offer for &raquo;{$member->username}&laquo;?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.cancel.sure'] = 'Do you really want to cancel your friendship offer for &raquo;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&laquo;?';
$this->items[$this->languageID]['wcf.user.whitelist.decline'] = 'Decline the friendship offer?';
$this->items[$this->languageID]['wcf.user.whitelist.decline.success'] = 'The friendship offer by &quot;{$user}&quot; has been declined.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.decline.success'] = 'The friendship offer by &quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&quot; has been declined.';
$this->items[$this->languageID]['wcf.user.whitelist.decline.sure'] = 'Do you really want to decline the friendship with &quot;{$member->username}&quot;?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.decline.sure'] = 'Do you really want to decline the friendship with &quot;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&quot;?';
$this->items[$this->languageID]['wcf.user.whitelist.empty'] = 'Empty friends list';
$this->items[$this->languageID]['wcf.user.whitelist.empty.sure'] = 'Are you sure you want to empty your complete friends list?';
$this->items[$this->languageID]['wcf.user.whitelist.error.username.canNotAddYourself'] = 'You cannot add yourself to your friends list.';
$this->items[$this->languageID]['wcf.user.whitelist.error.username.userDoesNotAllowFriendshipOfferings'] = 'User &quot;{$error.username}&quot; does not accept any friendship offers.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.error.username.userDoesNotAllowFriendshipOfferings'] = 'User &quot;<?php echo StringUtil::encodeHTML($this->v[\'error\'][\'username\']); ?>&quot; does not accept any friendship offers.';
$this->items[$this->languageID]['wcf.user.whitelist.invitedMembers'] = 'Sent friendship offers';
$this->items[$this->languageID]['wcf.user.whitelist.invitingMembers'] = 'Received friendship offers';
$this->items[$this->languageID]['wcf.user.whitelist.members'] = '{#$members|count} user(s) on your friend list';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.members'] = '<?php echo StringUtil::formatNumeric(count($this->v[\'members\'])); ?> user(s) on your friend list';
$this->items[$this->languageID]['wcf.user.whitelist.notification'] = '{if $this->user->getInvitations()|count == 1}The following user would like to add you to his friends list:{else}The following users would like to add you to their friends list:{/if}';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.notification'] = '<?php if (count($this->v[\'this\']->user->getInvitations()) == 1) { ?>The following user would like to add you to his friends list:<?php } else { ?>The following users would like to add you to their friends list:<?php } ?>';
$this->items[$this->languageID]['wcf.user.whitelist.notification.cancel'] = 'Cancel notification';
$this->items[$this->languageID]['wcf.user.whitelist.offer.success'] = 'You have offered your friendship to {if $invitedUsers|count == 1}&quot;{$invitedUsers|array_shift}&quot;{else}the following users {implode from=$invitedUsers item=user}&quot;{$user}&quot;{/implode} {/if}.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.offer.success'] = 'You have offered your friendship to <?php if (count($this->v[\'invitedUsers\']) == 1) { ?>&quot;<?php echo StringUtil::encodeHTML(array_shift($this->v[\'invitedUsers\'])); ?>&quot;<?php } else { ?>the following users <?php
$_lengthe694998e72a7412941f89d6328316fcdbd62d8c8 = count($this->v[\'invitedUsers\']);
$_ie694998e72a7412941f89d6328316fcdbd62d8c8 = 0;
foreach ($this->v[\'invitedUsers\'] as $this->v[\'user\']) { ?>&quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&quot;<?php
if (++$_ie694998e72a7412941f89d6328316fcdbd62d8c8 < $_lengthe694998e72a7412941f89d6328316fcdbd62d8c8) { echo \', \'; }
} ?> <?php } ?>.';
$this->items[$this->languageID]['wcf.user.whitelist.remove'] = 'Remove this user from your friend list';
$this->items[$this->languageID]['wcf.user.whitelist.remove.success'] = '&quot;{$user}&quot; has been successfully removed from your friend list.';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.remove.success'] = '&quot;<?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>&quot; has been successfully removed from your friend list.';
$this->items[$this->languageID]['wcf.user.whitelist.remove.sure'] = 'Do you really want to cancel the friendship offer for &raquo;{$member->username}&laquo;?';
$this->dynamicItems[$this->languageID]['wcf.user.whitelist.remove.sure'] = 'Do you really want to cancel the friendship offer for &raquo;<?php echo StringUtil::encodeHTML($this->v[\'member\']->username); ?>&laquo;?';
$this->items[$this->languageID]['wcf.user.whitelist.title'] = 'Friend list';
$this->items[$this->languageID]['wcf.user.whitelist.username'] = 'Add the following user to your friend list';
$this->items[$this->languageID]['wcf.user.whitelist.username.description'] = 'Please enter the name of the user(s) you want to add to your friend list (comma separated).';
$this->items[$this->languageID]['wcf.user.whitelist.declineAll'] = 'Decline all';
$this->items[$this->languageID]['wcf.user.whitelist.acceptAll'] = 'Accept all';
$this->items[$this->languageID]['wcf.user.whitelist.declineAll.sure'] = 'Do you really want to decline all friendship offers?';
$this->items[$this->languageID]['wcf.user.whitelist.acceptAll.sure'] = 'Do you really want to accept all friendship offers?';
?>