<?php
/**
* WoltLab Community Framework
* language: it
* encoding: UTF-8
* category: wcf.user.register
* generated at Thu, 15 Aug 2013 01:21:50 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.user.register.activation'] = 'Attiva account';
$this->items[$this->languageID]['wcf.user.register.activation.code'] = 'Codice attivazione di 9 caratteri';
$this->items[$this->languageID]['wcf.user.register.activation.error.code.notValid'] = 'Avete inserito un codice di attivazione non valido. <a href="index.php?page=Register&amp;action={if $action == \'activate\'}newActivationCode{else}newReactivationCode{/if}{@SID_ARG_2ND}">Clicca qui</a> per ricevere un nuovo codice di attivazione.';
$this->dynamicItems[$this->languageID]['wcf.user.register.activation.error.code.notValid'] = 'Avete inserito un codice di attivazione non valido. <a href="index.php?page=Register&amp;action=<?php if ($this->v[\'action\'] == \'activate\') { ?>newActivationCode<?php } else { ?>newReactivationCode<?php } ?><?php echo SID_ARG_2ND; ?>">Clicca qui</a> per ricevere un nuovo codice di attivazione.';
$this->items[$this->languageID]['wcf.user.register.activation.error.userID.notValid'] = 'Avete inserito un user id non valido.';
$this->items[$this->languageID]['wcf.user.register.activation.redirect'] = 'Il vostro account utente è stato attivato con successo. Potete ora loggarvi con i vostri dati.';
$this->items[$this->languageID]['wcf.user.register.activation.userID'] = 'User id';
$this->items[$this->languageID]['wcf.user.register.awaitActivation'] = 'Grazie {$username} per esserti registrato. I dati del tuo account saranno controllati al più presto da un amministratore.<br />Appena l\'account sarà attivato, riceverete una E-Mail di notifica.';
$this->dynamicItems[$this->languageID]['wcf.user.register.awaitActivation'] = 'Grazie <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?> per esserti registrato. I dati del tuo account saranno controllati al più presto da un amministratore.<br />Appena l\'account sarà attivato, riceverete una E-Mail di notifica.';
$this->items[$this->languageID]['wcf.user.register.confirmEmail.description'] = 'Prego confermare il vostro indirizzo E-Mail!';
$this->items[$this->languageID]['wcf.user.register.confirmPassword.description'] = 'Prego confermare la vostra password!';
$this->items[$this->languageID]['wcf.user.register.disclaimer'] = '<div align="justify"> <p>La registrazione e l\'uso del presente forum sono gratuiti.<br/>Dopo aver letto il presente testo cliccare su &quot;Accetto&quot; per proseguire con la registrazione, altrimenti su &quot;Rifiuto&quot; per tornare alla Home Page del forum.<br/><strong>Solo se accettate</strong> le regole qui di seguito elencate sarà possibile proseguire con la registrazione ed interagire in modo completo con il resto della comunità.</p>
				
<p>Anche se gli Amministratori e Moderatori di {lang}{PAGE_TITLE}{/lang} possono cancellare o modificare tutti i post indesiderati, risulta impossibile per essi controllare tutti gli interventi.<br/>&Egrave; possibile che qualcuno di questi possa sfuggire al loro controllo.<br/>Tutti i Post esprimono le opinioni dei loro autori, i proprietari di {lang}{PAGE_TITLE}{/lang} e WoltLab GmbH (sviluppatori del presente pacchetto software, la Burning Board) non possono essere ritenuti responsabili del contenuto di essi (testo dei messaggi, sondaggi o allegati che siano).</p>

<p>Procedendo con la registrazione, accetti di non postare <em>messaggi volgari, maleducati, irriverenti o che  esprimono visioni politiche o di legge di qualsiasi calibro. Accetti di non postare messaggi che incitano alla violenza (verso persone, animali o cose), messaggi riportanti forme di pornografia o pedofilia, o contenuti riportanti meteriale legato alla pirateria informatica</em>.</p>

<p>Procedendo con la registrazione, accetti di non scatenare liti fra utenti di questo forum. Ognuno possiede il sacrosanto diritto di espressione, ovviamente nei limiti umani dell\'educazione.</p>

<p>Procedendo con la registrazione, accetti che il compito di moderare gestire questo forum spetta esclusivamente ai moderatori e amministratori di questo forum.<br/>Potrai però denunciare agli amministratori o moderatori eventuali post con contenuti scorretti, illegali o contenuti espressi nei punti precedenti.<br/>Potrai inoltre notificare, agli stessi amministratori o moderatori, presenze di bug o errori nel fuzionamento del presente pacchetto software.</p>

<p>In aggiunta, gli amministratori e moderatori di questa board potranno decidere di modificare o cancellare interamente il tuo account per qualsiasi ragione e senza darne avviso alcuno qualora lo ritengano opportuno.</p>

<p>Buona permanenza su {lang}{PAGE_TITLE}{/lang}!</p></div>';
$this->dynamicItems[$this->languageID]['wcf.user.register.disclaimer'] = '<div align="justify"> <p>La registrazione e l\'uso del presente forum sono gratuiti.<br/>Dopo aver letto il presente testo cliccare su &quot;Accetto&quot; per proseguire con la registrazione, altrimenti su &quot;Rifiuto&quot; per tornare alla Home Page del forum.<br/><strong>Solo se accettate</strong> le regole qui di seguito elencate sarà possibile proseguire con la registrazione ed interagire in modo completo con il resto della comunità.</p>
				
<p>Anche se gli Amministratori e Moderatori di <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang75c0f70b560dd22561fb4982a05b6e93d2b684e8 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang75c0f70b560dd22561fb4982a05b6e93d2b684e8, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> possono cancellare o modificare tutti i post indesiderati, risulta impossibile per essi controllare tutti gli interventi.<br/>&Egrave; possibile che qualcuno di questi possa sfuggire al loro controllo.<br/>Tutti i Post esprimono le opinioni dei loro autori, i proprietari di <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang94095c605680aae023f9d496fed138bc779dda79 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang94095c605680aae023f9d496fed138bc779dda79, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> e WoltLab GmbH (sviluppatori del presente pacchetto software, la Burning Board) non possono essere ritenuti responsabili del contenuto di essi (testo dei messaggi, sondaggi o allegati che siano).</p>

<p>Procedendo con la registrazione, accetti di non postare <em>messaggi volgari, maleducati, irriverenti o che  esprimono visioni politiche o di legge di qualsiasi calibro. Accetti di non postare messaggi che incitano alla violenza (verso persone, animali o cose), messaggi riportanti forme di pornografia o pedofilia, o contenuti riportanti meteriale legato alla pirateria informatica</em>.</p>

<p>Procedendo con la registrazione, accetti di non scatenare liti fra utenti di questo forum. Ognuno possiede il sacrosanto diritto di espressione, ovviamente nei limiti umani dell\'educazione.</p>

<p>Procedendo con la registrazione, accetti che il compito di moderare gestire questo forum spetta esclusivamente ai moderatori e amministratori di questo forum.<br/>Potrai però denunciare agli amministratori o moderatori eventuali post con contenuti scorretti, illegali o contenuti espressi nei punti precedenti.<br/>Potrai inoltre notificare, agli stessi amministratori o moderatori, presenze di bug o errori nel fuzionamento del presente pacchetto software.</p>

<p>In aggiunta, gli amministratori e moderatori di questa board potranno decidere di modificare o cancellare interamente il tuo account per qualsiasi ragione e senza darne avviso alcuno qualora lo ritengano opportuno.</p>

<p>Buona permanenza su <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langc5bb4f969cfec5ff14a3914fb089779bedc3b069 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langc5bb4f969cfec5ff14a3914fb089779bedc3b069, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>!</p></div>';
$this->items[$this->languageID]['wcf.user.register.disclaimer.button.accept'] = 'Accetto';
$this->items[$this->languageID]['wcf.user.register.disclaimer.button.decline'] = 'Rifiuto';
$this->items[$this->languageID]['wcf.user.register.disclaimer.title'] = 'Avvertenze';
$this->items[$this->languageID]['wcf.user.register.email.description'] = 'Prego inserire il vostro indirizzo E-Mail!';
$this->items[$this->languageID]['wcf.user.register.error.disabled'] = 'La registrazione è al momento non disponibile.';
$this->items[$this->languageID]['wcf.user.register.error.userAlreadyEnabled'] = 'Questo utente risulta essere già abilitato.';
$this->items[$this->languageID]['wcf.user.register.invitation'] = 'Registrati ora!';
$this->items[$this->languageID]['wcf.user.register.needActivation'] = 'Grazie {$username} per esserti registrato. Riceverai una E-Mail all\'indirizzo {$email} con il riepilogo dei dati del tuo account.<br />
Per completare la registrazione seguite i passi indicati nell\'E-Mail inviatavi.';
$this->dynamicItems[$this->languageID]['wcf.user.register.needActivation'] = 'Grazie <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?> per esserti registrato. Riceverai una E-Mail all\'indirizzo <?php echo StringUtil::encodeHTML($this->v[\'email\']); ?> con il riepilogo dei dati del tuo account.<br />
Per completare la registrazione seguite i passi indicati nell\'E-Mail inviatavi.';
$this->items[$this->languageID]['wcf.user.register.needActivation.mail'] = 'Gentile {$username},

Grazie per esserti registrato su {PAGE_TITLE}.
Per attivare la vostra registrazione dovete seguire i passi che seguono.

Cliccare sul seguente link per terminare la registrazione:
{PAGE_URL}/index.php?page=Register&action=a&u={$userID}&a={$activationCode}

**** Link non funzionante? ****
Se il link non funziona dovete aprire il vostro browser e visitare il seguente indirizzo
{PAGE_URL}/index.php?page=Register&action=a

Assicurarsi che nell\'indirizzo appena indicato non vi siano spazi.
Inserire poi nella pagina che verrà visualizzata i seguenti dati

User id: 			    {$userID}
Codice attivazione: 	{$activationCode}

Se non sei stato tu a registrarti su {PAGE_TITLE} ignorate questa E-Mail.

Se riscontri altri problemi con l\'attivazione contatta un membro del nostro Team.
-> {MAIL_ADMIN_ADDRESS}

Arrivederci,
Il team di {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.register.needActivation.mail'] = 'Gentile <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?>,

Grazie per esserti registrato su <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>.
Per attivare la vostra registrazione dovete seguire i passi che seguono.

Cliccare sul seguente link per terminare la registrazione:
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?page=Register&action=a&u=<?php echo StringUtil::encodeHTML($this->v[\'userID\']); ?>&a=<?php echo StringUtil::encodeHTML($this->v[\'activationCode\']); ?>

**** Link non funzionante? ****
Se il link non funziona dovete aprire il vostro browser e visitare il seguente indirizzo
<?php echo StringUtil::encodeHTML(PAGE_URL); ?>/index.php?page=Register&action=a

Assicurarsi che nell\'indirizzo appena indicato non vi siano spazi.
Inserire poi nella pagina che verrà visualizzata i seguenti dati

User id: 			    <?php echo StringUtil::encodeHTML($this->v[\'userID\']); ?>
Codice attivazione: 	<?php echo StringUtil::encodeHTML($this->v[\'activationCode\']); ?>

Se non sei stato tu a registrarti su <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?> ignorate questa E-Mail.

Se riscontri altri problemi con l\'attivazione contatta un membro del nostro Team.
-> <?php echo StringUtil::encodeHTML(MAIL_ADMIN_ADDRESS); ?>

Arrivederci,
Il team di <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.register.needActivation.mail.subject'] = 'Attivazione registrazione su {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.register.needActivation.mail.subject'] = 'Attivazione registrazione su <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.register.needsActivation'] = 'Il vostro account utente non è ancora attivo. Per poter utilizzare tutte le funzioni di questo software dovete provvedere all&rsquo;<a href="index.php?page=Register&amp;action=enable{@SID_ARG_2ND}">attivazione dell&rsquo;account</a>. Seguite la procedura indicata nella E-Mail che vi è stata appena inviata.';
$this->dynamicItems[$this->languageID]['wcf.user.register.needsActivation'] = 'Il vostro account utente non è ancora attivo. Per poter utilizzare tutte le funzioni di questo software dovete provvedere all&rsquo;<a href="index.php?page=Register&amp;action=enable<?php echo SID_ARG_2ND; ?>">attivazione dell&rsquo;account</a>. Seguite la procedura indicata nella E-Mail che vi è stata appena inviata.';
$this->items[$this->languageID]['wcf.user.register.newActivationCode'] = 'Richedi nuovo codice di attivazione';
$this->items[$this->languageID]['wcf.user.register.newActivationCode.email.description'] = 'Potete registrare qui un nuovo indirizzo E-Mail nel quale sar&aacute; inviato il nuovo codice di attivazione. Lasciare vuoto questo campo se volete ricevere il codice di attivazione nella casella email indicata in precedenza.';
$this->items[$this->languageID]['wcf.user.register.newActivationCode.success'] = '&Egrave; stata inviata una nuova E-Mail contenente un nuovo codice di attivazione all\'indirizzo {$email}.';
$this->dynamicItems[$this->languageID]['wcf.user.register.newActivationCode.success'] = '&Egrave; stata inviata una nuova E-Mail contenente un nuovo codice di attivazione all\'indirizzo <?php echo StringUtil::encodeHTML($this->v[\'email\']); ?>.';
$this->items[$this->languageID]['wcf.user.register.notification.mail'] = 'Gentile Amministratore,

l\'utente {$username} si è registrato su {PAGE_TITLE}.';
$this->dynamicItems[$this->languageID]['wcf.user.register.notification.mail'] = 'Gentile Amministratore,

l\'utente <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?> si è registrato su <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>.';
$this->items[$this->languageID]['wcf.user.register.notification.mail.subject'] = 'Nuova registrazione su {PAGE_TITLE}';
$this->dynamicItems[$this->languageID]['wcf.user.register.notification.mail.subject'] = 'Nuova registrazione su <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?>';
$this->items[$this->languageID]['wcf.user.register.password.description'] = 'Una password sicura deve contenere almeno {if REGISTER_PASSWORD_MIN_LENGTH}{REGISTER_PASSWORD_MIN_LENGTH}{else}8{/if} caratteri.';
$this->dynamicItems[$this->languageID]['wcf.user.register.password.description'] = 'Una password sicura deve contenere almeno <?php if (REGISTER_PASSWORD_MIN_LENGTH) { ?><?php echo StringUtil::encodeHTML(REGISTER_PASSWORD_MIN_LENGTH); ?><?php } else { ?>8<?php } ?> caratteri.';
$this->items[$this->languageID]['wcf.user.register.success'] = 'Grazie {$username} per esserti registrato. Il processo di registrazione è concluso.';
$this->dynamicItems[$this->languageID]['wcf.user.register.success'] = 'Grazie <?php echo StringUtil::encodeHTML($this->v[\'username\']); ?> per esserti registrato. Il processo di registrazione è concluso.';
$this->items[$this->languageID]['wcf.user.register.title'] = 'Registrazione';
$this->items[$this->languageID]['wcf.user.register.username.description'] = 'L\'username deve essere composto da un minimo di {REGISTER_USERNAME_MIN_LENGTH} ed un massimo di {REGISTER_USERNAME_MAX_LENGTH} caratteri.';
$this->dynamicItems[$this->languageID]['wcf.user.register.username.description'] = 'L\'username deve essere composto da un minimo di <?php echo StringUtil::encodeHTML(REGISTER_USERNAME_MIN_LENGTH); ?> ed un massimo di <?php echo StringUtil::encodeHTML(REGISTER_USERNAME_MAX_LENGTH); ?> caratteri.';
$this->items[$this->languageID]['wcf.user.register.welcome'] = 'Gentile visitatore,<br />Benvenuto su {lang}{PAGE_TITLE}{/lang}. Se questa è la tua prima visita, ti chiediamo di leggere la sezione <a href="index.php?page=Help{@SID_ARG_2ND}">Aiuto</a>. Questa guida ti spiegherà il funzionamento di questa pagina. Prima di poter utilizzare tutte le funzioni di questo software dovrai registrarti. Usa la <a href="index.php?page=Register{@SID_ARG_2ND}">form di registrazione</a> per registrarti adesso, oppure <a href="index.php?page=Help&amp;item=user.login{@SID_ARG_2ND}">visualizza maggiori informazioni</a> sul processo di registrazione. Se sei già un utente registrato, allora dovrai solamente procedere con il <a href="index.php?form=UserLogin{@SID_ARG_2ND}">login da qui</a>.';
$this->dynamicItems[$this->languageID]['wcf.user.register.welcome'] = 'Gentile visitatore,<br />Benvenuto su <?php $this->tagStack[] = array(\'lang\', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang31382d726da04df7395e697523ff2c3569f3de58 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang31382d726da04df7395e697523ff2c3569f3de58, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>. Se questa è la tua prima visita, ti chiediamo di leggere la sezione <a href="index.php?page=Help<?php echo SID_ARG_2ND; ?>">Aiuto</a>. Questa guida ti spiegherà il funzionamento di questa pagina. Prima di poter utilizzare tutte le funzioni di questo software dovrai registrarti. Usa la <a href="index.php?page=Register<?php echo SID_ARG_2ND; ?>">form di registrazione</a> per registrarti adesso, oppure <a href="index.php?page=Help&amp;item=user.login<?php echo SID_ARG_2ND; ?>">visualizza maggiori informazioni</a> sul processo di registrazione. Se sei già un utente registrato, allora dovrai solamente procedere con il <a href="index.php?form=UserLogin<?php echo SID_ARG_2ND; ?>">login da qui</a>.';
?>