<?php
/**
* WoltLab Community Framework
* language: it
* encoding: UTF-8
* category: wcf.tagging
* generated at Thu, 15 Aug 2013 01:21:50 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.tagging.filter'] = 'Filtro per tag{if $tag|isset}: &quot;{$tag}&quot;{/if}';
$this->dynamicItems[$this->languageID]['wcf.tagging.filter'] = 'Filtro per tag<?php if (isset($this->v[\'tag\'])) { ?>: &quot;<?php echo StringUtil::encodeHTML($this->v[\'tag\']); ?>&quot;<?php } ?>';
$this->items[$this->languageID]['wcf.tagging.tags'] = 'Tags';
$this->items[$this->languageID]['wcf.tagging.tags.add'] = 'Tags';
$this->items[$this->languageID]['wcf.tagging.tags.add.description'] = 'Piu tags devono essere separati da una virgola.';
$this->items[$this->languageID]['wcf.tagging.tags.used'] = 'Tags usati';
$this->items[$this->languageID]['wcf.tagging.by'] = 'Da';
$this->items[$this->languageID]['wcf.tagging.mostPopular'] = 'Tag più popolariMost popular tags';
$this->items[$this->languageID]['wcf.tagging.overview'] = 'Dettagli';
$this->items[$this->languageID]['wcf.tagging.title'] = 'Risultati per &quot;{$tagObj->getName()}&quot;';
$this->dynamicItems[$this->languageID]['wcf.tagging.title'] = 'Risultati per &quot;<?php echo StringUtil::encodeHTML($this->v[\'tagObj\']->getName()); ?>&quot;';
$this->items[$this->languageID]['wcf.tagging.taggable.all.com.woltlab.wbb.thread'] = 'Tutti i threads';
$this->items[$this->languageID]['wcf.tagging.taggable.com.woltlab.wbb.thread'] = 'Threads';
?>