<?php
/**
* WoltLab Community Framework
* language: it
* encoding: UTF-8
* category: wcf.global
* generated at Thu, 15 Aug 2013 01:21:49 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.global.button.back'] = '&laquo; Indietro';
$this->items[$this->languageID]['wcf.global.button.close'] = 'Chiudi';
$this->items[$this->languageID]['wcf.global.button.collapse'] = 'Collapse';
$this->items[$this->languageID]['wcf.global.button.collapsible'] = 'Expand or collapse';
$this->items[$this->languageID]['wcf.global.button.delete'] = 'Cancella';
$this->items[$this->languageID]['wcf.global.button.delete.confirm'] = 'Siete sicuro di voler cancellare questo dato?';
$this->items[$this->languageID]['wcf.global.button.deleteCompletely'] = 'Cancella completamente';
$this->items[$this->languageID]['wcf.global.button.edit'] = 'Modifica';
$this->items[$this->languageID]['wcf.global.button.editor.jump'] = 'Use full editor';
$this->items[$this->languageID]['wcf.global.button.expand'] = 'Expand';
$this->items[$this->languageID]['wcf.global.button.mark'] = 'Seleziona';
$this->items[$this->languageID]['wcf.global.button.next'] = 'Avanti &raquo;';
$this->items[$this->languageID]['wcf.global.button.preview'] = 'Anteprima';
$this->items[$this->languageID]['wcf.global.button.reset'] = 'Reimposta';
$this->items[$this->languageID]['wcf.global.button.submit'] = 'Invia';
$this->items[$this->languageID]['wcf.global.button.unmark'] = 'Deseleziona';
$this->items[$this->languageID]['wcf.global.date.day'] = 'Giorno';
$this->items[$this->languageID]['wcf.global.date.days'] = 'Giorni';
$this->items[$this->languageID]['wcf.global.date.hour'] = 'Ora';
$this->items[$this->languageID]['wcf.global.date.hours'] = 'Ore';
$this->items[$this->languageID]['wcf.global.date.minute'] = 'Minuto';
$this->items[$this->languageID]['wcf.global.date.minutes'] = 'Minuti';
$this->items[$this->languageID]['wcf.global.date.month'] = 'Mese';
$this->items[$this->languageID]['wcf.global.date.months'] = 'Mesi';
$this->items[$this->languageID]['wcf.global.date.second'] = 'Secondo';
$this->items[$this->languageID]['wcf.global.date.seconds'] = 'Secondi';
$this->items[$this->languageID]['wcf.global.date.week'] = 'Settimana';
$this->items[$this->languageID]['wcf.global.date.weeks'] = 'Settimane';
$this->items[$this->languageID]['wcf.global.date.year'] = 'Anno';
$this->items[$this->languageID]['wcf.global.date.year.notRequired'] = 'Specificare l\'anno di nascita non è obbligatorio.';
$this->items[$this->languageID]['wcf.global.date.years'] = 'Years';
$this->items[$this->languageID]['wcf.global.dateFormat'] = '%d.%m.%Y';
$this->items[$this->languageID]['wcf.global.dateFormatLocalized'] = '%e. %B %Y';
$this->items[$this->languageID]['wcf.global.dateFormatToday'] = '<b>Oggi</b>, %H:%M';
$this->items[$this->languageID]['wcf.global.dateFormatYesterday'] = 'Ieri,  %H:%M';
$this->items[$this->languageID]['wcf.global.dateInputOrder'] = 'day-month-year';
$this->items[$this->languageID]['wcf.global.dateMethod'] = 'strftime';
$this->items[$this->languageID]['wcf.global.decimalPoint'] = ',';
$this->items[$this->languageID]['wcf.global.defaultValue'] = 'Predefinito';
$this->items[$this->languageID]['wcf.global.error.backward'] = 'Torna alla pagina precedente';
$this->items[$this->languageID]['wcf.global.error.empty'] = 'Prego inserire le informazioni richieste da questo campo.';
$this->items[$this->languageID]['wcf.global.error.file.notFound'] = 'Impossibile trovare il file.';
$this->items[$this->languageID]['wcf.global.error.illegalLink'] = 'Il link che cercate di visualizzare non è disponibile oppure non è valido.';
$this->items[$this->languageID]['wcf.global.error.permissionDenied'] = 'Non siete abilitato alla visualizzazione di questa pagina. Non avete i permessi per visualizzarla.';
$this->items[$this->languageID]['wcf.global.error.permissionDenied.title'] = 'Non siete abilitato a visitare questa pagina.';
$this->items[$this->languageID]['wcf.global.error.title'] = 'Messaggio di errore';
$this->items[$this->languageID]['wcf.global.form.error'] = 'I dati inseriti non sono validi. Prego controllare i dati nei campi indicati in rosso.';
$this->items[$this->languageID]['wcf.global.language.ar'] = 'Arabo';
$this->items[$this->languageID]['wcf.global.language.bs'] = 'Bosniaco';
$this->items[$this->languageID]['wcf.global.language.cs'] = 'Ceco';
$this->items[$this->languageID]['wcf.global.language.da'] = 'Danese';
$this->items[$this->languageID]['wcf.global.language.de'] = 'Tedesco';
$this->items[$this->languageID]['wcf.global.language.de-informal'] = 'Tedesco (Informale)';
$this->items[$this->languageID]['wcf.global.language.el'] = 'Greco';
$this->items[$this->languageID]['wcf.global.language.en'] = 'Inglese';
$this->items[$this->languageID]['wcf.global.language.es'] = 'Spagnolo';
$this->items[$this->languageID]['wcf.global.language.fa'] = 'Persiano';
$this->items[$this->languageID]['wcf.global.language.fi'] = 'Finlandese';
$this->items[$this->languageID]['wcf.global.language.fr'] = 'Francese';
$this->items[$this->languageID]['wcf.global.language.he'] = 'Ebraico';
$this->items[$this->languageID]['wcf.global.language.hr'] = 'Croato';
$this->items[$this->languageID]['wcf.global.language.hu'] = 'Ungherese';
$this->items[$this->languageID]['wcf.global.language.it'] = 'Italiano';
$this->items[$this->languageID]['wcf.global.language.ja'] = 'Giapponese';
$this->items[$this->languageID]['wcf.global.language.ko'] = 'Coreano';
$this->items[$this->languageID]['wcf.global.language.nl'] = 'Olandese';
$this->items[$this->languageID]['wcf.global.language.no'] = 'Norvegese';
$this->items[$this->languageID]['wcf.global.language.pl'] = 'Polacco';
$this->items[$this->languageID]['wcf.global.language.pt'] = 'Portoghese';
$this->items[$this->languageID]['wcf.global.language.pt-BR'] = 'Portuguese (Brazil)';
$this->items[$this->languageID]['wcf.global.language.ro'] = 'Rumeno';
$this->items[$this->languageID]['wcf.global.language.ru'] = 'Russo';
$this->items[$this->languageID]['wcf.global.language.sk'] = 'Slovacco';
$this->items[$this->languageID]['wcf.global.language.sr'] = 'Serbo';
$this->items[$this->languageID]['wcf.global.language.sv'] = 'Svedese';
$this->items[$this->languageID]['wcf.global.language.th'] = 'Thai';
$this->items[$this->languageID]['wcf.global.language.tr'] = 'Turco';
$this->items[$this->languageID]['wcf.global.language.zh-CN'] = 'Cinese (Semplificato)';
$this->items[$this->languageID]['wcf.global.language.zh-TW'] = 'Cinese (Tradizionale)';
$this->items[$this->languageID]['wcf.global.locale.unix'] = 'it_IT';
$this->items[$this->languageID]['wcf.global.locale.win'] = 'italian';
$this->items[$this->languageID]['wcf.global.multiSelect'] = 'Più valori possono essere selezionati usando la combinazione di tasti &quot;Ctrl/Shift&quot; (per Windows) oppure &quot;Command&quot; (per Mac OS) e cliccando sui valori scelti.';
$this->items[$this->languageID]['wcf.global.page.input'] = 'Nella pagina sottostante';
$this->items[$this->languageID]['wcf.global.page.next'] = 'Pagina successiva';
$this->items[$this->languageID]['wcf.global.page.previous'] = 'Pagina precedente';
$this->items[$this->languageID]['wcf.global.pageDirection'] = 'ltr';
$this->items[$this->languageID]['wcf.global.pageTitle'] = 'WoltLab&reg; Community Framework&trade;';
$this->items[$this->languageID]['wcf.global.redirect.title'] = 'Reindirizzamento';
$this->items[$this->languageID]['wcf.global.redirect.url'] = 'Cliccare qui se il reindirizzamento automatico non funziona!';
$this->items[$this->languageID]['wcf.global.scrollUp'] = 'Vai all\'inizio della pagina';
$this->items[$this->languageID]['wcf.global.search.matchesExactly'] = 'Corrispondenza esatta';
$this->items[$this->languageID]['wcf.global.shortTimeFormat'] = '%d.%m.%Y, %H:%M';
$this->items[$this->languageID]['wcf.global.shortTimeFormatLocalized'] = '%e. %B %Y, %H:%M';
$this->items[$this->languageID]['wcf.global.skipToContent'] = 'Skip navigation';
$this->items[$this->languageID]['wcf.global.sortOrder.ascending'] = 'Ascendente';
$this->items[$this->languageID]['wcf.global.sortOrder.descending'] = 'Discendente';
$this->items[$this->languageID]['wcf.global.thousandsSeparator'] = '.';
$this->items[$this->languageID]['wcf.global.timeFormat'] = '%d.%m.%Y, %H:%M';
$this->items[$this->languageID]['wcf.global.timeFormatLocalized'] = '%A, %e. %B %Y, %H:%M';
?>