<?php
/**
* WoltLab Community Framework
* language: it
* encoding: UTF-8
* category: wcf.header.menu
* generated at Thu, 15 Aug 2013 01:21:51 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.header.menu.help'] = 'Aiuto';
$this->items[$this->languageID]['wcf.header.menu.memberslist'] = 'Membri';
?>