<?php
/**
* WoltLab Community Framework
* language: it
* encoding: UTF-8
* category: wcf.usersOnline
* generated at Thu, 15 Aug 2013 01:21:49 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items[$this->languageID]['wcf.usersOnline.location.help'] = '<a href="index.php?page=Help{SID_ARG_2ND}">Aiuto</a>';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.help'] = '<a href="index.php?page=Help<?php echo StringUtil::encodeHTML(SID_ARG_2ND); ?>">Aiuto</a>';
$this->items[$this->languageID]['wcf.usersOnline.location.login'] = 'Login';
$this->items[$this->languageID]['wcf.usersOnline.location.logout'] = 'Logout';
$this->items[$this->languageID]['wcf.usersOnline.location.lostPassword'] = 'Password dimenticata?';
$this->items[$this->languageID]['wcf.usersOnline.location.register'] = 'Registrazione';
$this->items[$this->languageID]['wcf.usersOnline.location.usercp'] = 'Modifica Profilo';
$this->items[$this->languageID]['wcf.usersOnline.location.search'] = '<a href="index.php?form=Search{SID_ARG_2ND}">Ricerca</a>';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.search'] = '<a href="index.php?form=Search<?php echo StringUtil::encodeHTML(SID_ARG_2ND); ?>">Ricerca</a>';
$this->items[$this->languageID]['wcf.usersOnline.location.mail'] = 'Scrive una E-Mail a {$user}';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.mail'] = 'Scrive una E-Mail a <?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>';
$this->items[$this->languageID]['wcf.usersOnline.location.membersList'] = '<a href="index.php?page=MembersList{SID_ARG_2ND}">Lista utenti</a>';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.membersList'] = '<a href="index.php?page=MembersList<?php echo StringUtil::encodeHTML(SID_ARG_2ND); ?>">Lista utenti</a>';
$this->items[$this->languageID]['wcf.usersOnline.location.membersSearch'] = '<a href="index.php?form=MembersSearch{SID_ARG_2ND}">Ricarca per utenti</a>';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.membersSearch'] = '<a href="index.php?form=MembersSearch<?php echo StringUtil::encodeHTML(SID_ARG_2ND); ?>">Ricarca per utenti</a>';
$this->items[$this->languageID]['wcf.usersOnline.location.profile'] = 'Visualizza il profilo di {$user}';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.profile'] = 'Visualizza il profilo di <?php echo StringUtil::encodeHTML($this->v[\'user\']); ?>';
$this->items[$this->languageID]['wcf.usersOnline.location.tagCloud'] = 'Box tag';
$this->items[$this->languageID]['wcf.usersOnline.location.taggedObjects'] = 'Risultati per il tag &quot;{$tag}&quot;';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.taggedObjects'] = 'Risultati per il tag &quot;<?php echo StringUtil::encodeHTML($this->v[\'tag\']); ?>&quot;';
$this->items[$this->languageID]['wcf.usersOnline.location.attachmentList'] = 'List of own attachmenst';
$this->items[$this->languageID]['wcf.usersOnline.location.messenger'] = 'Contatta {$user} attraverso Messenger';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.messenger'] = 'Contatta <?php echo StringUtil::encodeHTML($this->v[\'user\']); ?> attraverso Messenger';
$this->items[$this->languageID]['wcf.usersOnline.guestname'] = 'Nome';
$this->items[$this->languageID]['wcf.usersOnline.guests'] = 'Al momento {if $guests|count == 1}c\'è un Ospite{else}ci sono {#$guests|count} ospiti{/if} Online';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.guests'] = 'Al momento <?php if (count($this->v[\'guests\']) == 1) { ?>c\'è un Ospite<?php } else { ?>ci sono <?php echo StringUtil::formatNumeric(count($this->v[\'guests\'])); ?> ospiti<?php } ?> Online';
$this->items[$this->languageID]['wcf.usersOnline.invisible'] = ' (Invisibile)';
$this->items[$this->languageID]['wcf.usersOnline.ipAddress'] = 'Indirizzo IP';
$this->items[$this->languageID]['wcf.usersOnline.lastActivity'] = 'Ultima attività';
$this->items[$this->languageID]['wcf.usersOnline.location'] = 'Ubicazione';
$this->items[$this->languageID]['wcf.usersOnline.location.usersOnline'] = '<a href="index.php?page=UsersOnline{SID_ARG_2ND}">Chi è Online?</a>';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.usersOnline'] = '<a href="index.php?page=UsersOnline<?php echo StringUtil::encodeHTML(SID_ARG_2ND); ?>">Chi è Online?</a>';
$this->items[$this->languageID]['wcf.usersOnline.marking.friends'] = 'Amici';
$this->items[$this->languageID]['wcf.usersOnline.marking.legend'] = 'Legenda:';
$this->items[$this->languageID]['wcf.usersOnline.members'] = 'Al momento {if $users|count == 1}risulta online un utente registrato{else} risultano online {#$users|count} utenti registrati{/if}';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.members'] = 'Al momento <?php if (count($this->v[\'users\']) == 1) { ?>risulta online un utente registrato<?php } else { ?> risultano online <?php echo StringUtil::formatNumeric(count($this->v[\'users\'])); ?> utenti registrati<?php } ?>';
$this->items[$this->languageID]['wcf.usersOnline.spiderName'] = 'Nome';
$this->items[$this->languageID]['wcf.usersOnline.spiders'] = 'Al momento {if $spiders|count == 1}risulta online una Search-Engine Robot{else}risultano online {#$spiders|count} Search-Engine Robots{/if} ({if $detailedSpiderList}<a href="index.php?page=UsersOnline&amp;sortField={$sortField}&amp;sortOrder={$sortOrder}&amp;detailedSpiderList=0{if $additionalParameters|isset}{@$additionalParameters}{/if}{@SID_ARG_2ND}">Nascondi Dettagli</a>{else}<a href="index.php?page=UsersOnline&amp;sortField={$sortField}&amp;sortOrder={$sortOrder}&amp;detailedSpiderList=1{if $additionalParameters|isset}{@$additionalParameters}{/if}{@SID_ARG_2ND}">Mostra Dettagli</a>{/if})';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.spiders'] = 'Al momento <?php if (count($this->v[\'spiders\']) == 1) { ?>risulta online una Search-Engine Robot<?php } else { ?>risultano online <?php echo StringUtil::formatNumeric(count($this->v[\'spiders\'])); ?> Search-Engine Robots<?php } ?> (<?php if ($this->v[\'detailedSpiderList\']) { ?><a href="index.php?page=UsersOnline&amp;sortField=<?php echo StringUtil::encodeHTML($this->v[\'sortField\']); ?>&amp;sortOrder=<?php echo StringUtil::encodeHTML($this->v[\'sortOrder\']); ?>&amp;detailedSpiderList=0<?php if (isset($this->v[\'additionalParameters\'])) { ?><?php echo $this->v[\'additionalParameters\']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">Nascondi Dettagli</a><?php } else { ?><a href="index.php?page=UsersOnline&amp;sortField=<?php echo StringUtil::encodeHTML($this->v[\'sortField\']); ?>&amp;sortOrder=<?php echo StringUtil::encodeHTML($this->v[\'sortOrder\']); ?>&amp;detailedSpiderList=1<?php if (isset($this->v[\'additionalParameters\'])) { ?><?php echo $this->v[\'additionalParameters\']; ?><?php } ?><?php echo SID_ARG_2ND; ?>">Mostra Dettagli</a><?php } ?>)';
$this->items[$this->languageID]['wcf.usersOnline.title'] = 'Elenco utenti - &quot; Chi è online? &quot;';
$this->items[$this->languageID]['wcf.usersOnline.userAgent'] = 'Browser usato';
$this->items[$this->languageID]['wcf.usersOnline.username'] = 'Username';
$this->items[$this->languageID]['wcf.usersOnline.location.attachment'] = 'Allegato';
$this->items[$this->languageID]['wcf.usersOnline.location.pollOverview'] = 'Dettagli sondaggio';
$this->items[$this->languageID]['wcf.usersOnline.location.pmNew'] = 'Sta creando un nuovo messaggio privato';
$this->items[$this->languageID]['wcf.usersOnline.location.pmView'] = 'Sta leggendo messaggi privati';
$this->items[$this->languageID]['wcf.usersOnline.location.userGroups'] = 'User groups mamagement';
$this->items[$this->languageID]['wcf.usersOnline.location.userWarn'] = 'Segnala utente';
$this->items[$this->languageID]['wcf.usersOnline.location.teamPage'] = '<a href="index.php?page=Team{SID_ARG_2ND}">Utenti del Team</a>';
$this->dynamicItems[$this->languageID]['wcf.usersOnline.location.teamPage'] = '<a href="index.php?page=Team<?php echo StringUtil::encodeHTML(SID_ARG_2ND); ?>">Utenti del Team</a>';
?>