<?php
/**
* WoltLab Community Framework
* Template: attachmentsShow
* Compiled at: Tue, 13 Aug 2013 17:19:32 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'attachmentsShow';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierFilesize'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierFilesize.class.php');
$this->pluginObjects['TemplatePluginModifierFilesize'] = new TemplatePluginModifierFilesize;
}
if (!isset($this->pluginObjects['TemplatePluginModifierShorttime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierShorttime.class.php');
$this->pluginObjects['TemplatePluginModifierShorttime'] = new TemplatePluginModifierShorttime;
}
?><?php if (isset($this->v['attachments'][$this->v['messageID']])) { ?>
	<?php if (count($this->v['attachments'][$this->v['messageID']]['images']) > 0) { ?>
		<fieldset class="attachmentPreview">
			<legend><?php echo StringUtil::encodeHTML($this->v['author']->username); ?> has attached the following image<?php if (count($this->v['attachments'][$this->v['messageID']]['images']) > 1) { ?>s<?php } ?>:</legend>
			<ul class="floatContainer">
				<?php
if (count($this->v['attachments'][$this->v['messageID']]['images']) > 0) {
foreach ($this->v['attachments'][$this->v['messageID']]['images'] as $this->v['attachment']) {
?>
					<li class="floatedElement container-4" style="width: <?php echo StringUtil::encodeHTML(ATTACHMENT_THUMBNAIL_WIDTH+2); ?>px; height: <?php echo StringUtil::encodeHTML(ATTACHMENT_THUMBNAIL_HEIGHT+2); ?>px;">
						<?php if ($this->v['attachment']->thumbnailType) { ?>
							<a href="index.php?page=Attachment&amp;attachmentID=<?php echo $this->v['attachment']->attachmentID; ?>&amp;h=<?php echo $this->v['attachment']->sha1Hash; ?><?php echo SID_ARG_2ND; ?>" style="width: <?php echo StringUtil::encodeHTML(ATTACHMENT_THUMBNAIL_WIDTH); ?>px; height: <?php echo StringUtil::encodeHTML(ATTACHMENT_THUMBNAIL_HEIGHT); ?>px;" class="enlargable" title="<?php echo StringUtil::encodeHTML($this->v['attachment']->attachmentName); ?>"><img src="index.php?page=Attachment&amp;attachmentID=<?php echo $this->v['attachment']->attachmentID; ?>&amp;h=<?php echo $this->v['attachment']->sha1Hash; ?>&amp;thumbnail=1<?php echo SID_ARG_2ND; ?>" alt="<?php echo StringUtil::encodeHTML($this->v['attachment']->attachmentName); ?>" style="width: <?php echo $this->v['attachment']->getThumbnailWidth(); ?>px; height: <?php echo $this->v['attachment']->getThumbnailHeight(); ?>px; margin-top: -<?php echo $this->v['attachment']->getThumbnailHeight()/2; ?>px" /><span></span></a>
						<?php } else { ?>
							<div style="width: <?php echo StringUtil::encodeHTML(ATTACHMENT_THUMBNAIL_WIDTH); ?>px; height: <?php echo StringUtil::encodeHTML(ATTACHMENT_THUMBNAIL_HEIGHT); ?>px;"><img src="index.php?page=Attachment&amp;attachmentID=<?php echo $this->v['attachment']->attachmentID; ?>&amp;h=<?php echo $this->v['attachment']->sha1Hash; ?><?php echo SID_ARG_2ND; ?>" alt="<?php echo StringUtil::encodeHTML($this->v['attachment']->attachmentName); ?>" title="<?php echo StringUtil::encodeHTML($this->v['attachment']->attachmentName); ?>" style="width: <?php echo $this->v['attachment']->getWidth(); ?>px; height: <?php echo $this->v['attachment']->getHeight(); ?>px; margin-top: -<?php echo $this->v['attachment']->getHeight()/2; ?>px" /></div>
						<?php } ?>
					</li>
				<?php } } ?>
			</ul>
		</fieldset>
	<?php } ?>
	
	<?php if (count($this->v['attachments'][$this->v['messageID']]['files']) > 0) { ?>
		<fieldset class="attachmentFile">
			<legend><?php echo StringUtil::encodeHTML($this->v['author']->username); ?> has attached the following file<?php if (count($this->v['attachments'][$this->v['messageID']]['files']) > 1) { ?>s<?php } ?>:</legend>
			<ul>
				<?php
if (count($this->v['attachments'][$this->v['messageID']]['files']) > 0) {
foreach ($this->v['attachments'][$this->v['messageID']]['files'] as $this->v['attachment']) {
?>
					<li>
						<a href="index.php?page=Attachment&amp;attachmentID=<?php echo $this->v['attachment']->attachmentID; ?>&amp;h=<?php echo $this->v['attachment']->sha1Hash; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StringUtil::encodeHTML($this->v['attachment']->getFileTypeIcon()); ?>" alt="" /></a>
						
						<div>
							<a<?php if ($this->v['attachment']->getContentPreview()) { ?> title="<?php echo StringUtil::encodeHTML($this->v['attachment']->getContentPreview()); ?>"<?php } ?> href="index.php?page=Attachment&amp;attachmentID=<?php echo $this->v['attachment']->attachmentID; ?>&amp;h=<?php echo $this->v['attachment']->sha1Hash; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['attachment']->attachmentName); ?></a>
							<span class="smallFont">(<?php echo $this->pluginObjects['TemplatePluginModifierFilesize']->execute(array($this->v['attachment']->attachmentSize), $this); ?> - <b><?php echo StringUtil::formatNumeric($this->v['attachment']->downloads); ?></b> times downloaded<?php if ($this->v['attachment']->downloads > 0) { ?> - latest: <?php echo $this->pluginObjects['TemplatePluginModifierShorttime']->execute(array($this->v['attachment']->lastDownloadTime), $this); ?><?php } ?>)</span>
						</div>
					</li>
				<?php } } ?>
			</ul>
		</fieldset>
	<?php } ?>
<?php } ?>