<?php
/**
* WoltLab Community Framework
* Template: login
* Compiled at: Sat, 17 Aug 2013 09:22:34 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'login';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><?php
$outerTemplateName5ea7edf475590fc7e1b9e8b812524e535b448f8d = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName5ea7edf475590fc7e1b9e8b812524e535b448f8d;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Login - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang58f4e28c4e46a6ff5560c43419e43e230812ff73 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang58f4e28c4e46a6ff5560c43419e43e230812ff73, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName0cbb31fc40689d233911626b746fa6d407f60978 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName0cbb31fc40689d233911626b746fa6d407f60978;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateNamef8c6fba79849f2867069f37c97516d48e56956ff = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef8c6fba79849f2867069f37c97516d48e56956ff;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<script type="text/javascript">
		//<![CDATA[
		onloadEvents.push(function() { if (!'<?php echo StringUtil::encodeHTML($this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['username']), $this)); ?>' || '<?php echo StringUtil::encodeHTML($this->v['errorField']); ?>' == 'username') document.getElementById('loginUsername').focus(); else document.getElementById('loginPassword').focus(); });
		//]]>
	</script>
	
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langcc1ff3ef60f41c40fcd3926375df6c0809a18ced = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langcc1ff3ef60f41c40fcd3926375df6c0809a18ced, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('loginL.png'); ?>" alt="" />
		<div class="headlineContainer">
			<h2> Login</h2>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if ($this->v['errorField']) { ?>
		<p class="error">The data you have entered are invalid. Please check the information you have given in the marked fields.</p>
	<?php } ?>
	
	<form method="post" action="index.php?form=UserLogin">
		<div class="border content">
			<div class="container-1">
				<div class="formElement<?php if ($this->v['errorField'] == 'username') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="loginUsername">Username</label>
					</div>
					<div class="formField">
						<input type="text" class="inputText" name="loginUsername" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" id="loginUsername" />
						<?php if ($this->v['errorField'] == 'username') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
								<?php if ($this->v['errorType'] == 'notFound') { ?>The user name &quot;<?php echo StringUtil::encodeHTML($this->v['username']); ?>&quot; could not be found.<?php } ?>
								<?php if ($this->v['errorType'] == 'notEnabled') { ?>wcf.user.login.error.username.notEnabled<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
				
				<div class="formElement<?php if ($this->v['errorField'] == 'password') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="loginPassword">Password</label>
					</div>
					<div class="formField">
						<input type="password" class="inputText" name="loginPassword" value="<?php echo StringUtil::encodeHTML($this->v['password']); ?>" id="loginPassword" />
						<?php if ($this->v['errorField'] == 'password') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
								<?php if ($this->v['errorType'] == 'false') { ?>The password you entered is invalid. If you have lost your password you can use the <a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">&quot;Lost Password&quot; function</a>.<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
				
				<?php if ($this->v['supportsPersistentLogins']) { ?>
					<div class="formElement">
						<div class="formField">
							<label><input type="checkbox" name="useCookies" value="1" <?php if ($this->v['useCookies'] == 1) { ?>checked="checked" <?php } ?>/> Remember my login on this computer until I logout manually.</label>
						</div>
					</div>
				<?php } ?>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
				<?php
$outerTemplateNamef04afe631847b9c9fdced1c2728d4ffafacd7d0b = $this->v['tpl']['template'];
$this->includeTemplate('captcha', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamef04afe631847b9c9fdced1c2728d4ffafacd7d0b;
$this->v['tpl']['includedTemplates']['captcha'] = 1;
?>
				
				<div class="formElement">
					<div class="formField">
						<ul class="formOptionsLong">
							<li><img src="<?php echo StyleManager::getStyle()->getIconPath('lostPasswordS.png'); ?>" alt="" /> <a href="index.php?form=LostPassword<?php echo SID_ARG_2ND; ?>">Lost password</a></li>
							<?php if ( ! REGISTER_DISABLED && REGISTER_ACTIVATION_METHOD == 1) { ?><li><img src="<?php echo StyleManager::getStyle()->getIconPath('registerS.png'); ?>" alt="" /> <a href="index.php?page=Register&amp;action=enable<?php echo SID_ARG_2ND; ?>">Finish registration</a></li><?php } ?>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
			
		<div class="formSubmit">
			<input type="submit" accesskey="s" value="Submit" />
			<input type="reset" accesskey="r" value="Reset" />
		</div>
		
		<input type="hidden" name="url" value="<?php echo StringUtil::encodeHTML($this->v['url']); ?>" />
		<?php echo SID_INPUT_TAG; ?>
	</form>

</div>

<?php
$outerTemplateNamecb6b2382f03972cd57347000fa6f7a5a72ef8697 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamecb6b2382f03972cd57347000fa6f7a5a72ef8697;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>