<?php
/**
* WoltLab Community Framework
* Template: lostPassword
* Compiled at: Sat, 17 Aug 2013 09:25:26 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'lostPassword';
?>
<?php
$outerTemplateNamed3aef1027871f25247ab299bfaa8834738cf8a23 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamed3aef1027871f25247ab299bfaa8834738cf8a23;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Lost password - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langa78942ddbd551868af0fcd3e96497f7d51c3d52f = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langa78942ddbd551868af0fcd3e96497f7d51c3d52f, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName30d20f4deee5d30ef1458da6dc9c0b0580450bc4 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName30d20f4deee5d30ef1458da6dc9c0b0580450bc4;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<script type="text/javascript">
		//<![CDATA[
		function checkLostPasswordInput() {
			if (document.getElementById('username').value == '') {
				enableOptions('email');
			}
			if (document.getElementById('email').value == '') {
				enableOptions('username');
			}
			
			if (document.getElementById('username').value != '' && document.getElementById('email').value == '') {
				disableOptions('email');
			}
			if (document.getElementById('username').value == '' && document.getElementById('email').value != '') {
				disableOptions('username');
			}
		}
		
		onloadEvents.push(function() { checkLostPasswordInput(); });
		//]]>
	</script>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateNamedfb75245cef153d566ad52edd0893c79c1a0d13e = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamedfb75245cef153d566ad52edd0893c79c1a0d13e;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langc90185b0fbe17e3be929e3520024dc932089bd64 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langc90185b0fbe17e3be929e3520024dc932089bd64, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('lostPasswordL.png'); ?>" alt="" />
		<div class="headlineContainer">
			<h2>Lost password</h2>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<p class="info">You only have to fill in one of the fields.</p>
	
	<?php if ($this->v['errorField']) { ?>
		<p class="error">The data you have entered are invalid. Please check the information you have given in the marked fields.</p>
	<?php } ?>
	
	<form method="post" action="index.php?form=LostPassword">
		<div class="border content">
			<div class="container-1">
				<div id="usernameDiv" class="formElement<?php if ($this->v['errorField'] == 'username') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="username">Username</label>
					</div>
					<div class="formField">
						<input type="text" class="inputText" name="username" value="<?php echo StringUtil::encodeHTML($this->v['username']); ?>" id="username" onkeyup="checkLostPasswordInput();" />
						<?php if ($this->v['errorField'] == 'username') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
								<?php if ($this->v['errorType'] == 'notFound') { ?>The user name &quot;<?php echo StringUtil::encodeHTML($this->v['username']); ?>&quot; could not be found.<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
			
				<div id="emailDiv" class="formElement<?php if ($this->v['errorField'] == 'email') { ?> formError<?php } ?>">
					<div class="formFieldLabel">
						<label for="email">E-mail Address</label>
					</div>
					<div class="formField">
						<input type="text" class="inputText" name="email" value="<?php echo StringUtil::encodeHTML($this->v['email']); ?>" id="email" onkeyup="checkLostPasswordInput();" />
						<?php if ($this->v['errorField'] == 'email') { ?>
							<p class="innerError">
								<?php if ($this->v['errorType'] == 'empty') { ?>Please enter the required information for this field.<?php } ?>
								<?php if ($this->v['errorType'] == 'notFound') { ?>No user with the e-mail address &quot;<?php echo StringUtil::encodeHTML($this->v['email']); ?>&quot; has been found.<?php } ?>
							</p>
						<?php } ?>
					</div>
				</div>
				
				<?php if (isset($this->v['additionalFields'])) { ?><?php echo $this->v['additionalFields']; ?><?php } ?>
				<?php
$outerTemplateName2d97ce1d4f73f4aff0ecc8966d0f49af5e60cc39 = $this->v['tpl']['template'];
$this->includeTemplate('captcha', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2d97ce1d4f73f4aff0ecc8966d0f49af5e60cc39;
$this->v['tpl']['includedTemplates']['captcha'] = 1;
?>
			</div>
		</div>
		
		<div class="formSubmit">
			<input type="submit" accesskey="s" value="Submit" />
			<input type="reset" accesskey="r" onclick="window.setTimeout('checkLostPasswordInput()', 100)" value="Reset" />
		</div>
	
		<?php echo SID_INPUT_TAG; ?>
	</form>

</div>

<?php
$outerTemplateName1af70bec489a0340c017b80d469bc8e8ec1ddc02 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName1af70bec489a0340c017b80d469bc8e8ec1ddc02;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>