<?php
/**
* WoltLab Community Framework
* Template: membersList
* Compiled at: Thu, 15 Aug 2013 01:21:32 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'membersList';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierConcat'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierConcat.class.php');
$this->pluginObjects['TemplatePluginModifierConcat'] = new TemplatePluginModifierConcat;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionPages'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionPages.class.php');
$this->pluginObjects['TemplatePluginFunctionPages'] = new TemplatePluginFunctionPages;
}
?><?php
$outerTemplateNamea672225a2960823cc501b8b0cc2ac9e29d615390 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamea672225a2960823cc501b8b0cc2ac9e29d615390;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Mitglieder - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang328fad2c9fe04e31188493ac4dd7372d66f50946 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang328fad2c9fe04e31188493ac4dd7372d66f50946, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	<?php
$outerTemplateName586428885ed5b114918904d43c9f1788a1206a35 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName586428885ed5b114918904d43c9f1788a1206a35;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/MultiPagesLinks.class.js"></script>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>

<?php $this->assign('searchScript', 'index.php?form=MembersSearch'); ?>
<?php $this->assign('searchFieldName', 'staticParameters[username]'); ?>
<?php if (isset($this->v['staticParameters']['username'])) { ?><?php $this->assign('searchFieldValue', $this->v['staticParameters']['username']); ?><?php } ?>
<?php $this->assign('searchFieldTitle', 'Mitglieder suchen'); ?>
<?php $this->assign('searchExtendedLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array('index.php?form=MembersSearch',SID_ARG_2ND), $this)); ?>

<?php
$outerTemplateName82de7df7b13f3cd4ffb0ccefe23e652250ab4a0f = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName82de7df7b13f3cd4ffb0ccefe23e652250ab4a0f;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_langfcd2a69e3aba94b61dd32ee2e5d49c5ae6e526fa = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langfcd2a69e3aba94b61dd32ee2e5d49c5ae6e526fa, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('membersL.png'); ?>" alt="" />
		<div class="headlineContainer">
			<h2>Mitglieder</h2>
			<p>Insgesamt <?php echo StringUtil::formatNumeric($this->v['items']); ?> Mitglied<?php if ($this->v['items'] != 1) { ?>er<?php } ?></p>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<div class="tabMenu">
		<ul>
			<li<?php if ( ! $this->v['searchID']) { ?> class="activeTabMenu"<?php } ?>><a href="index.php?page=MembersList<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('membersM.png'); ?>" alt="" /> <span>Mitgliederliste</span></a></li>
			<li<?php if ($this->v['searchID']) { ?> class="activeTabMenu"<?php } ?>><a href="index.php?form=MembersSearch<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('membersSearchM.png'); ?>" alt="" /> <span>Mitgliedersuche</span></a></li>
			<?php if ($this->v['hasFriends']) { ?><li><a href="index.php?page=MyFriendsList<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('friendsM.png'); ?>" alt="" /> <span>Meine Freunde</span></a></li><?php } ?>
			<?php if (isset($this->v['additionalTabs'])) { ?><?php echo $this->v['additionalTabs']; ?><?php } ?>
		</ul>
	</div>
	<div class="subTabMenu">
		<div class="containerHead">
			<ul>
				<li<?php if (empty($this->v['letter'])) { ?> class="activeSubTabMenu"<?php } ?>><a href="index.php?page=MembersList&amp;searchID=<?php echo $this->v['searchID']; ?><?php echo SID_ARG_2ND; ?>"><span>alle</span></a></li>
				<?php
if (count($this->v['letters']) > 0) {
foreach ($this->v['letters'] as $this->v['letterItem']) {
?>
					<li<?php if (rawurlencode($this->v['letterItem']) == $this->v['letter']) { ?> class="activeSubTabMenu"<?php } ?>><a href="index.php?page=MembersList&amp;letter=<?php echo rawurlencode($this->v['letterItem']); ?><?php if ($this->v['searchID']) { ?>&amp;searchID=<?php echo $this->v['searchID']; ?><?php } ?><?php echo SID_ARG_2ND; ?>"><span><?php echo StringUtil::encodeHTML($this->v['letterItem']); ?></span></a></li>
				<?php } } ?>
			</ul>
		</div>
	</div>
	
	<div class="border tabMenuContent">
		<?php if (count($this->v['members']) > 0) { ?>
			<table class="tableList membersList">
				<thead>
					<tr class="tableHead">
						<?php
if (count($this->v['header']) > 0) {
foreach ($this->v['header'] as $this->v['field']) {
?>
							<?php if ($this->v['field']['sortable']) { ?>
								<th class="column<?php echo StringUtil::encodeHTML(ucfirst($this->v['field']['field'])); ?><?php if ($this->v['sortField'] == $this->v['field']['field']) { ?> active<?php } ?>"><div><a href="index.php?page=MembersList&amp;letter=<?php echo $this->v['letter']; ?>&amp;searchID=<?php echo $this->v['searchID']; ?>&amp;pageNo=<?php echo $this->v['pageNo']; ?>&amp;sortField=<?php echo StringUtil::encodeHTML($this->v['field']['field']); ?>&amp;sortOrder=<?php if ($this->v['sortField'] == $this->v['field']['field'] && $this->v['sortOrder'] == 'ASC') { ?>DESC<?php } else { ?>ASC<?php } ?><?php echo SID_ARG_2ND; ?>"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['field']['name']; ?><?php $_lang5bc1fd6f5e17cba6f51a3561e829d24627bd64e0 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang5bc1fd6f5e17cba6f51a3561e829d24627bd64e0, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?><?php if ($this->v['sortField'] == $this->v['field']['field']) { ?> <img src="<?php ob_start(); ?>sort<?php echo $this->v['sortOrder']; ?>S.png<?php $_iconbceb5ff10dc30df6bd5d639a7323cfbe426892d7 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconbceb5ff10dc30df6bd5d639a7323cfbe426892d7); ?>" alt="" /><?php } ?></a></div></th>
							<?php } else { ?>
								<th class="column<?php echo StringUtil::encodeHTML(ucfirst($this->v['field']['field'])); ?>"><div><span class="emptyHead"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['field']['name']; ?><?php $_lang065f0043a939fa97ae603e59f0e30ab76bf32a3b = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang065f0043a939fa97ae603e59f0e30ab76bf32a3b, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></div></th>
							<?php } ?>
						<?php } } ?>
					</tr>
				</thead>
				<tbody>
					<?php
if (count($this->v['members']) > 0) {
foreach ($this->v['members'] as $this->v['member']) {
?>
						<tr class="container-<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => '1,2'), $this); ?>">
							<?php
if (count($this->v['fields']) > 0) {
foreach ($this->v['fields'] as $this->v['field']) {
?>
								<td class="column<?php echo StringUtil::encodeHTML(ucfirst($this->v['field'])); ?>"><?php echo $this->v['member'][$this->v['field']]; ?></td>
							<?php } } ?>
						</tr>
					<?php } } ?>
				</tbody>
			</table>
		<?php } else { ?>
			<div class="container-1">
				Es gibt kein Mitglied mit diesem Anfangsbuchstaben.
			</div>
		<?php } ?>
	</div>
	
	<?php echo $this->pluginObjects['TemplatePluginFunctionPages']->execute(array('link' => $this->pluginObjects['TemplatePluginModifierConcat']->execute(array("index.php?page=MembersList&pageNo=%d&searchID={$this->v['searchID']}&sortField={$this->v['sortField']}&sortOrder={$this->v['sortOrder']}&letter={$this->v['letter']}",SID_ARG_2ND_NOT_ENCODED), $this)), $this); ?>

</div>

<?php
$outerTemplateName3216bec5af5ebdf3e264804c27796a2b9cfda833 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3216bec5af5ebdf3e264804c27796a2b9cfda833;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>