<?php
/**
* WoltLab Community Framework
* Template: messageFormMultiQuote
* Compiled at: Tue, 13 Aug 2013 11:30:42 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'messageFormMultiQuote';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><div id="multiQuote" class="hidden">
	<fieldset class="noJavaScript">
		<legend class="noJavaScript">Zitate</legend>
		
		<div id="multiQuoteList"></div>
	</fieldset>
</div>

<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/MultiQuoteManager.class.js"></script>
<script type="text/javascript">
	//<![CDATA[
	// show tab
	tabbedPane.addTab('multiQuote', false);
	var showQuoteTab = true;
	
	// quotes
	var quotes = new Hash();
	<?php
if (count($this->v['quotes']) > 0) {
foreach ($this->v['quotes'] as $this->v['quoteID'] => $this->v['quote']) {
?>
		quotes.set('<?php echo $this->v['quoteID']; ?>', {
			quoteID: '<?php echo $this->v['quoteID']; ?>',
			objectID: <?php echo $this->v['quote']['objectID']; ?>,
			objectType: '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['quote']['objectType']), $this); ?>',
			parentID: <?php echo $this->v['quote']['parentID']; ?>,
			author: '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['quote']['author']), $this); ?>',
			url: '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['quote']['url']), $this); ?>',
			text: '<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['quote']['text']), $this); ?>',
			used: <?php echo $this->v['quote']['used']; ?>
		});
	<?php } } ?>
	document.observe("dom:loaded", function() { }); // ie fix
	document.observe("dom:loaded", function() {
		multiQuoteManagerObj = new MultiQuoteManager(quotes, {
			langInsertQuote: 'Zitat in Text einfügen',
			langRemoveQuote: 'Zitat entfernen',
			langNoQuotes: 'Sie haben keine Zitate gespeichert.',
			langSelectedQuotes: '(count > 1 ? "Die ausgewählten Zitate werden" : "Das ausgewählte Zitat wird") + " nach dem Absenden des Formulars gelöscht."',
			imgInsertSrc: '<?php echo StyleManager::getStyle()->getIconPath('messageS.png'); ?>',
			imgRemoveSrc: '<?php echo StyleManager::getStyle()->getIconPath('deleteS.png'); ?>'
		});

		if (typeof(multiQuoteObj) != 'undefined') {
			multiQuoteObj.setManager(multiQuoteManagerObj);
		}

		if (!$('multiQuoteList').down('li') && !$('multiQuoteTab').hasClassName('activeTabMenu')) {
			showQuoteTab = false;
			//$('multiQuoteTab').setOpacity('0.5');
			$('multiQuoteTab').addClassName('disabled');
			var a = $('multiQuoteTab').down('a');
			if (Prototype.Browser.IE) a.setOpacity('0.5');
			a.onclick = '';
			a.setStyle({ 'cursor' : 'default' });
			a.observe('click', function(evt) {
				if (showQuoteTab) {
					tabbedPane.openTab('multiQuote');
				}
			});
		}
	});
	
	document.observe('wcf:MultiQuote:saveQuote', function() {
		showQuoteTab = true;
		$('multiQuoteTab').removeClassName('disabled');
		$('multiQuoteTab').down('a').setStyle({ 'cursor' : 'pointer' });
		if (Prototype.Browser.IE) $('multiQuoteTab').down('a').setOpacity('1');
	});
	//]]>
</script>