<?php
/**
* WoltLab Community Framework
* Template: multiQuote
* Compiled at: Tue, 13 Aug 2013 11:31:09 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'multiQuote';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
?><script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/MultiQuote.class.js"></script>
<script type="text/javascript">
	//<![CDATA[
	var quoteData = new Hash();
	document.observe("dom:loaded", function() {
		multiQuoteObj = new MultiQuote(quoteData, '<?php if (isset($this->v['formURL'])) { ?><?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['formURL']), $this); ?><?php } ?>', {
			langButtonQuote			: 'Zitieren',
			langButtonQuoteMultiple		: '"Zitieren" + (objectValue.quotes > 0 ? " ("+objectValue.quotes+")" : "")',
			langQuoteDirectly		: 'Nachricht direkt zitieren',
			langMarkToQuote			: 'Nachricht zum Zitieren auswählen',
			langQuoteTextDirectly		: 'Textstelle direkt zitieren',
			langMarkTextToQuote		: 'Textstelle zum Zitieren auswählen',
			langRemoveQuotes		: 'Ausgewählte Zitate entfernen',
			langQuoteParagraphDirectly	: 'Absatz direkt zitieren',
			langMarkParagraphToQuote	: 'Absatz zum Zitieren auswählen',
			langQuoteParagraphsDirectly	: 'Absätze direkt zitieren',
			langMarkParagraphsToQuote	: 'Absätze zum Zitieren auswählen',
			iconMessageQuoteOptions		: '<?php echo StyleManager::getStyle()->getIconPath('messageQuoteOptionsS.png'); ?>'
		});
	});
//]]>
</script>