<?php
/**
* WoltLab Community Framework
* Template: index
* Compiled at: Tue, 13 Aug 2013 11:36:40 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'index';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginModifierTime'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierTime.class.php');
$this->pluginObjects['TemplatePluginModifierTime'] = new TemplatePluginModifierTime;
}
?><?php
$outerTemplateName26f9f0363e935b20e6ac57da0d044ae7da597b09 = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName26f9f0363e935b20e6ac57da0d044ae7da597b09;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title>Main Page - <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang8089ba0292284647b012be2279dc6e5614d2ca1d = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang8089ba0292284647b012be2279dc6e5614d2ca1d, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	
	<?php
$outerTemplateName110a48172d1c12e368d40dcf0c2cd297832db830 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName110a48172d1c12e368d40dcf0c2cd297832db830;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	<link rel="alternate" type="application/rss+xml" href="index.php?page=ThreadsFeed&amp;format=rss2" title="Feed (RSS2)" />
	<link rel="alternate" type="application/atom+xml" href="index.php?page=ThreadsFeed&amp;format=atom" title="Feed (Atom)" />
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateNameea699e5072d305a126a0232ada3454045e7155c0 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameea699e5072d305a126a0232ada3454045e7155c0;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<div class="mainHeadline">
		<img src="<?php echo StyleManager::getStyle()->getIconPath('indexL.png'); ?>" alt="" ondblclick="document.location.href=fixURL('index.php?action=BoardMarkAllAsRead&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>')" title="Mark all Forums as read" />
		<div class="headlineContainer">
			<h2><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang2eae53669eb175cc7334ce0447d050c670545d25 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang2eae53669eb175cc7334ce0447d050c670545d25, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></h2>
			<p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_DESCRIPTION); ?><?php $_lang072e8d09aa5a5b61ab05c9ea45271ce608fce5c7 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang072e8d09aa5a5b61ab05c9ea45271ce608fce5c7, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php if (isset($this->v['additionalTopContents'])) { ?><?php echo $this->v['additionalTopContents']; ?><?php } ?>
	
	<?php
$outerTemplateName787d305d9291b5a1182e348eea52842ff7128d87 = $this->v['tpl']['template'];
$this->includeTemplate("boardList", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName787d305d9291b5a1182e348eea52842ff7128d87;
$this->v['tpl']['includedTemplates']["boardList"] = 1;
?>
	
	<?php if (isset($this->v['usersOnlineTotal']) || INDEX_ENABLE_STATS || isset($this->v['additionalBoxes']) || count($this->v['tags'])) { ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2', 'print' => false, 'advance' => false), $this); ?>
		<div class="border infoBox">
			<?php if (isset($this->v['usersOnlineTotal'])) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxUsersOnline">
					<div class="containerIcon"> <img src="<?php echo StyleManager::getStyle()->getIconPath('membersM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3><?php if ($this->v['this']->user->getPermission('user.usersOnline.canView')) { ?><a href="index.php?page=UsersOnline<?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['usersOnlineTotal']); ?> <?php if ($this->v['usersOnlineTotal'] == 1) { ?>user is<?php } else { ?>users are<?php } ?> browsing the forums</a><?php } else { ?><?php echo StringUtil::encodeHTML($this->v['usersOnlineTotal']); ?> <?php if ($this->v['usersOnlineTotal'] == 1) { ?>user is<?php } else { ?>users are<?php } ?> browsing the forums<?php } ?></h3> 
						<p class="smallFont">
<?php if ($this->v['usersOnlineMembers'] > 0) { ?>
	<?php echo StringUtil::encodeHTML($this->v['usersOnlineMembers']); ?> member<?php if ($this->v['usersOnlineMembers'] != 1) { ?>s<?php } ?>
<?php } ?>
<?php if ($this->v['usersOnlineInvisible'] > 0) { ?>
	(<?php echo StringUtil::encodeHTML($this->v['usersOnlineInvisible']); ?> thereof are invisible)
<?php } ?>
<?php if ($this->v['usersOnlineGuests'] > 0 && $this->v['usersOnlineMembers'] > 0) { ?> and <?php } ?>
<?php if ($this->v['usersOnlineGuests'] > 0) { ?>
	<?php echo StringUtil::encodeHTML($this->v['usersOnlineGuests']); ?> guests
<?php } ?> <?php if (USERS_ONLINE_RECORD > 0) { ?>- Record: <?php echo StringUtil::formatNumeric(USERS_ONLINE_RECORD); ?> user<?php if (USERS_ONLINE_RECORD != 1) { ?>s<?php } ?> (<?php echo $this->pluginObjects['TemplatePluginModifierTime']->execute(array(USERS_ONLINE_RECORD_TIME), $this); ?><?php } ?>)</p>
						<?php if (count($this->v['usersOnline'])) { ?>
							<p class="smallFont">
							<?php
$_length447770e2d256dd7cbf2113f72198b883cff9f052 = count($this->v['usersOnline']);
$_i447770e2d256dd7cbf2113f72198b883cff9f052 = 0;
foreach ($this->v['usersOnline'] as $this->v['userOnline']) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['userOnline']['userID']; ?><?php echo SID_ARG_2ND; ?>"><?php echo $this->v['userOnline']['username']; ?></a><?php
if (++$_i447770e2d256dd7cbf2113f72198b883cff9f052 < $_length447770e2d256dd7cbf2113f72198b883cff9f052) { echo ', '; }
} ?>
							</p>
							<?php if (INDEX_ENABLE_USERS_ONLINE_LEGEND && count($this->v['usersOnlineMarkings'])) { ?>
								<p class="smallFont">
								Legend: <?php
$_length55a3d64ccbf1c1c745c01579cf8ffcf153a715ab = count($this->v['usersOnlineMarkings']);
$_i55a3d64ccbf1c1c745c01579cf8ffcf153a715ab = 0;
foreach ($this->v['usersOnlineMarkings'] as $this->v['usersOnlineMarking']) { ?><?php echo $this->v['usersOnlineMarking']; ?><?php
if (++$_i55a3d64ccbf1c1c745c01579cf8ffcf153a715ab < $_length55a3d64ccbf1c1c745c01579cf8ffcf153a715ab) { echo ', '; }
} ?>
								</p>
							<?php } ?>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
			
			<?php if (INDEX_ENABLE_STATS) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxStatistics">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('statisticsM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Statistics:</h3> 
						<p class="smallFont"><?php echo StringUtil::formatNumeric($this->v['stats']['members']); ?> Member<?php if ($this->v['stats']['members'] != 1) { ?>s<?php } ?> - <?php echo StringUtil::formatNumeric($this->v['stats']['threads']); ?> <?php if ($this->v['stats']['threads'] == 1) { ?>Thread<?php } else { ?>Threads<?php } ?> - <?php echo StringUtil::formatNumeric($this->v['stats']['posts']); ?> <?php if ($this->v['stats']['posts'] == 1) { ?>Post<?php } else { ?>Posts<?php } ?> (<?php echo StringUtil::formatNumeric($this->v['stats']['postsPerDay']); ?> <?php if ($this->v['stats']['postsPerDay'] == 1) { ?>Post<?php } else { ?>Posts<?php } ?> per day)<br />
Newest member: <a href="index.php?page=User&amp;userID=<?php echo $this->v['stats']['newestMember']->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['stats']['newestMember']->username); ?></a>.</p>
					</div>
				</div>
			<?php } ?>
			
			<?php if (isset($this->v['additionalBoxes'])) { ?><?php echo $this->v['additionalBoxes']; ?><?php } ?>
			
			<?php if (count($this->v['tags'])) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxTags">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('tagM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3><a href="index.php?page=TaggedObjects<?php echo SID_ARG_2ND; ?>">Most popular tags</a></h3>
						<?php
$outerTemplateName2952d0b7fabb52e5e60f21de2fc73d8940b814c0 = $this->v['tpl']['template'];
$this->includeTemplate('tagCloud', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName2952d0b7fabb52e5e60f21de2fc73d8940b814c0;
$this->v['tpl']['includedTemplates']['tagCloud'] = 1;
?>
					</div>
				</div>
			<?php } ?>
		</div>
	<?php } ?>
	<div class="pageOptions">
		<?php if (isset($this->v['additionalPageOptions'])) { ?><?php echo $this->v['additionalPageOptions']; ?><?php } ?>
		<a href="index.php?action=BoardMarkAllAsRead&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('boardMarkAsReadS.png'); ?>" alt="" /> <span>Mark all Forums as read</span></a>
	</div>
</div>

<?php
$outerTemplateName37ddce7e5e8d9ea78f703226c7a0da6ba12bfaaf = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName37ddce7e5e8d9ea78f703226c7a0da6ba12bfaaf;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>

</body>
</html>