<?php
/**
* WoltLab Community Framework
* Template: board
* Compiled at: Tue, 13 Aug 2013 11:10:47 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'board';
?>
<?php
if (!isset($this->pluginObjects['TemplatePluginModifierConcat'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierConcat.class.php');
$this->pluginObjects['TemplatePluginModifierConcat'] = new TemplatePluginModifierConcat;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionPages'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionPages.class.php');
$this->pluginObjects['TemplatePluginFunctionPages'] = new TemplatePluginFunctionPages;
}
if (!isset($this->pluginObjects['TemplatePluginModifierEncodejs'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginModifierEncodejs.class.php');
$this->pluginObjects['TemplatePluginModifierEncodejs'] = new TemplatePluginModifierEncodejs;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionCycle'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionCycle.class.php');
$this->pluginObjects['TemplatePluginFunctionCycle'] = new TemplatePluginFunctionCycle;
}
if (!isset($this->pluginObjects['TemplatePluginFunctionHtmloptions'])) {
require_once(WCF_DIR.'lib/system/template/plugin/TemplatePluginFunctionHtmloptions.class.php');
$this->pluginObjects['TemplatePluginFunctionHtmloptions'] = new TemplatePluginFunctionHtmloptions;
}
?><?php
$outerTemplateNamee7218936305ac46f1f1d7367a4b06ffe6ff36e9f = $this->v['tpl']['template'];
$this->includeTemplate("documentHeader", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNamee7218936305ac46f1f1d7367a4b06ffe6ff36e9f;
$this->v['tpl']['includedTemplates']["documentHeader"] = 1;
?>
<head>
	<title><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_lang0cc014435b813a9e1388d1de8ac15134cc2eb1df = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang0cc014435b813a9e1388d1de8ac15134cc2eb1df, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?> <?php if ($this->v['pageNo'] > 1) { ?>- Seite <?php echo StringUtil::formatNumeric($this->v['pageNo']); ?> <?php } ?>- <?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang9c29552a8afc8ec9e1c222c769aa7fca219f0640 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang9c29552a8afc8ec9e1c222c769aa7fca219f0640, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></title>
	
	<?php
$outerTemplateName5085ec506ce85377b029c99bd184dd43430eddf3 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName5085ec506ce85377b029c99bd184dd43430eddf3;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
	
	<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/MultiPagesLinks.class.js"></script>
	<link rel="alternate" type="application/rss+xml" href="index.php?page=ThreadsFeed&amp;format=rss2&amp;boardID=<?php echo $this->v['boardID']; ?>" title="Themen dieses Forums abonnieren (RSS2)" />
	<link rel="alternate" type="application/atom+xml" href="index.php?page=ThreadsFeed&amp;format=atom&amp;boardID=<?php echo $this->v['boardID']; ?>" title="Themen dieses Forums abonnieren (Atom)" />
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>

<?php $this->assign('searchFieldTitle', 'Forum durchsuchen'); ?>
<?php ob_start(); ?>
	<input type="hidden" name="boardIDs[]" value="<?php echo $this->v['boardID']; ?>" />
	<input type="hidden" name="types[]" value="post" />
<?php
$this->v['tpl']['capture']['default'] = ob_get_contents();
ob_end_clean();
$this->assign('searchHiddenFields', $this->v['tpl']['capture']['default']);
?>

<?php
$outerTemplateName935227bba30a39a27b5248abddf4121bac2ce74e = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName935227bba30a39a27b5248abddf4121bac2ce74e;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	
	<?php
$outerTemplateName11ca136246344dc970cb1cc486c96d856a481d9c = $this->v['tpl']['template'];
$this->includeTemplate("navigation", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName11ca136246344dc970cb1cc486c96d856a481d9c;
$this->v['tpl']['includedTemplates']["navigation"] = 1;
?>
	
	<div class="mainHeadline">
		<img src="<?php ob_start(); ?><?php echo $this->v['board']->getIconName(); ?>L.png<?php $_icon3116b9d3a37c5908188d8e8fc2fb50b39ab86971 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon3116b9d3a37c5908188d8e8fc2fb50b39ab86971); ?>" alt="" <?php if ($this->v['board']->isBoard()) { ?>ondblclick="document.location.href=fixURL('index.php?action=BoardMarkAsRead&amp;boardID=<?php echo $this->v['boardID']; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>')" title="Forum durch Doppelklick als gelesen markieren" <?php } ?>/>
		<div class="headlineContainer">
			<h2><a href="index.php?page=Board&amp;boardID=<?php echo $this->v['boardID']; ?><?php echo SID_ARG_2ND; ?>"><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML($this->v['board']->title); ?><?php $_langed57a7d74c0a06a9e1bc6fc5ccc21006ae313cfe = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langed57a7d74c0a06a9e1bc6fc5ccc21006ae313cfe, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></a></h2>
			<p><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php if ($this->v['board']->allowDescriptionHtml) { ?><?php echo $this->v['board']->description; ?><?php } else { ?><?php echo StringUtil::encodeHTML($this->v['board']->description); ?><?php } ?><?php $_langdb868e7f96a8dec9e757258d1eed50c8d27bcca5 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langdb868e7f96a8dec9e757258d1eed50c8d27bcca5, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></p>
		</div>
	</div>
	
	<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>
	
	<?php
$outerTemplateName05bdc999e8e27ecf2e7695c19eeaf267c33e61e7 = $this->v['tpl']['template'];
$this->includeTemplate("boardList", array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName05bdc999e8e27ecf2e7695c19eeaf267c33e61e7;
$this->v['tpl']['includedTemplates']["boardList"] = 1;
?>
	
	<?php if ($this->v['board']->isBoard()) { ?>
		<div class="contentHeader">
			<?php $this->assign('encodedPrefix', urlencode($this->v['prefix'])); ?>
			<?php $this->assign('multiplePagesLink', "index.php?page=Board&boardID={$this->v['boardID']}&pageNo=%d"); ?>
			<?php if ($this->v['sortField'] != $this->v['defaultSortField']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&sortField=',$this->v['sortField']), $this)); ?><?php } ?>
			<?php if ($this->v['sortOrder'] != $this->v['defaultSortOrder']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&sortOrder=',$this->v['sortOrder']), $this)); ?><?php } ?>
			<?php if ($this->v['daysPrune'] != $this->v['defaultDaysPrune']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&daysPrune=',$this->v['daysPrune']), $this)); ?><?php } ?>
			<?php if ($this->v['status']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&status=',$this->v['status']), $this)); ?><?php } ?>
			<?php if ($this->v['prefix']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&prefix=',$this->v['encodedPrefix']), $this)); ?><?php } ?>
			<?php if ($this->v['languageID']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&languageID=',$this->v['languageID']), $this)); ?><?php } ?>
			<?php if ($this->v['tagID']) { ?><?php $this->assign('multiplePagesLink', $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],'&tagID=',$this->v['tagID']), $this)); ?><?php } ?>
			<?php echo $this->pluginObjects['TemplatePluginFunctionPages']->execute(array('print' => true, 'assign' => 'pagesOutput', 'link' => $this->pluginObjects['TemplatePluginModifierConcat']->execute(array($this->v['multiplePagesLink'],SID_ARG_2ND_NOT_ENCODED), $this)), $this); ?>
			<?php if ($this->v['board']->canStartThread() || isset($this->v['additionalLargeButtons'])) { ?>
				<div class="largeButtons">
					<ul>
						<?php if ($this->v['board']->canStartThread()) { ?><li><a href="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v['boardID']; ?><?php echo SID_ARG_2ND; ?>" title="Thema erstellen"><img src="<?php echo StyleManager::getStyle()->getIconPath('threadNewM.png'); ?>" alt="" /> <span>Thema erstellen</span></a></li><?php } ?>
						<?php if (isset($this->v['additionalLargeButtons'])) { ?><?php echo $this->v['additionalLargeButtons']; ?><?php } ?>
					</ul>
				</div>
			<?php } ?>
		</div>
	
		<?php if ($this->v['permissions']['canHandleThread'] || $this->v['permissions']['canHandlePost']) { ?>
			<script type="text/javascript">
				//<![CDATA[	
				var language = new Object();
				var postData = new Hash();
				var url = 'index.php?page=Board&boardID=<?php echo $this->v['boardID']; ?>&pageNo=<?php echo $this->v['pageNo']; ?>&sortField=<?php echo $this->v['sortField']; ?>&sortOrder=<?php echo $this->v['sortOrder']; ?>&daysPrune=<?php echo $this->v['daysPrune']; ?>&status=<?php echo $this->v['status']; ?>&prefix=<?php echo $this->pluginObjects['TemplatePluginModifierEncodejs']->execute(array($this->v['prefix']), $this); ?>&languageID=<?php echo $this->v['languageID']; ?><?php echo SID_ARG_2ND_NOT_ENCODED; ?>';
				//]]>
			</script>
			<?php
$outerTemplateNameae9a7ebfb35fdeb543de0f12b046b9e024810ab8 = $this->v['tpl']['template'];
$this->includeTemplate('threadInlineEdit', array('pageType' => 'board'), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameae9a7ebfb35fdeb543de0f12b046b9e024810ab8;
$this->v['tpl']['includedTemplates']['threadInlineEdit'] = 1;
?>
		<?php } ?>
		
		<?php if (count($this->v['topThreads']) == 0 && count($this->v['normalThreads']) == 0) { ?>
			<div class="border content">
				<div class="container-1">
					<p>Es ist kein Thema <?php if ($this->v['board']->getThreads() > 0) { ?>zu den gewählten Kriterien <?php } ?>in diesem Forum vorhanden.</p>
				</div>
			</div>
		<?php } else { ?>
			<script type="text/javascript" src="<?php echo RELATIVE_WBB_DIR; ?>js/ThreadMarkAsRead.class.js"></script>
			<?php if (count($this->v['topThreads']) > 0) { ?>
				<?php
$outerTemplateName3293c5fedebd9c51de2a18fd57ffcc8f241c45ce = $this->v['tpl']['template'];
$this->includeTemplate("boardThreads", array('title' => "Ankündigungen und wichtige Themen", 'threads' => $this->v['topThreads'], 'listName' => 'topThreadsStatus', 'listStatus' => $this->v['topThreadsStatus'], 'listHasNewThreads' => $this->v['newTopThreads']), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3293c5fedebd9c51de2a18fd57ffcc8f241c45ce;
$this->v['tpl']['includedTemplates']["boardThreads"] = 1;
?>
			<?php } ?>
			
			<?php if (count($this->v['normalThreads']) > 0) { ?>
				<?php
$outerTemplateName7793cf638bee1f18a11e9f047340133e0965c957 = $this->v['tpl']['template'];
$this->includeTemplate("boardThreads", array('title' => "Themen", 'threads' => $this->v['normalThreads'], 'listName' => 'normalThreadsStatus', 'listStatus' => $this->v['normalThreadsStatus'], 'listHasNewThreads' => $this->v['newNormalThreads']), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName7793cf638bee1f18a11e9f047340133e0965c957;
$this->v['tpl']['includedTemplates']["boardThreads"] = 1;
?>
			<?php } ?>
		<?php } ?>
	
		<div class="contentFooter">
			<?php echo $this->v['pagesOutput']; ?>
			
			<div id="threadEditMarked" class="optionButtons"></div>
			<div id="postEditMarked" class="optionButtons"></div>
	
			<?php if ($this->v['board']->canStartThread() || isset($this->v['additionalLargeButtons'])) { ?>
				<div class="largeButtons">
					<ul>
						<?php if ($this->v['board']->canStartThread()) { ?><li><a href="index.php?form=ThreadAdd&amp;boardID=<?php echo $this->v['boardID']; ?><?php echo SID_ARG_2ND; ?>" title="Thema erstellen"><img src="<?php echo StyleManager::getStyle()->getIconPath('threadNewM.png'); ?>" alt="" /> <span>Thema erstellen</span></a></li><?php } ?>
						<?php if (isset($this->v['additionalLargeButtons'])) { ?><?php echo $this->v['additionalLargeButtons']; ?><?php } ?>
					</ul>
				</div>
			<?php } ?>
		</div>
	<?php } ?>
	
	<?php if ($this->v['board']->isBoard() || isset($this->v['usersOnlineTotal']) || count($this->v['boardModerators']) || isset($this->v['additionalBoxes']) || count($this->v['tags'])) { ?>
		<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array('values' => 'container-1,container-2', 'print' => false, 'advance' => false), $this); ?>
		<div class="border infoBox">
			<?php if ($this->v['board']->isBoard()) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxSorting">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('sortM.png'); ?>" alt="" /> </div>
					<div class="containerContent">
						<h3>Sortierung &amp; Filterung</h3>
						<form method="get" action="index.php">
							<div class="threadSort">
								<input type="hidden" name="page" value="Board" />
								<input type="hidden" name="boardID" value="<?php echo $this->v['boardID']; ?>" />
								<input type="hidden" name="pageNo" value="<?php echo $this->v['pageNo']; ?>" />
								<input type="hidden" name="tagID" value="<?php echo $this->v['tagID']; ?>" />
								
								<div class="floatedElement">
									<label for="sortField">Sortierung nach</label>
									<select name="sortField" id="sortField">
										<option value="prefix"<?php if ($this->v['sortField'] == 'prefix') { ?> selected="selected"<?php } ?>>Präfix</option>
										<option value="topic"<?php if ($this->v['sortField'] == 'topic') { ?> selected="selected"<?php } ?>>Titel</option>
										<?php if (MODULE_ATTACHMENT) { ?><option value="attachments"<?php if ($this->v['sortField'] == 'attachments') { ?> selected="selected"<?php } ?>>Dateianhänge</option><?php } ?>
										<?php if (MODULE_POLL) { ?><option value="polls"<?php if ($this->v['sortField'] == 'polls') { ?> selected="selected"<?php } ?>>Umfragen</option><?php } ?>
										<option value="username"<?php if ($this->v['sortField'] == 'username') { ?> selected="selected"<?php } ?>>Autor</option>
										<option value="time"<?php if ($this->v['sortField'] == 'time') { ?> selected="selected"<?php } ?>>Erstem Beitrag</option>
										<?php if ($this->v['enableRating']) { ?><option value="ratingResult"<?php if ($this->v['sortField'] == 'ratingResult') { ?> selected="selected"<?php } ?>>Bewertung</option><?php } ?>
										<option value="replies"<?php if ($this->v['sortField'] == 'replies') { ?> selected="selected"<?php } ?>>Antworten</option>
										<option value="views"<?php if ($this->v['sortField'] == 'views') { ?> selected="selected"<?php } ?>>Zugriffe</option>
										<option value="lastPostTime"<?php if ($this->v['sortField'] == 'lastPostTime') { ?> selected="selected"<?php } ?>>Letztem Beitrag</option>
									</select>
									<select name="sortOrder">
										<option value="ASC"<?php if ($this->v['sortOrder'] == 'ASC') { ?> selected="selected"<?php } ?>>in aufsteigender Reihenfolge</option>
										<option value="DESC"<?php if ($this->v['sortOrder'] == 'DESC') { ?> selected="selected"<?php } ?>>in absteigender Reihenfolge</option>
									</select>
								</div>
								
								<div class="floatedElement">
									<label for="filterDate">Im Zeitraum</label>
									<select name="daysPrune" id="filterDate">
										<option value="1"<?php if ($this->v['daysPrune'] == 1) { ?> selected="selected"<?php } ?>>der letzten 24 Stunden</option>
										<option value="3"<?php if ($this->v['daysPrune'] == 3) { ?> selected="selected"<?php } ?>>der letzten 3 Tage</option>
										<option value="7"<?php if ($this->v['daysPrune'] == 7) { ?> selected="selected"<?php } ?>>der letzten 7 Tage</option>
										<option value="14"<?php if ($this->v['daysPrune'] == 14) { ?> selected="selected"<?php } ?>>der letzten 14 Tage</option>
										<option value="30"<?php if ($this->v['daysPrune'] == 30) { ?> selected="selected"<?php } ?>>der letzten 30 Tage</option>
										<option value="60"<?php if ($this->v['daysPrune'] == 60) { ?> selected="selected"<?php } ?>>der letzten 60 Tage</option>
										<option value="100"<?php if ($this->v['daysPrune'] == 100) { ?> selected="selected"<?php } ?>>der letzten 100 Tage</option>
										<option value="365"<?php if ($this->v['daysPrune'] == 365) { ?> selected="selected"<?php } ?>>der letzten 365 Tage</option>
										<option value="1000"<?php if ($this->v['daysPrune'] == 1000) { ?> selected="selected"<?php } ?>>von Anfang an</option>
									</select>
								</div>
								
								<?php if ($this->v['board']->hasPrefixes()) { ?>
									<div class="floatedElement">
										<label for="filterPrefix">Präfix</label>
										<select name="prefix" id="filterPrefix">
											<option value=""></option>
											<option value="empty"<?php if ($this->v['prefix'] == 'empty') { ?> selected="selected"<?php } ?>>ohne Präfix</option>
											<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['board']->getPrefixOptions(), 'selected' => $this->v['prefix']), $this); ?>
										</select>
									</div>
								<?php } ?>
								
								<div class="floatedElement">
									<label for="filterByStatus">Status</label>
									<select name="status" id="filterByStatus">
										<option value=""></option>
										<?php if ($this->v['this']->user->userID) { ?>
											<option value="read"<?php if ($this->v['status'] == 'read') { ?> selected="selected"<?php } ?>>gelesen</option>
											<option value="unread"<?php if ($this->v['status'] == 'unread') { ?> selected="selected"<?php } ?>>ungelesen</option>
										<?php } ?>
										<?php if (MODULE_THREAD_MARKING_AS_DONE && $this->v['board']->enableMarkingAsDone) { ?>
											<option value="done"<?php if ($this->v['status'] == 'done') { ?> selected="selected"<?php } ?>>erledigt</option>
											<option value="undone"<?php if ($this->v['status'] == 'undone') { ?> selected="selected"<?php } ?>>unerledigt</option>
										<?php } ?>
										<option value="closed"<?php if ($this->v['status'] == 'closed') { ?> selected="selected"<?php } ?>>geschlossen</option>
										<option value="open"<?php if ($this->v['status'] == 'open') { ?> selected="selected"<?php } ?>>offen</option>
										<?php if ($this->v['board']->getModeratorPermission('canDeleteThreadCompletely')) { ?><option value="deleted"<?php if ($this->v['status'] == 'deleted') { ?> selected="selected"<?php } ?>>gelöscht</option><?php } ?>
										<?php if ($this->v['board']->getModeratorPermission('canEnableThread')) { ?><option value="hidden"<?php if ($this->v['status'] == 'hidden') { ?> selected="selected"<?php } ?>>deaktiviert</option><?php } ?>
									</select>
								</div>
								
								<?php if (count($this->v['contentLanguages']) > 1) { ?>
									<div class="floatedElement">
										<label for="filterByLanguage">Sprache</label>
										<select name="languageID" id="filterByLanguage">
											<option value="0"></option>
											<?php echo $this->pluginObjects['TemplatePluginFunctionHtmloptions']->execute(array('options' => $this->v['contentLanguages'], 'selected' => $this->v['languageID'], 'disableEncoding' => true), $this); ?>
										</select>
									</div>
								<?php } ?>
								
								<div class="floatedElement">
									<input type="image" class="inputImage" src="<?php echo StyleManager::getStyle()->getIconPath('submitS.png'); ?>" alt="Absenden" />
								</div>
	
								<?php echo SID_INPUT_TAG; ?>
							</div>
						</form>
					</div>
				</div>
			<?php } ?>
	
			<?php if (count($this->v['boardModerators'])) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxModerators">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('moderatorM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Moderatoren:</h3>
						<p class="smallFont"><?php
$_lengthf8dbb5916e75e3d3ad19a6ba877822ac7dfbba15 = count($this->v['boardModerators']);
$_if8dbb5916e75e3d3ad19a6ba877822ac7dfbba15 = 0;
foreach ($this->v['boardModerators'] as $this->v['moderator']) { ?><?php if ($this->v['moderator']->userID) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['moderator']->userID; ?><?php echo SID_ARG_2ND; ?>"><?php echo StringUtil::encodeHTML($this->v['moderator']); ?></a><?php } else { ?><?php echo StringUtil::encodeHTML($this->v['moderator']); ?><?php } ?><?php
if (++$_if8dbb5916e75e3d3ad19a6ba877822ac7dfbba15 < $_lengthf8dbb5916e75e3d3ad19a6ba877822ac7dfbba15) { echo ', '; }
} ?></p>
					</div>
				</div>
			<?php } ?>
		
			<?php if (isset($this->v['usersOnlineTotal'])) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxUsersOnline">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('membersM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3><?php if ($this->v['this']->user->getPermission('user.usersOnline.canView')) { ?><a href="index.php?page=UsersOnline&amp;boardID=<?php echo $this->v['boardID']; ?><?php echo SID_ARG_2ND; ?>">Zurzeit <?php if ($this->v['usersOnlineTotal'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> neben Ihnen <?php echo StringUtil::formatNumeric($this->v['usersOnlineTotal']); ?> Benutzer in diesem Forum unterwegs:</a><?php } else { ?>Zurzeit <?php if ($this->v['usersOnlineTotal'] == 1) { ?>ist<?php } else { ?>sind<?php } ?> neben Ihnen <?php echo StringUtil::formatNumeric($this->v['usersOnlineTotal']); ?> Benutzer in diesem Forum unterwegs:<?php } ?></h3> 
						<p class="smallFont">
<?php if ($this->v['usersOnlineMembers'] > 0) { ?>
	<?php echo StringUtil::formatNumeric($this->v['usersOnlineMembers']); ?> Mitglied<?php if ($this->v['usersOnlineMembers'] != 1) { ?>er<?php } ?>
<?php } ?> 
<?php if ($this->v['usersOnlineInvisible'] > 0) { ?>
	(davon <?php echo StringUtil::formatNumeric($this->v['usersOnlineInvisible']); ?> unsichtbar)
<?php } ?>
<?php if ($this->v['usersOnlineGuests'] > 0 && $this->v['usersOnlineMembers'] > 0) { ?>und<?php } ?>
<?php if ($this->v['usersOnlineGuests'] > 0) { ?>
	<?php echo StringUtil::formatNumeric($this->v['usersOnlineGuests']); ?> Besucher
<?php } ?></p>
						<?php if (count($this->v['usersOnline'])) { ?>
							<p class="smallFont"><?php
$_lengthebe371c3f951e8638367a0ba6a0b219f8574c6e3 = count($this->v['usersOnline']);
$_iebe371c3f951e8638367a0ba6a0b219f8574c6e3 = 0;
foreach ($this->v['usersOnline'] as $this->v['userOnline']) { ?><a href="index.php?page=User&amp;userID=<?php echo $this->v['userOnline']['userID']; ?><?php echo SID_ARG_2ND; ?>"><?php echo $this->v['userOnline']['username']; ?></a><?php
if (++$_iebe371c3f951e8638367a0ba6a0b219f8574c6e3 < $_lengthebe371c3f951e8638367a0ba6a0b219f8574c6e3) { echo ', '; }
} ?></p>
							<?php if (INDEX_ENABLE_USERS_ONLINE_LEGEND && count($this->v['usersOnlineMarkings'])) { ?>
								<p class="smallFont">
								Legende: <?php
$_lengthe8cce90e1038a6c9e680ad4575d38be8e864caa1 = count($this->v['usersOnlineMarkings']);
$_ie8cce90e1038a6c9e680ad4575d38be8e864caa1 = 0;
foreach ($this->v['usersOnlineMarkings'] as $this->v['usersOnlineMarking']) { ?><?php echo $this->v['usersOnlineMarking']; ?><?php
if (++$_ie8cce90e1038a6c9e680ad4575d38be8e864caa1 < $_lengthe8cce90e1038a6c9e680ad4575d38be8e864caa1) { echo ', '; }
} ?>
								</p>
							<?php } ?>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
		
			<?php if ($this->v['board']->isBoard() && BOARD_ENABLE_STATS) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxStatistics">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('statisticsM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Statistik:</h3> 
						<p class="smallFont"><?php echo StringUtil::formatNumeric($this->v['board']->getThreads()); ?> <?php if ($this->v['board']->getThreads() == 1) { ?>Thema<?php } else { ?>Themen<?php } ?> - <?php echo StringUtil::formatNumeric($this->v['board']->getPosts()); ?> <?php if ($this->v['board']->getPosts() == 1) { ?>Beitrag<?php } else { ?>Beiträge<?php } ?> (<?php echo StringUtil::formatNumeric($this->v['board']->getPostsPerDay()); ?> <?php if ($this->v['board']->getPostsPerDay() == 1) { ?>Beitrag<?php } else { ?>Beiträge<?php } ?> pro Tag)</p>
					</div>
				</div>
			<?php } ?>
			
			<?php if (count($this->v['tags'])) { ?>
				<div class="<?php echo $this->pluginObjects['TemplatePluginFunctionCycle']->execute(array(), $this); ?> infoBoxTags">
					<div class="containerIcon"><img src="<?php echo StyleManager::getStyle()->getIconPath('tagM.png'); ?>" alt="" /></div>
					<div class="containerContent">
						<h3>Filter nach Tag<?php if (isset($this->v['tag'])) { ?>: &raquo;<?php echo StringUtil::encodeHTML($this->v['tag']); ?>&laquo;<?php } ?></h3>
						<ul class="tagCloud">
							<?php
if (count($this->v['tags']) > 0) {
foreach ($this->v['tags'] as $this->v['tag']) {
?>
								<li><a href="index.php?page=Board&amp;boardID=<?php echo $this->v['board']->boardID; ?>&amp;pageNo=<?php echo $this->v['pageNo']; ?>&amp;sortField=<?php echo $this->v['sortField']; ?>&amp;sortOrder=<?php echo $this->v['sortOrder']; ?>&amp;daysPrune=<?php echo $this->v['daysPrune']; ?>&amp;status=<?php echo $this->v['status']; ?>&amp;prefix=<?php echo $this->v['encodedPrefix']; ?>&amp;languageID=<?php echo $this->v['languageID']; ?>&amp;tagID=<?php echo $this->v['tag']->getID(); ?><?php echo SID_ARG_2ND; ?>" style="font-size: <?php echo $this->v['tag']->getSize(); ?>%"><?php echo StringUtil::encodeHTML($this->v['tag']->getName()); ?></a></li>
							<?php } } ?>
						</ul>
					</div>
				</div>
			<?php } ?>
			
			<?php if (isset($this->v['additionalBoxes'])) { ?><?php echo $this->v['additionalBoxes']; ?><?php } ?>
		</div>
	<?php } ?>
	
	<div class="pageOptions">
		<?php if ($this->v['board']->isBoard()) { ?>
		
			<?php if (isset($this->v['additionalPageOptions'])) { ?><?php echo $this->v['additionalPageOptions']; ?><?php } ?>
			<?php if ($this->v['this']->user->userID) { ?>
				<?php if ( ! $this->v['this']->user->isBoardSubscription($this->v['boardID'])) { ?><a href="index.php?action=BoardSubscribe&amp;boardID=<?php echo $this->v['boardID']; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('subscribeS.png'); ?>" alt="" /> <span>Forum abonnieren</span></a>
				<?php } else { ?><a href="index.php?action=BoardUnsubscribe&amp;boardID=<?php echo $this->v['boardID']; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('unsubscribeS.png'); ?>" alt="" /> <span>Forum abbestellen</span></a>
				<?php } ?>
			<?php } ?>
			<a href="index.php?action=BoardMarkAsRead&amp;boardID=<?php echo $this->v['boardID']; ?>&amp;t=<?php echo SECURITY_TOKEN; ?><?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('boardMarkAsReadS.png'); ?>" alt="" /> <span>Forum als gelesen markieren</span></a>
		<?php } ?>
	</div>
	
	<?php
$outerTemplateName83eb72180b2531a585a54ebfa6386953edb6fd4a = $this->v['tpl']['template'];
$this->includeTemplate('boardQuickJump', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName83eb72180b2531a585a54ebfa6386953edb6fd4a;
$this->v['tpl']['includedTemplates']['boardQuickJump'] = 1;
?>
</div>

<?php
$outerTemplateName3645936837df1533ba199f89c3a3dd8dedb299ab = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName3645936837df1533ba199f89c3a3dd8dedb299ab;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?>
</body>
</html>