<?php
/**
* WoltLab Community Framework
* Template: aboutme
* Compiled at: Tue, 13 Aug 2013 11:11:18 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'aboutme';
?>
<?php
$outerTemplateName498e3b9baf0eef331a19998fee5924483b7ff387 = $this->v['tpl']['template'];
$this->includeTemplate('documentHeader', array(), (1 ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName498e3b9baf0eef331a19998fee5924483b7ff387;
$this->v['tpl']['includedTemplates']['documentHeader'] = 1;
?>
<head>
	<title>Über uns - <?php echo StringUtil::encodeHTML(PAGE_TITLE); ?></title>
	<?php
$outerTemplateName9fc520135e33578790a6bbe0ff34216172fc5752 = $this->v['tpl']['template'];
$this->includeTemplate('headInclude', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName9fc520135e33578790a6bbe0ff34216172fc5752;
$this->v['tpl']['includedTemplates']['headInclude'] = 1;
?>
</head>
<body<?php if (isset($this->v['templateName'])) { ?> id="tpl<?php echo StringUtil::encodeHTML(ucfirst($this->v['templateName'])); ?>"<?php } ?>>
<?php
$outerTemplateName0a5515d1c977d82a2cfee3c140eb47f4625d6741 = $this->v['tpl']['template'];
$this->includeTemplate('header', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateName0a5515d1c977d82a2cfee3c140eb47f4625d6741;
$this->v['tpl']['includedTemplates']['header'] = 1;
?>

<div id="main">
	<ul class="breadCrumbs">
		<li><a href="index.php?page=Index<?php echo SID_ARG_2ND; ?>"><img src="<?php echo StyleManager::getStyle()->getIconPath('indexS.png'); ?>" alt="" /> <span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo StringUtil::encodeHTML(PAGE_TITLE); ?><?php $_lang6d01a16f119abbe8933eb9e0af6e7315e6ee148f = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_lang6d01a16f119abbe8933eb9e0af6e7315e6ee148f, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a> &raquo;</li>
	</ul>

<div class="mainHeadline">
	<img src="<?php ob_start(); ?><?php echo StringUtil::encodeHTML(ABOUTMEPAGE_ICON); ?><?php $_icon5e33729c04d2487d29555d6889cd7e5a3f4a486b = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon5e33729c04d2487d29555d6889cd7e5a3f4a486b); ?>" alt="" />
<div class="headlineContainer">
    <h2><?php echo StringUtil::encodeHTML(ABOUTMEPAGE_TITLE); ?></h2>
    <p> <?php echo StringUtil::encodeHTML(ABOUTMEPAGE_DESCRIPTION); ?></p>
</div>
</div>

<?php if (isset($this->v['userMessages'])) { ?><?php echo $this->v['userMessages']; ?><?php } ?>


	<div class="border">
		<div class="layout-3">
			<div class="columnContainer">
				<div class="column second container-1">
					<div class="columnInner">
						<?php if (ABOUTMEPAGE_ABOUTUSTITLE) { ?>	
						<h3 class="subHeadline"><?php echo StringUtil::encodeHTML(ABOUTMEPAGE_ABOUTUSTITLE); ?></h3>
						<div class="contentBox">
						<p><?php if (ABOUTMEPAGE_ABOUTUSHTML != '0') { ?><?php echo ABOUTMEPAGE_ABOUTUSCONTENT; ?><?php } else { ?><?php echo nl2br(htmlspecialchars(ABOUTMEPAGE_ABOUTUSCONTENT)); ?><?php } ?></p>
					</div>
						<?php } ?>
						
					 </div>
				</div>
			</div>
	</div>
 </div>
</div>

<p><?php
$outerTemplateNameaa88cf66cabfdaa060011567d2b09d57f4ac6019 = $this->v['tpl']['template'];
$this->includeTemplate('footer', array(), (false ? 1 : 0));
$this->v['tpl']['template'] = $outerTemplateNameaa88cf66cabfdaa060011567d2b09d57f4ac6019;
$this->v['tpl']['includedTemplates']['footer'] = 1;
?></p>
</body>
</html>