<?php
/**
* WoltLab Community Framework
* Template: imageViewer
* Compiled at: Tue, 13 Aug 2013 17:19:31 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'imageViewer';
?>
<script type="text/javascript" src="<?php echo RELATIVE_WCF_DIR; ?>js/ImageViewer.class.js"></script>
<script type="text/javascript">
	//<![CDATA[			
	// when the window is fully loaded, add image viewer
	Event.observe(window, 'load', function() {
		new ImageViewer($$('.enlargable'), {
			langCaption		: 'this.links.length > 1 ? "Image " + (this.currentIndex + 1) + " of " + this.links.length + (this.currentLink.title ? (" - " + this.currentLink.title) : "") : (this.currentLink.title ? this.currentLink.title : "")',
			langPrevious		: 'Previous image',
			langNext		: 'Next image',
			langPlay		: 'Start slideshow (changes the image every 5 seconds)',
			langPause		: 'Stop slideshow',
			langEnlarge		: 'Show only this image (quits the image viewer)',
			langClose		: 'Close',
			imgBlankSrc		: '<?php echo RELATIVE_WCF_DIR; ?>images/imageViewer/blank.png',
			imgMenuSrc		: '<?php echo RELATIVE_WCF_DIR; ?>images/imageViewer/menu.png',
			imgPlaySrc		: '<?php ob_start(); ?>imageViewer/playM.png<?php $_icon6648008347c5f2dd62253a8fa0e2e2ba7fc1a955 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon6648008347c5f2dd62253a8fa0e2e2ba7fc1a955); ?>',
			imgPreviousSrc		: '<?php ob_start(); ?>imageViewer/previousM.png<?php $_iconab8a02e05e442416bbaf9fd65b68c68d784912d8 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconab8a02e05e442416bbaf9fd65b68c68d784912d8); ?>',
			imgNextSrc		: '<?php ob_start(); ?>imageViewer/nextM.png<?php $_icon43b2fcd89487041417a0f15838b16f1b48ad8c21 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon43b2fcd89487041417a0f15838b16f1b48ad8c21); ?>',
			imgEnlargeSrc		: '<?php ob_start(); ?>imageViewer/enlargeM.png<?php $_icon6d8cbdd5be59f0f642ce3b48e6185aac01a46124 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon6d8cbdd5be59f0f642ce3b48e6185aac01a46124); ?>',
			imgPauseSrc		: '<?php ob_start(); ?>imageViewer/pauseM.png<?php $_icon43c3340fc783740f5f79a7e338320549efd63261 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon43c3340fc783740f5f79a7e338320549efd63261); ?>',
			imgCloseSrc		: '<?php ob_start(); ?>imageViewer/closeM.png<?php $_icon6c36187dfa808a0a82ed04d1f0073abce4bbc7f1 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon6c36187dfa808a0a82ed04d1f0073abce4bbc7f1); ?>',
			imgPlayHoverSrc		: '<?php ob_start(); ?>imageViewer/playHoverM.png<?php $_iconbc76588669ebde024eb9022529deb245f96dd205 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconbc76588669ebde024eb9022529deb245f96dd205); ?>',
			imgPreviousHoverSrc	: '<?php ob_start(); ?>imageViewer/previousHoverM.png<?php $_iconbee868170771f5533b08eb920384f3dd243c0f0f = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_iconbee868170771f5533b08eb920384f3dd243c0f0f); ?>',
			imgNextHoverSrc		: '<?php ob_start(); ?>imageViewer/nextHoverM.png<?php $_icon284c704240965ab1da087ca25a2ddfb78c73586e = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon284c704240965ab1da087ca25a2ddfb78c73586e); ?>',
			imgEnlargeHoverSrc	: '<?php ob_start(); ?>imageViewer/enlargeHoverM.png<?php $_icon0fda308d7c137dff6e04361995ab5a8d0e6f7e76 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon0fda308d7c137dff6e04361995ab5a8d0e6f7e76); ?>',
			imgPauseHoverSrc	: '<?php ob_start(); ?>imageViewer/pauseHoverM.png<?php $_icon47e1959220deb00683ca93a18199425acc91173e = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon47e1959220deb00683ca93a18199425acc91173e); ?>',
			imgCloseHoverSrc	: '<?php ob_start(); ?>imageViewer/closeHoverM.png<?php $_icon8884f43e5b6ff1bd68372d93f9527f3c2a46f105 = ob_get_contents(); ob_end_clean(); echo StyleManager::getStyle()->getIconPath($_icon8884f43e5b6ff1bd68372d93f9527f3c2a46f105); ?>'	
		});
	});
//]]>
</script>