<?php
/**
* WoltLab Community Framework
* Template: footerMenu
* Compiled at: Tue, 13 Aug 2013 11:37:07 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->v['tpl']['template'] = 'footerMenu';
?>
<?php if (count($this->v['this']->getPageMenu()->getMenuItems('footer')) > 0) { ?>
	<div id="footerMenu" class="footerMenu">
		<div class="footerMenuInner"><?php $this->assign('menuItemCounter', 0); ?><?php $this->assign('menuItemCount', count($this->v['this']->getPageMenu()->getMenuItems('footer'))); ?><ul><?php
if (count($this->v['this']->getPageMenu()->getMenuItems('footer')) > 0) {
foreach ($this->v['this']->getPageMenu()->getMenuItems('footer') as $this->v['item']) {
?><?php $this->assign('menuItemCounter', $this->v['menuItemCounter']+1); ?><li id="mainMenuItem<?php echo $this->v['item']['menuItemID']; ?>"<?php if ($this->v['item']['activeMenuItem'] || $this->v['menuItemCounter'] == 1 || $this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?> class="<?php if ($this->v['menuItemCounter'] == 1) { ?>first<?php } elseif ($this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?>last<?php } ?><?php if ($this->v['item']['activeMenuItem']) { ?><?php if ($this->v['menuItemCounter'] == 1 || $this->v['menuItemCounter'] == $this->v['menuItemCount']) { ?>Active<?php } else { ?>active<?php } ?><?php } ?>"<?php } ?>><a href="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemLink']); ?>" title="<?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_langfc0d8430861ee7d4bc1bb1f8fdc6124308e6d6a0 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langfc0d8430861ee7d4bc1bb1f8fdc6124308e6d6a0, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?>"><?php if ($this->v['item']['menuItemIconS']) { ?><img src="<?php echo StringUtil::encodeHTML($this->v['item']['menuItemIconS']); ?>" alt="" /> <?php } ?><span><?php $this->tagStack[] = array('lang', array()); ob_start(); ?><?php echo $this->v['item']['menuItem']; ?><?php $_langa65a7a39bb9a3b58fbfc02b1425c1b276953b622 = ob_get_contents(); ob_end_clean(); echo WCF::getLanguage()->getDynamicVariable($_langa65a7a39bb9a3b58fbfc02b1425c1b276953b622, $this->tagStack[count($this->tagStack) - 1][1]); array_pop($this->tagStack); ?></span></a></li><?php } } ?></ul>
		</div>
	</div>
<?php } ?>